### ISSUE TITLE
tracking no-data for GDAL datasets in ARIA products

### ISSUE THREAD

**Issue by dbekaert** [insarlab/MintPy#100]
@hfattahi think we might need to account for the no-data values in the connected component data for ARIA, perhaps in general as well for unwrapped etc. @bbuzz31 noticed some issue when using the unwrap correction using connected component to complain about negative value.

For example, zero is a connected component and therefore we set no-date value -1 in the ARIA product. Suggest to use something like the following to find the no-data values, and then set it to a value MintPy knows to ignore? Not sure if this would need to be 0 or a NaN or so?

For loop on line 155 in **prep_aria.py** each time when a band is loaded.
```
   bnd = dsUnw.GetRasterBand(ii+1)
   try:
        NoData = bnd.GetNoDataValue()
   except:
        NoData = None
```

**Comment by hfattahi** [comment]
@dbekaert Yes I agree that we should better track NoData values. I believe Mintpy currently considers zero unwrapped phase as NoData and consistent with isce2 the connected component label of "0" is considered invalid. @yunjunz please correct me if I'm wrong.

In the meantime I think we can just shift the ARIA connected components by "1" while we load them to Mintpy and that should allow to use the unwrapping error correction code without modifications. something like this in prep_aria.py lines 126-127 :

```
bnd = dsComp.GetRasterBand(ii+1)
h5["connectComponent"][ii,:,:] = bnd.ReadAsArray() + 1
```
@dbekaert @bbuzz31 If you confirm this temporary fix is useful, we can commit it.

**Comment by yunjunz** [comment]
> I believe Mintpy currently considers zero unwrapped phase as NoData and consistent with isce2 the connected component label of "0" is considered invalid. @yunjunz please correct me if I'm wrong.

This is correct @hfattahi.

**Comment by dbekaert** [comment]
@hfattahi this would make connected component 0 be 1, and affect the current MintPy masking based on connected component 0. The no-data value for the connected component (i.e. currently -1) corresponds to the data outside the swath in the geo-coded space. Suggest to not shift the connected component, but instead put anything smaller than 0 to 0 as well. We are using no-data of 0 for unwrapped phase, so the current approach should be ok for now. 


```
bnd = dsComp.GetRasterBand(ii+1)
raster = bnd.ReadAsArray()
raster[raster<0]=0
h5["connectComponent"][ii,:,:] = raster
```

Going forward no-data could change in the product, but no-data value in gdal will reflect any changes. Long-term fix would remain to leverage "no-data" from raster and setting accordingly in MintPy.

**Comment by yunjunz** [comment]
@dbekaert another cause of the issue regarding the unwrapping error correction using connected components is data type: it should be bool, not int16.

https://github.com/insarlab/MintPy/blob/master/mintpy/prep_aria.py#L172

**Comment by dbekaert** [comment]
@yunjunz would that not lead to a true/false like condition for connected components?
Connected components per ARIA product run from -1 (no-data), 0 (decorrelated), 1-20 (regions).
Does MintPy only expect 0 (decorrelated + no-data) and 1 (regions)?

**Comment by yunjunz** [comment]
@dbekaert, I was wrong, mintpy supports both `byte` and `bool` type.

From my limited tests, your suggestion would work.

I agree that in the long term, mintpy should also be able to handle the no-data value.

**Comment by dbekaert** [comment]
@yunjunz O, great. Byte would work. Suggest upon loading to map the -1 to 0, and with the byte range we should allow time-series of up to 12 ARIA GUNW frames which is sufficient for sure.

**Comment by yunjunz** [comment]
Great. The byte range can be easily extended if more frames are required in the future.

**Comment by dbekaert** [comment]
Looks good @yunjunz!

**Comment by ehavazli** [comment]
Hi @yunjunz and @hfattahi 
I have another case in which no-data tracking is an issue
You can see below the average coherence plot I made using aria-tools:
<img width="1305" alt="Screen Shot 2019-07-25 at 4 11 32 PM" src="https://user-images.githubusercontent.com/6526589/61914866-e6dde380-aef6-11e9-89da-165551b6fdab.png">

And this is what my network looks like when I upload it to MintPy (0.2 coherence threshold)

<img width="1191" alt="Screen Shot 2019-07-25 at 4 15 59 PM" src="https://user-images.githubusercontent.com/6526589/61915010-81d6bd80-aef7-11e9-93e2-3767c4e0b0b9.png">

and here is the coherence history:

<img width="1040" alt="Screen Shot 2019-07-25 at 4 16 31 PM" src="https://user-images.githubusercontent.com/6526589/61915040-9adf6e80-aef7-11e9-8177-3aa3eec57951.png">

Can you confirm this discrepancy doesn't occur in other parts of the process?

**Comment by hfattahi** [comment]
@ehavazli 
1) How do you run plot_network.py exactly. Have you specified any mask in particular? specifying a mask may change the plot. But still the mask would be the same for the whole stack. Ideally we want to have the mask to be different for each interferogram which is not currently possible. 
 
2) What is the nodata value for coherence in your aria tools plot. I assume its based on the nodata value for unwrapped phase. Is that right?

**Comment by ehavazli** [comment]
>     1. How do you run plot_network.py exactly. Have you specified any mask in particular? specifying a mask may change the plot. But still the mask would be the same for the whole stack. Ideally we want to have the mask to be different for each interferogram which is not currently possible.

I am using the mask with ariaTSsetup.py so the extracted data is masked already. I don't use any masks in MintPy process.





>     2\. What is the nodata value for coherence in your aria tools plot. I assume its based on the nodata value for unwrapped phase. Is that right?

I don't have the no-data value right now but we are tracking it with gdal in the process and ignoring it while calculating average coherence in a product.

**Comment by dbekaert** [comment]
ARIA tools tracks the no-data in all of its under-laying processing as we leverage GDAL for mosaicing. We track this on the product level such we are flexible in case a different value is chosen in future for a product. The individual merged files written out should already contain a no-data value in the vrt. e.g. see gdalinfo on one of the YYYYMMDD_YYYYMMDD.vrt files.

I would therefore recommend that prep_aria.py which uses GDAL to load the vrt stack should check what the no-data value is and then set the Nan, or other value which mintpy assumes as no-data. 

see this earlier comment on retrieving the no-data


> ```
>    bnd = dsUnw.GetRasterBand(ii+1)
>    try:
>         NoData = bnd.GetNoDataValue()
>    except:
>         NoData = None
> ```

**Comment by yunjunz** [comment]
I like @dbekaert's idea, NaN is ignored in almost all process in mintpy, so I think it should work.

I already tried to do that for the geometry files as below:
https://github.com/insarlab/MintPy/blob/master/mintpy/prep_aria.py#L238

**Comment by ehavazli** [comment]
@yunjunz 
incidence angle is properly imported because of that line. it woudl be good to make sure that the rest of the process also follows the same path

**Comment by yunjunz** [comment]
From the SanFran dataset, the NoDataValue is `None` for some interferograms that I checked. So it does not seem to need to be handled. The committed prep_aria.py already assign NaN value to all geometry dataset whenever it's possible.

@ehavazli, it seems like your request of the current plot is because there is no mask used at all to calculate the mean coherence, and it can be solved by generating a common mask file to be able to identify those pixels with NoDataValue on the geometry, and to exclude them while calculating mean coherence, right?

This can be done by writing the mask data into the `waterMask` dataset, which is now used by default in mintpy, whenever it's available. I know the name does not match. In the future, when the real water mask file is available from ARIA-tools, we could merge these two: `validPixelMask` and `landPixelMask`, into `waterMask` dataset.

**Comment by yunjunz** [comment]
Plotting the average spatial coherence of the stack, to me, is useful because it helps to identify overall low coherent interferograms, thus, it makes more sense to me when the same mask is used during the calculation for different interferograms. 

An extreme example would be: one very low coherent interferogram with only a small area coherent, i.e. in the city. If an adaptive mask is used, and those low coherent area are masked out, the calcualted average coherent will still be high. And this should not be what user want.

**Comment by dbekaert** [comment]
> From the SanFran dataset, the NoDataValue is `None` for unw, coh and comp datasets for some interferograms that I checked. So it does not seem to need to be handled. The committed prep_aria.py already assign NaN value to all geometry dataset whenever it's possible.
> 

Are you referring to the files in the coherence, connectedComponents, unwrappedPhase folders? I checked and i get no-data values back. You mentioned some have no-data, which would interesting to confirm and should be fixed if its the case. If you can provide us with an example we could look into it. Copying @sssangha in case this needs further follow-up.

I was not able to replicate:
```
gdalinfo unwrappedPhase/20150507_20150401.vrt
gdalinfo connectedComponents/20150507_20150401.vrt
gdalinfo coherence/20150507_20150401.vrt
```
e.g. for connectedComponents:
```
Band 1 Block=128x128 Type=Int16, ColorInterp=Undefined
  NoData Value=-1
```

Given that the stack files point to these vrt files it should also have no-data set.
```
gdalinfo cohStack.vrt
Driver: VRT/Virtual Raster
Files: cohStack.vrt
       /Users/dbekaert/Desktop/Time-series/CA_137/coherence/20180322_20180226.vrt
       /Users/dbekaert/Desktop/Time-series/CA_137/coherence/20170315_20170114.vrt
```

**Comment by yunjunz** [comment]
Hi @dbekaert, I only checked a few interferograms and don't know about the rest of them. The gdalinfo return looks fine as your example above, but I can not get this value in Python, maybe not in a proper way, any suggestions?

Debug from `prep_aria.py` [L198](https://github.com/insarlab/MintPy/blob/master/mintpy/prep_aria.py#L198)

```
(Pdb) print(dsUnw.GetRasterBand(1).GetNoDataValue())
None
(Pdb) print(d12)
20150512_20150605
(Pdb) print(dsComp.GetRasterBand(1).GetNoDataValue())
None
(Pdb) 
```

Output from `gdalinfo`:

```
Band 1 Block=128x128 Type=Int16, ColorInterp=Undefined
  NoData Value=-1
```

For the loaded ifgramStack.h5 in mintpy, I am gonna translate NoData value (instead of using a fixed value that we currently know, to be in a more generic way) for unwrapped phase and spatial coherence to zero, as mintpy and isce currently understands; and NoData value for connected components to zero.
