### ISSUE TITLE
Seamless mosaicking of interferograms for HyP3 products

### ISSUE THREAD

**Issue by Arcyzr** [insarlab/MintPy#1027]
Hello Developers, I am interested in using hyp3 interferograms for Small Baseline InSAR processing in Mintpy. Given that my study area spans two regions of the same satellite orbit, does Mintpy offer any handling for seamless mosaicking of interferograms?

**Comment by yunjunz** [comment]
mintpy does not handle the phase stitching for the interferogram stack. [ARIA-tools](https://github.com/aria-tools/ARIA-tools) has this capability for ARIA products. You may get a more constructive answer from HyP3 developers in their forum/github.
