### ISSUE TITLE
Ionospheric correction for ALOS PALSAR

### ISSUE THREAD

**Issue by mohseniaref** [insarlab/MintPy#1036]
Hi,

I think due to update for ionospheric correction for Sentinel data, ALOS PALSAR data ionospheric correction is not possible with newer version of Mintpy

Best regards,
Mohammad
PS: @yuankailiu

**Comment by yunjunz** [comment]
Hi Mohammad, please elaborate more on the details, following the debug report template, so that we could diagnose. I think neither I nor Kai has an example ALOS dataset with ionospheric estimations to test.

**Comment by mohseniaref** [comment]
Hi @yunjunz ,

I will email you  and Kai soon! I am uploading Mintpy dataset of ionospheric correction for ALOS PALSAR

Best regards,
Mohammad
