### ISSUE TITLE
hdfeos5_2json_mbtiles.py

### ISSUE THREAD

**Issue by fukun364202818** [insarlab/MintPy#1042]
**Description of the problem**
Hello! I generated KeyError when converting the *.he5 file generated by save_hdfeos5.py using hdfeos5_2json_mbtiles.py: "Unable to synchronously open object (object 'latitude' doesn't exist)", then I looked at the *.he5 file and found that there was indeed no latitude, longitude. Why is that? How do I fix this? thank you

**Full script that generated the error**
Unable to synchronously open object (object 'latitude' doesn't exist)

# read lat and long. MintPy doesn't seem to support this yet, so we use the raw
# h5 file object
f = h5py.File(he_obj.file, "r")
lats = np.array(f["HDFEOS"]["GRIDS"]["timeseries"]["geometry"]["latitude"])
lons = np.array(f["HDFEOS"]["GRIDS"]["timeseries"]["geometry"]["longitude"])

**Full error message**

Unable to synchronously open object (object 'latitude' doesn't exist)

**System information**

* Operating system: Linux
* Python environment: conda
* MintPy version: 1.5.1
* Your custom / default template file (if the bug is related to a specific dataset):

**Comment by yunjunz** [comment]
Close this issue as it's related to [`insarmaps_scripts`](https://github.com/geodesymiami/insarmaps_scripts) and has been tracked [there](https://github.com/geodesymiami/insarmaps/issues/87).
