### ISSUE TITLE
SNAP geocoded products support

### ISSUE THREAD

**Issue by yunjunz** [insarlab/MintPy#105]
Hi @andretheronsa, thank you for adding `prep_snap.py` #101! Below are things that I can think of to make the SNAP+MintPy workflow as smooth as the ISCE+MintPy workflow.

+ [x] 1. Is it possible to add `interferograms` as the root directory of all interferograms? An example is shown below. This is preferred for a more simple root directory, so that `interferograms` folder can be in the same level as `mintpy` folder.

```
/interferograms
    /20190427_20190602
        /20190427_20190602_coh_tc.data
            /coh.img                                    #mintpy.load.corFile
            /coh.hdr
        20190427_20190602_coh_tc.dim
        /20190427_20190602_filt_int_sub_tc .data
            /filt_int.img                                #mintpy.load.intFile
            /filt_int.hdr
        20190427_20190602_filt_int_sub_tc.dim
        /20190427_20190602_unw_tc .data
            /filt_unw.img                             #mintpy.load.unwFile
            /filt_unw.hdr
        20190427_20190602_unw_tc.dim
    ...
/dem_tc.data 
    /dem.img                                         #mintpy.load.demFile
    /dem.hdr
dem_tc.dim
/mintpy
```

Once the question above is settled, `prep_snap` can be adjusted to run the complex metadata extraction function (`utm_dim_to_rsc()`) once and save the result into a simple text file, like `data.rsc` from prep_isce.py; and for the rest files, the code can search for `data.rsc` and used directly instead of calling `utm_dim_to_rsc()` again.

+ [x] 2. Could you write a document of your SNAP workflow, if there are more details than your comment inside prep_snap, on the mintpy's [wiki](https://github.com/insarlab/MintPy/wiki) or somewhere else you prefer? Other users who are interested can go there for detailed instruction to prepare SNAP products.

**Comment by yunjunz** [comment]
@andretheronsa, if you have an updated file structure of the dataset that you uploaded to box, please let me know. I will use your exact file structure and move forward to test load_data.py and smallbaselineApp.py for it.

**Comment by andretheronsa** [comment]
@yunjunz
1) I have uploaded the test data set with an updated structure to box.
1.1) Is there a specific reason _utm_dim_to_rsc()_ should only run once? I expect all the products to contain all the metadata and it runs within a second or two in my machine. At least for testing I propose we leave it as is.
2) Yes, I will document the SNAP workflow to the wiki as soon as I have successfully tested it. Once done I will post to the ESA STEP forums where people should be excited I am sure. They can then check up and improve my methodology too.
3) I have attempted to run the test dataset, it creates the .rsc files but when loading data returns error (Can not reshape numpy.array) in _utils.read_binary()_ -

**Comment by yunjunz** [comment]
> Is there a specific reason utm_dim_to_rsc() should only run once?

@andretheronsa, no there is no strong reason. I though it might be slow, but it went through pretty fast. I agree that the current form works great.

**Comment by yunjunz** [comment]
@andretheronsa I have uploaded a custom template file `mintpy/SAfricaSenAT29.txt`  in Box to test `load_data.py` to make sure we are on the same page for this. I also got an numpy reshape/broadcast error as below. This is because the first 3 interferograms "20190303_*" have size of 1943*1953 while the 4th interferogram "20190315_20190327" has size of 1942*1953. 

Could you make the size (row and column number) of all interferograms the same in SNAP? Otherwise, we could write an function in mintpy to adjust for it: fill NaN / Zero value in the smaller size file, or subset the larger size file.

```
[yunjunz:test/SAfricaSenAT29/mintpy] yunjunz% load_data.py -t SAfricaSenAT29.txt
SAR platform/sensor : Sen
processor: snap
--------------------------------------------------
prepare metadata files for snap products
prep_snap.py ../interferograms/*/*/Unw_*.img
prep_snap.py ../interferograms/*/*/coh_*.img
prep_snap.py ../dem_tc.data/dem*.img
--------------------------------------------------
searching interferometric pairs info
input data files:
unwrapPhase     : ../interferograms/*/*/Unw_*.img
coherence       : ../interferograms/*/*/coh_*.img
number of unwrapPhase     : 21
number of coherence       : 21
--------------------------------------------------
searching geometry files info
input data files:
height          : ../dem_tc.data/dem_VV.img
--------------------------------------------------
updateMode : True
compression: None
/Users/yunjunz/insarlab/test/SAfricaSenAT29/mintpy/inputs/ifgramStack.h5 exists, but can not read, remove it.
rm /Users/yunjunz/insarlab/test/SAfricaSenAT29/mintpy/inputs/ifgramStack.h5
--------------------------------------------------
create HDF5 file /Users/yunjunz/insarlab/test/SAfricaSenAT29/mintpy/inputs/ifgramStack.h5 with w mode
create dataset /unwrapPhase of <class 'numpy.float32'>   in size of (21, 1942, 1953) with compression = None
[======>                 14%                       ] 20190303_20190408    0s /     0sTraceback (most recent call last):
  File "/Users/yunjunz/development/python/MintPy/mintpy/load_data.py", line 568, in <module>
    main()
  File "/Users/yunjunz/development/python/MintPy/mintpy/load_data.py", line 543, in main
    extra_metadata=extraDict)
  File "/Users/yunjunz/development/python/MintPy/mintpy/objects/stackDict.py", line 148, in write2hdf5
    ds[i, :, :] = data
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/h5py/_hl/dataset.py", line 707, in __setitem__
    for fspace in selection.broadcast(mshape):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/h5py/_hl/selections.py", line 299, in broadcast
    raise TypeError("Can't broadcast %s -> %s" % (target_shape, self.mshape))
TypeError: Can't broadcast (1943, 1953) -> (1942, 1953)
```

**Comment by andretheronsa** [comment]
@yunjunz Ok, I have noticed that the outputs can be out by a line or so - likely due to small inaccuracies with SNAP subset by polygon tool or the terrain correction step. I generated these using my automated SNAP program so I don't think I can get much better using SNAP tools.
Since it is such a small discrepancy I think the simplest would be to fill in NaN values. Does Mintpy have utils for doing this, or something similar? 

*Thanks for the custom template file, looks the same as mine. I see it looks for a capitalized "Unw" file ("../interferograms/*/*/Unw_*.img"). The files aren't capitalized but nice to see it worked anyways +1.

**Comment by yunjunz** [comment]
@andretheronsa where should the smaller size file be filled the extra line(s), at the top or at the bottom?

**Comment by andretheronsa** [comment]
O, so filling with NaN is not spatially aware and the data will shift? I will have to check tomorrow.  
For testing it does not matter but then I think spatially subsetting the scenes will be safer.

**Comment by yunjunz** [comment]
I agree with spatially subsetting, it could be easily done in [load_data.main()](https://github.com/insarlab/MintPy/blob/master/mintpy/load_data.py#L537) using `box` argument, we just need a separate small function to adjust its value when `snap` processor. Even so, the shift direction still needs to be checked.

**Comment by yunjunz** [comment]
Hi @andretheronsa, `smallbaselineApp.py` should work for your example dataset now, please check it.

The current `load_data.py` is taking the minimum file size as the reference, and subsetting the rest files that have different size. Note that this **assumes**: files with different size have **extra line(s) at the bottom (last rows)**, or **extra column(s) at the right (last columns)**, which might not be true. 

And in this way, if the shift direction for the larger file, with respect to the small file, is not at the bottom, or sometimes bottom and sometimes top, there is no easy way to handle it in mintpy and it would be better to do it in SNAP.

Another more conservative way is: to load files with the most common size and to exclude (not load) the rest files.

**Comment by andretheronsa** [comment]
@yunjunz It works!! I am in total shock

**Comment by andretheronsa** [comment]
@yunjunz It works! I am in shock. It has taken me a very, very long time to get open source time-series InSAR software that actually works. Thank you and the team for all the hard work. It really is amazing, I am so excited for generating proper results now.
![image](https://user-images.githubusercontent.com/33958609/61378903-b074e880-a8a6-11e9-9a25-f9cf8cebfac1.png)

I think your subsetting work around is good enough to at least avoid the program from failing - proper subsetting should then be done before hand.

Would it makes sense to alternatively specify a bit smaller common area using the mintpy.subset.lalo default ?

**Comment by yunjunz** [comment]
> Would it makes sense to alternatively specify a bit smaller common area using the mintpy.subset.lalo default ?

Yes, using either `mintpy.subset.yx` or `mintpy.subset.lalo` should work too. The current workaround solution is setting the subset internally.

**Comment by yunjunz** [comment]
https://github.com/insarlab/MintPy/wiki/SNAP-input-data
