### ISSUE TITLE
prep_isce.py KeyError

### ISSUE THREAD

**Issue by blueswordgis** [insarlab/MintPy#1095]
I processed the Sentinel 1 data using ISCE2 and processed the data using prep_isce and got an error with the prompt as shown. Deleted the data after Feb 21, 2023 and it was processed successfully.
![image](https://github.com/insarlab/MintPy/assets/84838024/d65a86b1-1ef0-4773-a0aa-b6c9d231f778)

* Operating system: Linux
* Python environment: conda, mamba setup
* MintPy version: 1.5.2

**Comment by yunjunz** [comment]
The error says the baseline file for 20230221 is not found in the `baselines` folder. Could you confirm?

**Comment by ditafaith** [comment]
Hi @yunjunz, 
It is about the stage after prep_isce, specifically to apply subset `mintpy.subset.lalo` on MintPy's config.
I processed ALOS data using ISCE2 and MintPy, which followed [this structure](https://mintpy.readthedocs.io/en/latest/dir_structure/#isce_alosstack). Also, there is no problem with data.rsc. 

However, when I try to make a subset then became error as follows,
_File "/home/saka/miniconda3/lib/python3.9/site-packages/mintpy/utils/utils0.py", line 232, in azimuth_ground_resolution
    Re = float(atr['EARTH_RADIUS'])
KeyError: 'EARTH_RADIUS'_

When I checked the input files are in RADAR coodinates (*.unw). 
Is it possible to subset using `mintpy.subset.lalo` ?
Looking from your views.

**Comment by yunjunz** [comment]
@ditafaith please follow the issue template to provide a complete description for diagnosis and error re-production.

**Comment by ditafaith** [comment]
Hi @yunjunz 
Thank you for taking care about this issue. I [posted it](https://github.com/insarlab/MintPy/issues/1256).
