### ISSUE TITLE
Change Mix, Max Range of Colorbar

### ISSUE THREAD

**Issue by gjustin40** [insarlab/MintPy#1101]
I'm trying to visualize the result of displacement with velocity.

For personal reasons, I want to customize the range of the colorbar's min/max value.
The purpose of this customization is to normalize the displacement values by color to make them more visible.

Is there any function in MintPy to set the minimum and maximum range of the colorbar?
If not, I will just read the `.h5` file and visualize it myself.

Thank you.

**Comment by yunjunz** [comment]
The `view.py` command is very powerful. What you are looking for is `view.py -v` option. Run `view.py --help` for detailed usage and examples.
