### ISSUE TITLE
Release new version of MintPy to support HyP3 Burst InSAR products

### ISSUE THREAD

**Issue by forrestfwilliams** [insarlab/MintPy#1117]
**Description of the desired feature**

@yunjunz ASF's HyP3 team has just released our burst InSAR products to production :tada:! We would love for MintPy to support these products, and the needed functionality has already been added in PR #1074. However, these changes still need to be released. Would you be willing to create a new release of MintPy so that users installing from pip/conda can use this functionality?

I'm happy to create an example dataset as you mentioned in PR #1074 once this version has been released.

**Are you willing to help implement and maintain this feature?**

- [x] Yes
- [ ] No

**Comment by yunjunz** [comment]
That's great! Sure, I have a few bugfixes to push, and after that will cut for a new release. It should be done in 2 days max.

**Comment by yunjunz** [comment]
@forrestfwilliams The new release is cut https://github.com/insarlab/MintPy/releases/tag/v1.5.3. It should be in PyPI right away, and in conda-forge in a few hours. Cheers.

**Comment by yunjunz** [comment]
Thanks to the help of @jhkennedy, version 1.5.3 is now available on conda-forge.
