### ISSUE TITLE
Deprecated numpy.float usage in smallbaselineApp.py breaks with numpy > 1.24.0

### ISSUE THREAD

**Issue by scikyle** [insarlab/MintPy#1132]
Running Linux Mint 21.2 with Python 3.8.12 in an Anaconda environment, Mintpy 1.5.0 and Numpy 1.24.3. While running a stack of ASF HyP3 Sentinel-1 IW images through a notebook, smallbaselineApp.py hits an error early in processing indicating `AttributeError: module 'numpy' has no attribute 'float'`.

After some searching, I found [a similar error with a different library](https://github.com/azuritecoin/OnnxDiffusersUI/discussions/63), and tried the suggested fix, rolling Numpy back to 1.23.4. After restarting the notebook environment using the regressed Numpy version, smallbaselineApp.py ran to successful completion. 

Further searching suggested that np.float was a deprecated alias that has now expired, which is substantiated by [the Numpy 1.24.0 release notes](https://numpy.org/doc/stable/release/1.24.0-notes.html). The table in [the Numpy 1.20.0 release notes](https://numpy.org/doc/stable/release/1.20.0-notes.html), which introduced the deprecation, offers alternative suggestions.

**Comment by yunjunz** [comment]
The deprecated usage of numpy.int/float etc. has been fixed since version 1.5.1, please use the latest release or development version.
