### ISSUE TITLE
rename --gnss-source from `JPL-SIDESHOW` to `SIDESHOW`

### ISSUE THREAD

**Issue by yunjunz** [insarlab/MintPy#1228]
**Description of the desired feature**

@rzinke Shall we rename the `--gnss-source JPL-SIDESHOW` to `--gnss-source SIDESHOW` for simplicity, and to be consistent with other values, e.g. `UNR` and `ESESES`? It's also easier to type.

**Are you willing to help implement and maintain this feature?**

- [x] Yes
- [ ] No

**Comment by rzinke** [comment]
Hi @yunjunz , sorry for the slow reply... "JPL-SIDESHOW" is the name that was suggested to me by the people who process those data. I also don't think "SIDESHOW" by itself is descriptive of the project or institution doing the processing. I think we should keep "JPL-SIDESHOW" as the name.

**Comment by yunjunz** [comment]
Thanks for the explanation. To encourage more usage of this option (by typing less), how about we use `JPL` instead? We could use a more unique name if more solutions from JPL are added in the future.

**Comment by rzinke** [comment]
I'm generally in favor of short names that encourage ease of use. Unfortunately, changing the name to just `JPL` I think that will lead to confusion, because at least two groups at JPL publish solutions: The ESESES project funds a joint team at SIO and JPL. JPL SIDESHOW is different.

Fair point about the abbreviations not being official names. I will check again with the JPL SIDESHOW team to see what they think.

**Comment by rzinke** [comment]
Hi Yunjun. I asked, and using 'SIDESHOW' is OK, although the team does want users to know that those data are official JPL products funded by NASA's Space Geodesy Task. A [citation](https://agupubs.onlinelibrary.wiley.com/doi/10.1029/2019EA000644) was also provided. So it sounds like we're good to go ahead and shorten the name, but do you think it would be appropriate to provide some references in the comments of the objects/gnss.py page?

**Comment by yunjunz** [comment]
Great. Sure, adding references in the code comments and/or in the help message is very encouraged, I will go ahead and issue a PR.
