### ISSUE TITLE
regularly updated docker image

### ISSUE THREAD

**Issue by andretheronsa** [insarlab/MintPy#123]
For convenience I have created a [docker](https://docs.docker.com/get-started/) image on Docker hub for Mintpy: ``https://hub.docker.com/r/andretheronsa/mintpy``
If this would be useful for the project, it can be added it as an installation option ?

It provides an easy way to have the configured MintPy environment ready.  
It is built on a base debian:stretch linux image using the installation instructions (setting up conda, environment, mintpy, pyaps, pykml etc).  

All you need is docker installed (on windows / linux / mac).
Pull the image from dockerhub with: ``docker pull andretheronsa/mintpy:latest``
Run an interactive shell session in the container with: ``docker run -it andretheronsa/mintpy:latest bash``
To map your data folder on host to the container add ``-v /path/to/data/dir:/home/work/`` to the docker run command.

The image is the first version and has not been tested much. It can be made smaller too.

**Comment by yunjunz** [comment]
This is great @andretheronsa! Yes, do a pull request to the `installation.md` please.

I don't have experience on `docker` yet. Is this image built based on the latest version on `insarlab/master` branch?

**Comment by hfattahi** [comment]
This is awesome and very useful. Maybe it should build the released version which is supposed to be stable. @dbekaert mentioned that ARIA folks where working on a docker image for Mintpy as well. David please feel free to add ARIA folks to the discussion if needed.

**Comment by dbekaert** [comment]
The main idea is to hook the circle-ci to docker such it attempt to re-build the docker regularly. Copying in @pymonger. We have not started with this yet, so could be good to combine the efforts.

**Comment by andretheronsa** [comment]
Great to see the excitement!

@yunjunz I have done a pull request for updated installation instructions.
The container was built yesterday - it pulls the latest version of insarlab/master from git during build time. So it will need to be rebuild with new releases.

@dbekaert  I do not have experience with Circle-ci but such a tool to rebuild the docker will be useful.

I have added the dockerfile in a root level docker directory to the pull request, I am not sure if this is the right place for it, but you guys can check out the file to see exactly how it creates the container.

Note that if you build a docker image yourself from the file it will copy over all content in the directory you build it from - that is why it is in it's own directory. The rest of Mintpy gets pulled into the container from github.

**Comment by andretheronsa** [comment]
After testing I just want to note two errors that had to be fixed in the docker container.
1) I had to install the zip package (for save_kmz.py etc.).
2) The /bin/sh shebang in top of shell scripts points to the default shell and seems to be written for bash. (https://askubuntu.com/questions/141928/what-is-the-difference-between-bin-sh-and-bin-bash). 
On Ubuntu it is Bash but since the docker is Debian it points to Dash. I just had symlink ./bin/sh to point to Bash instead.
It now gets to "Normal end of smallbaselineApp processing!"

**Comment by dbekaert** [comment]
Would you be able to share the recipe for making the docker? @pymonger

**Comment by pymonger** [comment]
@dbekaert @andretheronsa: take a look at the circleci config here: https://github.com/isce-framework/isce2/blob/master/.circleci/config.yml.
We have 3 workflows defined at the bottom:
- `test` - on creation of a pull request, builds ISCEv2 and runs through unit tests
- `build-deploy` - when a pull request is merged into master, it builds the docker image and pushes it up to dockerhub
- `weekly` - periodically builds the docker container based on the current state of the master branch and pushes it up to dockerhub

**Comment by jhkennedy** [comment]
This could also be setup as a GitHub Action which will publish docker images to the [GittHub container registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry).

That would make the container image show up as a "Package" on the left-side bar under "Releases" on the main repository page, and you could access it like:
```
docker pull ghcr.io/insarlab/mintpy:latest
```

I'd be happy to setup the above up if no one has a strong preference for using Circle-CI and Dockerhub. Possibly with @forrestfwilliams help if he's interested?

**Comment by forrestfwilliams** [comment]
Hey @jhkennedy, yes I'd enjoy working with you on this! How do we get started?

**Comment by jhkennedy** [comment]
Sounds good! @forrestfwilliams I'll put up a draft PR and request you as a reviewer and we can iterate from there.
