### ISSUE TITLE
Python process disappears

### ISSUE THREAD

**Issue by cyloveyou** [insarlab/MintPy#1248]
I'm using mintpy to process SBASInSAR, I encountered a small problem: when processing to the step shown in the figure, all python processes silently and wonderfully disappeared, and the CPU usage also reduced, does any big brother know why this is? Thank you very much!
![c216a67a845adb98f174cc302951a64](https://github.com/user-attachments/assets/a24cbfcd-f6bd-4c86-9011-1c63bdb27423)

![177f467ad1587af7bc8a6bd91d05689](https://github.com/user-attachments/assets/b4785a2b-42b2-4604-a261-887a98ba240b)

**Comment by yunjunz** [comment]
I am not sure what happened there, but the provided info is very limited, please dig more (with hardware/software environment, and/or log files) and elaborate. Also, this is an ISCE2 info, so I would recommend posting on the isce2 repo instead.
