### ISSUE TITLE
mintpy.load.connCompFile for GAMMA

### ISSUE THREAD

**Issue by HN-Jiang** [insarlab/MintPy#1252]
Dear Mintpy,
I'm currently using GAMMA+Mintpy. I try to follow the workflow from Jupyter notebook. And I want to use Bridging to correct unwrapping error. But I think all the manual book about gamma didn't mention that which file is needed for "mintpy.load.connCompFile" which is required by "mintpy.unwrapError.method "

Best regards
Haonan

**Comment by yunjunz** [comment]
Gamma does not provide connected components as far as I know, so you could not use the two unwrapping error correction methods provided in mintpy.
