### ISSUE TITLE
AssertionError: PyAPS: Mask array size mismatch

### ISSUE THREAD

**Issue by laxmangeo** [insarlab/MintPy#1264]
Hi sir,
          I got an error at the step - correct troposphere.
![mintpy](https://github.com/user-attachments/assets/6c2878a1-3249-40aa-a21b-a831ca3f90eb)
how can I solve this?

**Comment by ditafaith** [comment]
Hi @laxmangeo, just to make sure, have you setup the .cdsapirc in your home directory?

**Comment by laxmangeo** [comment]
yes,
![cdsaspric](https://github.com/user-attachments/assets/f3e60739-158a-4e67-80a5-44732fc34a59)

**Comment by laxmangeo** [comment]
yes,
![cdsaspric](https://github.com/user-attachments/assets/f7c6e605-c7e3-407d-9ca9-78c568de4660)

**Comment by yunjunz** [comment]
@laxmangeo you would want to modify your response and do not show this private account info of yours.
