### ISSUE TITLE
GAMMA product cannot be geocoded correctly

### ISSUE THREAD

**Issue by wwe-gif** [insarlab/MintPy#1270]
Hi, everyone!  when I use  Mintpy  to  process the result of GAMMA product, it looks like correct in the  whole process. But, when I look at  the geocoded product, value is zero for all, can anyone explain why is it?  please note that before geocoding, value is correct.

Here is my screenshot:

Before geocoding:

<img width="515" alt="image" src="https://github.com/user-attachments/assets/4bedd182-f0aa-4743-b45a-fdf33c6caae0">

After geocoding:

<img width="511" alt="image" src="https://github.com/user-attachments/assets/e486a481-14a7-4bcf-9489-62898b60c1bd">

and my configure file :

[sbas.txt](https://github.com/user-attachments/files/17117030/sbas.txt)

note that full script has no error

**Comment by yunjunz** [comment]
Please provide more information for diagnosis:
1. plot your velocity files before and after geocoding
2. plot your geometryRadar.h5 and geometryGeo.h5 file
3. and maybe share the above data files directly for error reproduction, either publically here or privately to me (yunjunz@outlook.com).

**Comment by wwe-gif** [comment]
Sorry,I have solved this later. this is due to wrong input files. GAMMA products use isometric projection(EQA) in default. but, in Mintpy UTM has been suggested in utils/prep_gamma.py&nbsp; file. so i change it into UTM. The point of problem is unit. After i change it into UTM, unit is m. however, the program need degree, so, i find that is wrong. Then, I input the original EQA files, it works successfully.
I think it may need to change the UTM info in prep_gamma.py. many may be mistaken by it.


Thanks!&nbsp; 




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "insarlab/MintPy"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月11日(星期一) 凌晨0:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [insarlab/MintPy] GAMMA product cannot be geocoded correctly (Issue #1270)





 
Please provide more information for diagnosis:
  
plot your velocity files before and after geocoding
 
plot your geometryRadar.h5 and geometryGeo.h5 file
 
and maybe share the above data files directly for error reproduction, either publically here or privately to me ***@***.***).

**Comment by yunjunz** [comment]
I am glad to hear you located the problem. Gamma is very flexible in terms of format, which is a good and bad thing at the same time. From my understanding, we need two examples: one in UTM, and one in EQA coordinates. Each of them needs an example dataset and a detailed data structure documentation, to avoid future confusion. I am not a Gamma user. You are more than welcome to contribute to this.
