### ISSUE TITLE
[Bug] Error of matrix multiplication in unwrap_error_phase_closure.py

### ISSUE THREAD

**Issue by lidar-nevermore** [insarlab/MintPy#1279]
I’m processing the stack of sentinel-1 bursts, and the program exits without reporting any errors.

It turns out that this is a bug of np.dot().

Bug occurs when running the following line in unwrap_error_phase_closure.py:
```
closure_pha = np.dot(C, unw)
```
In my application, the size of C is  (4575, 2069), and the size of unw is (2069, 45120).

[Here ](https://drive.google.com/file/d/1xGh5XIrH7p2Sr8Gw_gWcwEMpqN5E3td7/view?usp=sharing) is the data

Finally, I get through this via pytorch:
```
C_torch= torch.from_numpy(C)
unw_torch=torch.from_numpy(unw)
closure_pha=torch.mm(C_torch,unw_torch).numpy()
```

I'm using numpy 1.26.4, and I have not test the other versions. Maybe switching a new version of numpy will work, too.

Hope this bug can be fixed soon.

update: 
I allocated 64GB of memory for mintpy, which should be enough to complete the matrix multiplication.

I'm not sure how numpy uses the allocated memory throughout the calculation. 

If we cannot change the behavior of numpy.dot(), dynamically adjusting the data tiling strategy according to the number of triplets may be a possible solution.

update2:

I finally solved this issue by downgrading numpy to 1.25.0. Now mintpy works well with 16GB memory.

**Comment by yunjunz** [comment]
This seems like a `numpy` problem, please consider opening an issue on its repo instead. I will go ahead and close it since the mintpy code works with numpy-1.25.0 from your update.
