### ISSUE TITLE
move notebooks out of mintpy repo

### ISSUE THREAD

**Issue by yunjunz** [insarlab/MintPy#138]
This issue is to track the process of moving the jupyter notebooks out of MintPy repository because they are 1) generally much larger than the script and 2) might experience quite some details changes, leading to unnecessary loads of commit history.

To do list:
- [x] move the following notebooks to new repository `insarlab/MintPy-tutorial`
  -  `docs/tutorials` 
  -  `docs/examples/applications`
  -  `docs/examples/simulations`
- [x] move `docs/paper` to new repository `geodesymiami/Yunjun_et_al-2019-MintPy`.

Links to this notebooks will still be kept in MintPy repo.

**Comment by falkamelung** [comment]
I don't have too much a preference. I would like to eventually see other code (e.g. GBIS or MimSAR) next to MintPy. For that reason  `insarlab/MintPy-tutorial` may not be good unless we do `insarlab/mintpy-framework/mintpy` and `insarlab/mintpy-framework/mintpy-tutorial` but this looks to complicated. So maybe `geodesymiami` is better.

**Comment by yunjunz** [comment]
Hi @falkamelung, there is no question to me about `insarlab/MintPy-tutorial`. It should stick with `MintPy`.

My hesitate is only about the host location of `Yunjun_et_al-2019-MintPy`, which is only about the figures of the paper. Let me know your preference for this please.

**Comment by yunjunz** [comment]
Close this issue since all tasks are complete.

**Comment by dbekaert** [comment]
Input file "SanFranSenDT42.txt" missing in Mintpy-turorial repo, could not find it in Mintpy repo either.

**Comment by yunjunz** [comment]
I don't have it anymore in my local machine, I hope @hfattahi still has it. It could go to either `insarlab/MintPy/docs/examples/input_files` or `insarlab/MintPy-tutorial/docs`.

**Comment by dbekaert** [comment]
Actually @hfattahi included all in the notebook, so can be reconstructed. Will close this
