### ISSUE TITLE
data type for connected components dataset

### ISSUE THREAD

**Issue by hfattahi** [insarlab/MintPy#148]
1) MintPy currently enforces np.byte datatype for connected components dataset. This means only values between -128 to 127 can be stored.
2) ISCE2 snaphu wrapper, outputs maximum 20 connected component and zeros out other components by default (can be controlled). But the largest can be up to 255 in Snaphu as the data type is unsigned byte (needs to be verified). Therefore np.byte in MintPy is fine for ISCE regular outputs.
3) arai tools stitches different unwrapped interferograms and relabels the connected components. So it is possible to have large number of connected components over large areas.
4) Other unwrappers (currently outside ISCE2) allow for much larger number of connected components

With all this I'm wondering if we should change the data type of connected components in MintPy hdf5 dataset to float?

**Comment by hfattahi** [comment]
@dbekaert @ehavazli What is the largest number of connected components that you guys may expect?

**Comment by dbekaert** [comment]
20 per product. So 20*n products people stitch.
I know of people stitching 8-9 products, so like 180  connected components or so.

**Comment by yunjunz** [comment]
the `connectComponent` object in mintpy is calling [skimage.measure.label()](https://scikit-image.org/docs/stable/api/skimage.measure.html#skimage.measure.label) to extract all regions/areas related properties, and this `label` function supports integer array as input only, thus, we could change the data type from `byte` to [`int16`](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.types.html), which supports up to 32767. How about that?

**Comment by hfattahi** [comment]
That is more than enough. The only implication is that we will increase the size on disk, by moving from np.byte to anything else. If increasing size is not a big concern for users then I think we should move to int16 .

**Comment by yunjunz** [comment]
Since the value of this dataset is usually small, compression should reduce the size a lot. We could turn ON the compression for this dataset always.

**Comment by hfattahi** [comment]
Yes I agree. So let's move to int16 then.
