### ISSUE TITLE
azimuthAngle from ariaTSsetup.py

### ISSUE THREAD

**Issue by yunjunz** [insarlab/MintPy#162]
The azimuthAngle from the current ariaTSsetup.py, for SanFran Sen descending track, has an average value of -8.8; while the average value from ISCE/topsStack (band2 of los.rdr), for Galapagos Sen descending track, has an average value of -102. They are very different! https://github.com/insarlab/MintPy/pull/139#discussion_r307045154

Below is the description from isce/topsStack `merged/geom_master/los.rdr.xml`:
> Two channel Line-Of-Sight geometry image (all angles in degrees). 
Represents vector drawn from target to platform. 
Channel 1: Incidence angle measured from vertical at target (always +ve).
Channel 2: Azimuth angle measured from North in Anti-clockwise direction.

@ehavazli and @dbekaert, what is the corresponding definition of the azimuthAngle from ARIA-tools? The current value looks unreasonable to me, in the topsStack's version of definition. And this will cause problem while applying enu2los convertion or the other way around.

**Comment by ehavazli** [comment]
@yunjunz, please disregard the azimuth angle value given in metadata of stack VRT files. The calculation of that value is not correct and wasn't meant to be used. Please use the extracted azimuth angle file. I will remove the metadata until the correct calculation is implemented.

**Comment by yunjunz** [comment]
Hi @ehavazli, the -8.8 is from the azimuthAngle file. The one read from the vrt metadata is already commented out.

**Comment by ehavazli** [comment]
that file is directly extracted from from the ARIA product. I believe @dbekaert  is the right person to give the details.

**Comment by dbekaert** [comment]
The convention we used for GUNW should be the same as the stacks/topsApp.
Adding @piyushrpt to confirm.

I just had a quick look at one of the original GUNW products and confirm @yunjunz for the value of Descending to be -10 range.

```
gdalinfo NETCDF:"S1-GUNW-D-R-087-tops-20171212_20171130-161514-21975N_19970N-PP-b926-v2_0_1.nc":/science/grids/imagingGeometry/azimuthAngle -stats
STATISTICS_MEAN=-11.594106027708
```

Will need to look into the meta-data cube code generation and compare with tops, to see what is happenning.
https://github.com/aria-jpl/ariamh/blob/develop/interferogram/sentinel/makeGeocube.py

**Comment by dbekaert** [comment]
@yunjunz the sign convention for ARIA products is as follows (will have it added to the aria main website as well): *The azimuth angle is defined as the counterclockwise angle between the East and the look direction from the ground target to the sensor.*

So this means for right looking systems: desc ~-9 and asc ~-168 degrees, both off by 90 degrees  from your definition. I suggest we handle this at the prep_aria.py script such we maintain the consistent definition within the aria-tools and the aria product as outlined on the website.

**Comment by yunjunz** [comment]
Thank you @dbekaert for the clarification. I will adjust prep_aria.py accordingly.

**Comment by yunjunz** [comment]
@dbekaert should it be between the **West** and the LOS vector?

**Comment by dbekaert** [comment]
Here is a schematic:

![Screen Shot 2019-08-01 at 1 35 19 PM](https://user-images.githubusercontent.com/19240905/62325778-49882f80-b461-11e9-965e-64d1141f964a.png)

**Comment by yunjunz** [comment]
Now everything make sense! ISCE/topsStack azimuthAngle represents the vector `from sensor to target`, measured from the `north` in the counterclockwise direction, AIRA azimuthAngle represents the vector `from target to sensor` measured from the `east` in the counterclockwise direction.

For ISCE, ascending track has a typical value of -258, descending track of -99.
For ARIA, ascending track has a typical value of -168, descending track of -9.

azAngleISCE = azAngleARIA - 90.

**Comment by dbekaert** [comment]
Sounds good, we would just need to check the code when we swap to left looking to see all remains as you expect.

**Comment by yunjunz** [comment]
Yeah, it will be good to re-check it for left-looking when there is dataset to confirm.
