### ISSUE TITLE
Confusing, non-fatal `basemap` installation errors under linux

### ISSUE THREAD

**Issue by falkamelung** [insarlab/MintPy#164]
I am getting the building errors below when installing MintPy as described in installallation.md. It looks very scary as the errors show up red (not  reproduced here) but  they are not fatal.  It says `failed to install basemap` and a bit later `Successfully installed basemap-1.2.0`. Very confusing!   Can't we go back to `conda install basemap` which did not throw any errors  (I forgot why this had to be changed). If not we should add a note that these errors are nothing to worry about.

 Here what I did. I install as :
```
./Miniconda3-4.5.12-Linux-x86_64.sh -b -p ./miniconda3
./miniconda3/bin/conda install --yes --file MintPy/docs/conda.txt 
./miniconda3/bin/pip install git+https://github.com/matplotlib/basemap.git#egg=mpl_toolkits
./miniconda3/bin/pip install git+https://github.com/tylere/pykml.git
```
I am getting the following errors, but at the end it says 'Sucessfully':
```
[famelung@pegasus test_mintpy]$ ./miniconda3/bin/pip install git+https://github.com/matplotlib/basemap.git#egg=mpl_toolkits
Collecting mpl_toolkits from git+https://github.com/matplotlib/basemap.git#egg=mpl_toolkits
  Cloning https://github.com/matplotlib/basemap.git to /tmp/pip-install-ag112_58/mpl-toolkits
  Running command git clone -q https://github.com/matplotlib/basemap.git /tmp/pip-install-ag112_58/mpl-toolkits
  WARNING: Generating metadata for package mpl-toolkits produced metadata for project name basemap. Fix your #egg=mpl-toolkits fragments.
Requirement already satisfied: matplotlib!=3.0.1,>=1.0.0 in ./miniconda3/lib/python3.7/site-packages (from basemap) (3.1.1)
Requirement already satisfied: numpy>=1.2.1 in ./miniconda3/lib/python3.7/site-packages (from basemap) (1.16.4)
Requirement already satisfied: pyproj>=1.9.3 in ./miniconda3/lib/python3.7/site-packages (from basemap) (2.2.1)
Collecting pyshp>=1.2.0 (from basemap)
Requirement already satisfied: six in ./miniconda3/lib/python3.7/site-packages (from basemap) (1.12.0)
Requirement already satisfied: python-dateutil>=2.1 in ./miniconda3/lib/python3.7/site-packages (from matplotlib!=3.0.1,>=1.0.0->basemap) (2.8.0)
Requirement already satisfied: kiwisolver>=1.0.1 in ./miniconda3/lib/python3.7/site-packages (from matplotlib!=3.0.1,>=1.0.0->basemap) (1.1.0)
Requirement already satisfied: cycler>=0.10 in ./miniconda3/lib/python3.7/site-packages (from matplotlib!=3.0.1,>=1.0.0->basemap) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in ./miniconda3/lib/python3.7/site-packages (from matplotlib!=3.0.1,>=1.0.0->basemap) (2.4.2)
Requirement already satisfied: setuptools in ./miniconda3/lib/python3.7/site-packages (from kiwisolver>=1.0.1->matplotlib!=3.0.1,>=1.0.0->basemap) (41.0.1)
Building wheels for collected packages: basemap, basemap
  Building wheel for basemap (setup.py) ... done
  Created wheel for basemap: filename=basemap-1.2.0-cp37-cp37m-linux_x86_64.whl size=121736686 sha256=0571727c5a5c82c48570b5d2a99941bee4444e929033d3b54a2e911b048e487e
  Stored in directory: /tmp/pip-ephem-wheel-cache-uhzgp5tw/wheels/3f/f3/56/de548b66967d0d661612b7618022e2c0d4b86b9a638cf6ccf3
  Building wheel for basemap (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /nethome/famelung/test_mintpy/miniconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ag112_58/basemap/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ag112_58/basemap/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-niw69w9i --python-tag cp37
       cwd: /tmp/pip-install-ag112_58/basemap/
  Complete output (5 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/nethome/famelung/test_mintpy/miniconda3/lib/python3.7/tokenize.py", line 447, in open
      buffer = _builtin_open(filename, 'rb')
  FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-ag112_58/basemap/setup.py'
  ----------------------------------------
  ERROR: Failed building wheel for basemap
  Running setup.py clean for basemap
  ERROR: Command errored out with exit status 1:
   command: /nethome/famelung/test_mintpy/miniconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ag112_58/basemap/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ag112_58/basemap/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
       cwd: /tmp/pip-install-ag112_58/basemap
  Complete output (5 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/nethome/famelung/test_mintpy/miniconda3/lib/python3.7/tokenize.py", line 447, in open
      buffer = _builtin_open(filename, 'rb')
  FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-ag112_58/basemap/setup.py'
  ----------------------------------------
  ERROR: Failed cleaning build dir for basemap
Successfully built basemap
Failed to build basemap
Installing collected packages: pyshp, basemap
Successfully installed basemap-1.2.0 pyshp-2.1.0
[famelung@pegasus test_mintpy]$
```
And basemap is indeed there:
```
 ./miniconda3/bin/pip freeze | grep basemap
basemap==1.2.0
```

**Comment by yunjunz** [comment]
the current basemap instruction is supposed to be a temporary solution, we should not spend time to make it perfect. The related installation will be much easier once basemap had a new (conda/macports) release.

If your old installation works, there is no reason to update your installation right now. All mintpy's recent new feature does not require new python dependencies.

**Comment by rzinke** [comment]
Hello. Did this issue get fixed? I am reinstalling MintPy following the instructions on the homepage. I set up a python environment called MintPy and installed the conda packages listed in the /MintPy/docs/conda.txt file.

But when I try installing basemap, get an error message: 
(MintPy) [rzinke@sar ~]$ pip install https://github.com/matplotlib/basemap/archive/v1.2.1rel.tar.gz
Collecting https://github.com/matplotlib/basemap/archive/v1.2.1rel.tar.gz
  Downloading https://github.com/matplotlib/basemap/archive/v1.2.1rel.tar.gz (132.5MB)
     |████████████████████████████████| 132.5MB 153.8MB/s 
    ERROR: Command errored out with exit status 1:
     command: /u/sar-r0/rzinke/python/miniconda3/envs/MintPy/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-wykj70gd/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-wykj70gd/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-req-build-wykj70gd/pip-egg-info
         cwd: /tmp/pip-req-build-wykj70gd/
    Complete output (18 lines):
    checking for GEOS lib in /home/rzinke ....
    checking for GEOS lib in /home/rzinke/local ....
    checking for GEOS lib in /usr ....
    checking for GEOS lib in /usr/local ....
    checking for GEOS lib in /sw ....
    checking for GEOS lib in /opt ....
    checking for GEOS lib in /opt/local ....
    
    Can't find geos library in standard locations ('/home/rzinke', '/home/rzinke/local', '/usr', '/usr/local', '/sw', '/opt', '/opt/local').
    Please install the corresponding packages using your
    systems software management system (e.g. for Debian Linux do:
    'apt-get install libgeos-3.3.3 libgeos-c1 libgeos-dev' and/or
    set the environment variable GEOS_DIR to point to the location
    where geos is installed (for example, if geos_c.h
    is in /usr/local/include, and libgeos_c is in /usr/local/lib,
    set GEOS_DIR to /usr/local), or edit the setup.py script
    manually and set the variable GEOS_dir (right after the line
    that says "set GEOS_dir manually here".
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

Have you encountered this message before and is there a simple solution?

**Comment by ehavazli** [comment]
Hey @rzinke, 

I think your problem may be related to GDAL. Please try
```
conda list | grep geos
```
and
```
conda list | grep gdal
```
in your mintpy environment and check if geos is installed as part of conda and which version of GDAL is installed (it is 2.4.1 for me).

If not go ahead and install geos which I believe comes with gdal:
```
conda install geos
```

**Comment by rzinke** [comment]
Thanks @ehavazli. I now tried
$ conda list | grep geos >  geos 3.8.0   he1b5a44_0   conda-forge 
and 
$ conda list | grep gdal > [returns nothing]

I installed gdal, and geos using conda (in the MintPy environment), so now geos is version 3.8.0; gdal is version 3.0.2. However, when I try 
pip install https://github.com/matplotlib/basemap/archive/v1.2.1rel.tar.gz
I get the same error message as above.

**Comment by yunjunz** [comment]
Hi @rzinke, could you double-check the `pip` command you used is from the MintPy conda environment using `which pip`? Mine is as below for example.

```
/Users/yunjunz/development/python/miniconda3/envs/MintPy/bin/pip
```

If it's the case and it still does not work, try to install the development version of basemap.

```
$PYTHON3DIR/bin/pip install git+https://github.com/matplotlib/basemap.git
```

**Comment by rzinke** [comment]
Hi @yunjunz, here is the result
(MintPy) [rzinke@sar ~]$ which pip
/u/sar-r0/rzinke/python/miniconda3/envs/MintPy/bin/pip

I get the same error as before with 
(MintPy) [rzinke@sar ~]$ pip install git+https://github.com/matplotlib/basemap.git

Collecting git+https://github.com/matplotlib/basemap.git
  Cloning https://github.com/matplotlib/basemap.git to /tmp/pip-req-build-jv600l6e
  Running command git clone -q https://github.com/matplotlib/basemap.git /tmp/pip-req-build-jv600l6e
    ERROR: Command errored out with exit status 1:
     command: /u/sar-r0/rzinke/python/miniconda3/envs/MintPy/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-jv600l6e/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-jv600l6e/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-req-build-jv600l6e/pip-egg-info
         cwd: /tmp/pip-req-build-jv600l6e/
    Complete output (18 lines):
    checking for GEOS lib in /home/rzinke ....
    checking for GEOS lib in /home/rzinke/local ....
    checking for GEOS lib in /usr ....
    checking for GEOS lib in /usr/local ....
    checking for GEOS lib in /sw ....
    checking for GEOS lib in /opt ....
    checking for GEOS lib in /opt/local ....
    
    Can't find geos library in standard locations ('/home/rzinke', '/home/rzinke/local', '/usr', '/usr/local', '/sw', '/opt', '/opt/local').
    Please install the corresponding packages using your
    systems software management system (e.g. for Debian Linux do:
    'apt-get install libgeos-3.3.3 libgeos-c1 libgeos-dev' and/or
    set the environment variable GEOS_DIR to point to the location
    where geos is installed (for example, if geos_c.h
    is in /usr/local/include, and libgeos_c is in /usr/local/lib,
    set GEOS_DIR to /usr/local), or edit the setup.py script
    manually and set the variable GEOS_dir (right after the line
    that says "set GEOS_dir manually here".
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by rzinke** [comment]
Hi, was anyone able to find a solution or workaround for this? I deleted my old mintpy conda environment and created a new one, following exactly the steps on the [Installation page](https://github.com/insarlab/MintPy/blob/master/docs/installation.md#2-install-dependencies). The installation failed with the same error as before: 
Downloading and Extracting Packages
python-3.7.6         | 52.9 MB   | ############################################################################### | 100% 
cvxopt-1.2.3         | 536 KB    | ############################################################################### | 100% 
setuptools-44.0.0    | 659 KB    | ############################################################################### | 100% 
pyresample-1.14.0    | 700 KB    | ############################################################################### | 100% 
pillow-7.0.0         | 643 KB    | ############################################################################### | 100% 
pyyaml-5.3           | 184 KB    | ############################################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Ran pip subprocess with arguments:
['/u/sar-r0/rzinke/python/miniconda3/envs/mintpy/bin/python', '-m', 'pip', 'install', '-U', '-r', '/u/sarh0/rzinke/tools/MintPy/docs/condaenv.u793u5b4.requirements.txt']
Pip subprocess output:
Collecting git+https://github.com/tylere/pykml.git (from -r /u/sarh0/rzinke/tools/MintPy/docs/condaenv.u793u5b4.requirements.txt (line 1))
  Cloning https://github.com/tylere/pykml.git to /tmp/pip-req-build-rlisewme
Collecting https://github.com/matplotlib/basemap/archive/v1.2.1rel.tar.gz (from -r /u/sarh0/rzinke/tools/MintPy/docs/condaenv.u793u5b4.requirements.txt (line 2))
  Downloading https://github.com/matplotlib/basemap/archive/v1.2.1rel.tar.gz

Pip subprocess error:
  Running command git clone -q https://github.com/tylere/pykml.git /tmp/pip-req-build-rlisewme
    ERROR: Command errored out with exit status 1:
     command: /u/sar-r0/rzinke/python/miniconda3/envs/mintpy/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-24nz4hze/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-24nz4hze/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-req-build-24nz4hze/pip-egg-info
         cwd: /tmp/pip-req-build-24nz4hze/
    Complete output (18 lines):
    checking for GEOS lib in /home/rzinke ....
    checking for GEOS lib in /home/rzinke/local ....
    checking for GEOS lib in /usr ....
    checking for GEOS lib in /usr/local ....
    checking for GEOS lib in /sw ....
    checking for GEOS lib in /opt ....
    checking for GEOS lib in /opt/local ....
    
    Can't find geos library in standard locations ('/home/rzinke', '/home/rzinke/local', '/usr', '/usr/local', '/sw', '/opt', '/opt/local').
    Please install the corresponding packages using your
    systems software management system (e.g. for Debian Linux do:
    'apt-get install libgeos-3.3.3 libgeos-c1 libgeos-dev' and/or
    set the environment variable GEOS_DIR to point to the location
    where geos is installed (for example, if geos_c.h
    is in /usr/local/include, and libgeos_c is in /usr/local/lib,
    set GEOS_DIR to /usr/local), or edit the setup.py script
    manually and set the variable GEOS_dir (right after the line
    that says "set GEOS_dir manually here".
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.


CondaEnvException: Pip failed

I will try to find my geos directory and set it manually.

**Comment by yunjunz** [comment]
Hi @rzinke, I spent some time and have not been able to figure out the cause. I would suggest the same: trying to set it manually.

**Comment by rzinke** [comment]
Solved! 
I deleted the old conda environment and created a new one using the command on the MintPy Installation page: 
$ conda env create -f /u/sarh0/rzinke/tools/MintPy/docs/conda_env.yml
This time, however, I first modified the conda_env.yml file to include geos and basemap as conda packages. My version of the conda_env.yml file looks like this:

# create environment : conda env create -f conda_env.yml
# update dependencies: conda env update -f conda_env.yml
# remove environment : conda env remove -n mintpy
# enter  environment : conda activate mintpy
# exit   environment : conda deactivate
name: MintPy
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.6
  - cdsapi
  - cvxopt
  - dask>=1.0,<2.0
  - dask-jobqueue>=0.3,<1.0
  - ecCodes
  - h5py
  - lxml
  - matplotlib
  - netcdf4
  - numpy
  - openmp
  - pip
  - pygrib
  - pyhdf
  - pykdtree
  - pyproj
  - pyresample
  - scikit-image
  - scipy
  - geos
  - basemap
  - pip:
    - git+https://github.com/tylere/pykml.git

**Comment by yunjunz** [comment]
That's great @rzinke!

Could you confirm whether `basemap` works properly by runing `view.py -h`?

**Comment by yunjunz** [comment]
Great! Could you issue a pull request for your changes? Thank you!

**Comment by yunjunz** [comment]
Hi @falkamelung, could you test if Rob's solution - adding `basemap` to conda.txt (conda installed geos for basemap from my testing on Mojave and Catalina) - works for you on Linux when you got a chance? It seems like `conda install basemap` works now.
