### ISSUE TITLE
Problem loading ISCE topsStack output with inconsistent size

### ISSUE THREAD

**Issue by EJFielding** [insarlab/MintPy#192]
**Description of the problem**

Load data failed from Sentinel-1 data processed with topsStack processor.

smallbaselineApp.py RidgecrestSenA064.txt --dostep load_data

This is my config file:
```
# vim: set filetype=cfg:
##----------------------------- SentinelStack/ISCE ---------------------##
cleanopt                        = 1    # [ 0 / 1 / 2 / 3 4]   0: no cleaning, 1: largest files, 2: merged/etc, PROCESS dirs, 3: SLC,RAW, 4: everything
ssaraopt                        = --platform=SENTINEL-1A,SENTINEL-1B -r 128 -f 587,588,589,590,591,592,593  -e 2018-07-01
processor                       = isce
sentinelStack.demDir            = /nethome/famelung/Sentinel/GalapagosT128SenVVD/DEM
sentinelStack.boundingBox       = '-1 0.15 -91.6 -90.9'
sentinelStack.subswath          = 1 2  # comment 
sentinelStack.numConnections    = 5   # comment
sentinelStack.azimuthLooks      = 5   # comment
sentinelStack.rangeLooks        = 15  # comment
sentinelStack.filtStrength      = 0.2  # comment
sentinelStack.unwMethod         = snaphu  # comment
sentinelStack.coregistration    = auto  # comment



##-------------------------------- MintPy -----------------------------##
mintpy.load.processor        = isce
##---------for ISCE only:
mintpy.load.metaFile         = ../master/IW*.xml
mintpy.load.baselineDir      = ../baselines
##---------interferogram datasets:
mintpy.load.unwFile          = ../merged/interferograms/*/filt_*.unw
mintpy.load.corFile          = ../merged/interferograms/*/filt_*.cor
mintpy.load.connCompFile     = ../merged/interferograms/*/filt_*.unw.conncomp
##---------geometry datasets:
mintpy.load.demFile          = ../merged/geom_master/hgt.rdr
mintpy.load.lookupYFile      = ../merged/geom_master/lat.rdr
mintpy.load.lookupXFile      = ../merged/geom_master/lon.rdr
mintpy.load.incAngleFile     = ../merged/geom_master/los.rdr
mintpy.load.azAngleFile      = ../merged/geom_master/los.rdr
mintpy.load.shadowMaskFile   = ../merged/geom_master/shadowMask.rdr
mintpy.load.waterMaskFile    = ../merged/geom_master/waterMask.rdr
mintpy.load.bperpFile        = ../merged/baseline_grid/*/bperp.rdr

#mintpy.subset.yx                         = 400:2400,0:1700
#mintpy.reference.lalo                    = -0.31,-91.22
mintpy.network.endDate                   = 20190704
mintpy.unwrapError.method                = phase_closure   #[bridging / phase_closure / no], auto for no
#mintpy.topographicResidual.stepFuncDate  = 20150524,20150616,20170321,20170910,20180613  #Wolf,Wolf,CerroAzul,Fernandina,Fernandina
#mintpy.deramp                            = linear

```

**Full error message**

```
searching interferometric pairs info
input data files:
unwrapPhase     : ../merged/interferograms/*/filt_*.unw
coherence       : ../merged/interferograms/*/filt_*.cor
connectComponent: ../merged/interferograms/*/filt_*.unw.conncomp
number of unwrapPhase     : 255
number of coherence       : 255
number of connectComponent: 255
--------------------------------------------------
searching geometry files info
input data files:
height          : ../merged/geom_master/hgt.rdr
latitude        : ../merged/geom_master/lat.rdr
longitude       : ../merged/geom_master/lon.rdr
incidenceAngle  : ../merged/geom_master/los.rdr
azimuthAngle    : ../merged/geom_master/los.rdr
shadowMask      : ../merged/geom_master/shadowMask.rdr
--------------------------------------------------
updateMode : True
compression: None
--------------------------------------------------
create HDF5 file /net/kraken/nobak/fielding/Ridgecrest/S1AB/A064/stack2/MintPy_v1/inputs/ifgramStack.h5 with w mode
create dataset /unwrapPhase      of <class 'numpy.float32'>   in size of (255, 3988, 9791) with compression = None
[=======>                15%                       ] 20151017_20151029   29s /   167sTraceback (most recent call last):
  File "/home/fielding/python/MintPy/mintpy/smallbaselineApp.py", line 1077, in <module>
    main()
  File "/home/fielding/python/MintPy/mintpy/smallbaselineApp.py", line 1067, in main
    app.run(steps=inps.runSteps, plot=inps.plot)
  File "/home/fielding/python/MintPy/mintpy/smallbaselineApp.py", line 996, in run
    self.run_load_data(sname)
  File "/home/fielding/python/MintPy/mintpy/smallbaselineApp.py", line 364, in run_load_data
    mintpy.load_data.main(scp_args.split())
  File "/home/fielding/python/MintPy/mintpy/load_data.py", line 589, in main
    extra_metadata=extraDict)
  File "/home/fielding/python/MintPy/mintpy/objects/stackDict.py", line 153, in write2hdf5
    ds[i, :, :] = data
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/fielding/anaconda3/envs/mintpy/lib/python3.7/site-packages/h5py/_hl/dataset.py", line 707, in __setitem__
    for fspace in selection.broadcast(mshape):
  File "/home/fielding/anaconda3/envs/mintpy/lib/python3.7/site-packages/h5py/_hl/selections.py", line 299, in broadcast
    raise TypeError("Can't broadcast %s -> %s" % (target_shape, self.mshape))
TypeError: Can't broadcast (3988, 6945) -> (3988, 9791)
```

**System information**

* Operating system: Linux
* Version of Python and relevant dependencies if applicable: Python 3.7 from Anaconda
* Version of MintPy (output of `smallbaselineApp.py -v`):

**Comment by hfattahi** [comment]
Hi Eric, Can you check if all your interferograms have the same size? Looks like there is at least one interferogran with a shape of (3988, 6945) which is different from (3988, 9791) which is probably what most of your interferogram has.

**Comment by EJFielding** [comment]
Hi Heresh, Thanks for the suggestion. I went to my `merged/interferograms` directory and ran `grep WIDTH */filt_fine.unw.rsc`.  I can see now that 48 out of my 255 interferograms have a width of 6945. This must be a processing problem in the version of sentinelStack that I am using.

It would be better if there was a more helpful error message from MintPy. It seems like it could do a quick check that all the input images are the same size.

**Comment by yunjunz** [comment]
Hi @EJFielding, thanks for the update. I agree that MintPy should i) skip those interferograms with inconsistent size and load the rest ii) print out more informative warning message for it.

**Comment by EJFielding** [comment]
Yes, that would be a bit improvement for MintPy to ignore the bad interferograms.

I looked at one of the interferograms and I see that one of the two dates has only 3 bursts in IW3. That means that the problem was in the original data, not the processing. 

Is there any way to manually provide a list of interferograms to exclude from the data load?

**Comment by yunjunz** [comment]
Hi @EJFielding, I just committed the skip functionality, could you update the code and try again when you got a chance?

**Comment by EJFielding** [comment]
Thanks! It is loading now and printed out a list of interferograms that were skipped. I can see that I still have 207 interferograms left.

**Comment by EJFielding** [comment]
I ran the `network_modification` step, and now I can see that the skipped interferograms have broken the network into two segments. It would be nice if the `load_data` step told me that my network was not connected. Note that I also set the end date to July 4, 2019 to avoid mixing coseismic deformation with preseismic deformation in the time series.
![Network](https://user-images.githubusercontent.com/7253576/63656142-76202600-c745-11e9-8917-5b2bf885cfd4.png)

**Comment by yunjunz** [comment]
Hi @EJFielding, for the not fully connected network, a warning or error message (depending on the chosen weight function) will be generated during the `invert_network` step before running the inversion.

https://github.com/insarlab/MintPy/blob/master/mintpy/ifgram_inversion.py#L687

A easy solution to get a fully connected network in your case would be to select more sequential connections to form interferograms with acquisitions before and after the problematic image while re-running `topsStack`. 

From my limited experience, mixing pre-, co- and post-seimic/eruptive deformation time-series is fine except when the co-seismic/eruptive deformation exceeds the InSAR deformation detection limit, such as the 2018 Sierra Negra eruption. Mixing works for the Wells earthquake example below. I would recommend you to try to see if mixing is suitable for your case as well.

https://github.com/insarlab/MintPy/blob/master/docs/example_dataset.md#envisat-of-the-2008-wells-earthquake-with-gamma

**Comment by EJFielding** [comment]
The coseismic interferograms are not unwrapped correctly in this case.

Sent from my iPhone
      ++Eric

On Aug 25, 2019, at 14:59, Zhang Yunjun <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @EJFielding<https://github.com/EJFielding>, for the not fully connected network, a warning or error message (depending on the chosen weight function) will be generated during the invert_network step before running the inversion.

https://github.com/insarlab/MintPy/blob/master/mintpy/ifgram_inversion.py#L687

A easy solution to get a fully connected network in your case would be to select more sequential connections to form interferograms with acquisitions before and after the problematic image while re-running topsStack.

From my limited experience, mixing pre-, co- and post-seimic/eruptive deformation time-series is fine except when the co-seismic/eruptive deformation exceeds the InSAR deformation detection limit, such as the 2018 Sierra Negra eruption. Mixing works for the Wells earthquake example below. I would recommend you to try to see if mixing is suitable for your case as well.

https://github.com/insarlab/MintPy/blob/master/docs/example_dataset.md#envisat-of-the-2008-wells-earthquake-with-gamma

**Comment by yunjunz** [comment]
Thanks for the clarification.
