### ISSUE TITLE
Scene average coherence includes areas of nodata from ISCE topsStack output

### ISSUE THREAD

**Issue by EJFielding** [insarlab/MintPy#195]
**Description of the problem**
My ISCE topsStack output includes some scenes with limited coverage of the area due to partial acquisitions. It seems that the scene average coherence of pairs that include those scenes is calculated using at least some of the area with no data. Here are the coherence plots:

![coherence_1](https://user-images.githubusercontent.com/7253576/63658988-9f4faf00-c763-11e9-8afb-942fb5999963.png)

![coherence_2](https://user-images.githubusercontent.com/7253576/63658999-b098bb80-c763-11e9-9979-40b176b7e0ec.png)

**Full script that generated the error**
Ran the regular input_data step and then `plot_smallbaselineApp.sh`.

**Full error message**

Here is the coherence plot:
![CoherenceMatrix](https://user-images.githubusercontent.com/7253576/63659154-9a3f2f80-c764-11e9-9564-2cb32318e1de.png)

**System information**

* Operating system: Linux
* Version of Python and relevant dependencies if applicable: Python 3.7
* Version of MintPy (output of `smallbaselineApp.py -v`): MintPy release version v1.2beta-18, release date 2019-08-24

**Comment by yunjunz** [comment]
Hi @EJFielding, the fix above will now ignore the ZERO value of the coherence dataset while plotting the average spatial coherence.

Note that affects the plotting only and won't change the `invert_network` step, where for the pixel-wised unwrapPhase, the ZERO, NaN value is ignored; and for the pixel-wised spatial coherence (used in weighted inversion only), the ZERO, NaN value is set to a very small value (0.01 by default).

**Comment by yunjunz** [comment]
Thank you for pointing it out @EJFielding!
