### ISSUE TITLE
Mask of Connected Components not updated after modify_network

### ISSUE THREAD

**Issue by EJFielding** [insarlab/MintPy#197]
**Description of the problem**

The `maskConnComp.h5` file is not updated when interferograms are dropped by the `modify_network` step with new parameters.

**Full script that generated the error**

Ran `modify_network` with new `mintpy.network.startDate` to removed interferograms with partial coverage. The mask file remained the same.

Here is the view of `maskConnComp.h5` after modification:
![maskConnComp](https://user-images.githubusercontent.com/7253576/63661429-61f11e80-c76f-11e9-8e48-f9d3b7306cdf.png)

Note only narrow line of `1` values where partial scenes (now removed) overlap.

**System information**

* Operating system: Linux
* Version of Python and relevant dependencies if applicable
* Version of MintPy (output of `smallbaselineApp.py -v`): MintPy release version v1.2beta-18, release date 2019-08-24

**Comment by yunjunz** [comment]
It's fixed now, thank you for pointing it out.

**Comment by EJFielding** [comment]
Thanks for the fast update!!

I pulled the new version and run the `modify_network` step again. It looks like it was going to update the mask, but then decided to skip it. 
```
generate_mask.py /net/kraken/nobak/fielding/Ridgecrest/S1AB/A064/stack2/MintPy_v1/inputs/ifgramStack.h5 --nonzero -o maskConnComp.h5 --update
input ifgramStack file: /net/kraken/nobak/fielding/Ridgecrest/S1AB/A064/stack2/MintPy_v1/inputs/ifgramStack.h5
--------------------------------------------------
update mode: ON
1) output file maskConnComp.h5 already exists.
2) output file is newer than input dataset: connectComponent.
run or skip: skip.
```
I will remove the mask file and try again.
