### ISSUE TITLE
save_gmt.py is confused about input parameters

### ISSUE THREAD

**Issue by EJFielding** [insarlab/MintPy#205]
**Description of the problem**

The `save_gmt.py` script is having trouble with its input parameter parsing.

**Full script that generated the error**

```
save_gmt.py geo_velocity.h5 -o geo_velocity.grd
```
or `save_gmt.py -h`.

**Full error message**

```
Using default MintPy Path: /home/fielding/tools/MintPy
usage: save_gmt.py [-h] [-o OUTFILE] file [dset]
save_gmt.py: error: unrecognized arguments: o m e / f i e l d i n g / t o o l s / M i n t P y / m i n t p y / s a v e _ g m t . p y
```

**System information**

* Operating system:MacOS
* Version of Python and relevant dependencies if applicable: 3.7
* Version of MintPy (output of `smallbaselineApp.py -v`): MintPy release version v1.2beta-27, release date 2019-09-02

**Comment by yunjunz** [comment]
Thank you @EJFielding, it's fixed now.

**Comment by EJFielding** [comment]
Thanks again for the quick fix!

I hope that Hurrican Dorian is not going to affect Miami much.

**Comment by yunjunz** [comment]
Thanks for your kind wish Eric. We had big rain today, hope it won't get much worse tomorrow.
