### ISSUE TITLE
Memory Error for very large dataset

### ISSUE THREAD

**Issue by rzinke** [insarlab/MintPy#216]
Hello, 

I am processing a large data set: A ~15 degrees latitude swath consisting of > 1000 interferograms for something like 100 dates. When I run smallbaselineApp, an avgPhaseVelocity map is produced, but the inversion step fails with "MemoryError". I briefly raised this issue in the past, and I know Heresh had started working on a block-by-block processing feature to break the data into smaller chunks. Was the block-by-block method finished and fully implemented for the rest of the process?

I have been using the MintPy version with block-by-block processing enabled (committed 13 Aug 2019), and it produces the file timeseries.h5. However, when I try tsview.py timeseries.h5 I get a similar "MemoryError" message.

Is a workaround still in the works? Or do I need to process my data in smaller chunks?

Thanks,
Robert

**Comment by yunjunz** [comment]
Hi Robert, the block-by-block version is still in the development, we won't release it anytime soon. I would recommend you to process your data in a smaller size.

**Comment by rzinke** [comment]
Hi @yunjunz, thanks for letting me know!

**Comment by rzinke** [comment]
Hello, 
I was curious if there was a way to downsample or multilook ifg data when they are prepared for MintPy. That is, rather than slice a data set into smaller pieces, would it be possible to instead increase the pixel size of the data? I did not see this option available in the tutorials.

**Comment by yunjunz** [comment]
Hi @rzinke, you could use `multilook.py` for the `geometryGeo.h5` and `ifgramStack.h5` file after data loading.

This is not part of the routine workflow, so don't forget to replace the filename to continue to use `smallbaselineApp.py`.

**Comment by rzinke** [comment]
Thanks! I am getting an error:
(MintPy) [rzinke@sar Parkfield_ds]$ multilook.py inputs/ifgramStack.h5 -o inputs/ifgramStack_ml3.h5 -r 3 -a 3
multilooking isce ifgramStack file: inputs/ifgramStack.h5
number of looks in y / azimuth direction: 3
number of looks in x / range   direction: 3
multilooking coherence        from ifgramStack.h5 ...
multilooking connectComponent from ifgramStack.h5 ...
multilooking unwrapPhase      from ifgramStack.h5 ...
update LENGTH, WIDTH, YMIN, YMAX, XMIN, XMAX
update Y/X_STEP
Traceback (most recent call last):
  File "/u/sarh0/rzinke/tools/MintPy/mintpy/multilook.py", line 209, in <module>
    main()
  File "/u/sarh0/rzinke/tools/MintPy/mintpy/multilook.py", line 201, in main
    multilook_file(infile, lks_y=inps.lks_y, lks_x=inps.lks_x, outfile=inps.outfile)
  File "/u/sarh0/rzinke/tools/MintPy/mintpy/multilook.py", line 191, in multilook_file
    atr = multilook_attribute(atr, lks_y, lks_x)
  File "/u/sarh0/rzinke/tools/MintPy/mintpy/multilook.py", line 134, in multilook_attribute
    atr['AZIMUTH_PIXEL_SIZE'] = str(lks_y * float(atr['AZIMUTH_PIXEL_SIZE']))
KeyError: 'AZIMUTH_PIXEL_SIZE'

Is there a workaround for this?


Also, are the instructions in the help menu reversed? 
From multilook.py -h: 
 -r LKS_X, --range LKS_X, -x LKS_X
                        number of multilooking in azimuth/y direction
  -a LKS_Y, --azimuth LKS_Y, -y LKS_Y
                        number of multilooking in range  /x direction

Thank you

**Comment by rzinke** [comment]
I am using ARIA data by the way.

**Comment by yunjunz** [comment]
Hi @rzinke, the AZIMUTH_PIXEL_SIZE is now optional while running multilook.py. I have fixed the typo. Thank you for pointing them out @rzinke!

**Comment by rzinke** [comment]
Hi @yunjunz, the results of the multilooked timeseries look great. Thanks the help!

**Comment by rzinke** [comment]
Hello. I am not sure if this is directly related or not, but I am receiving an error when trying to process a multilooked data set. Specifically, I processed the interferograms using ARIA and ARIA-tools, then prepared them for MintPy using prep_aria. I then applied the multilook function to the geometryGeo.h5 and ifgramStack.h5 files, making sure to replace the multilooked versions with the standard file names, as described above. After completing steps load_data, modify_network, reference_point, and most of the correct_unwrap_error steps, I received the following error message: 

******************** step - correct_unwrap_error ********************
Input data seems to be geocoded. Lookup file not needed.
read options from template file: smallbaselineApp.cfg
--------------------------------------------------
update mode: ON
1) output dataset: unwrapPhase_bridging NOT found.
run or skip: run.
--------------------------------------------------
correct unwrapping error in /u/sar-r2/rzinke/Tibet/Chunks/T121Sd_33-35/inputs/ifgramStack.h5 with bridging ...
read water mask from file: waterMask.h5
open /u/sar-r2/rzinke/Tibet/Chunks/T121Sd_33-35/inputs/ifgramStack.h5 with r+ mode
input  dataset: unwrapPhase
output dataset: unwrapPhase_bridging
create /unwrapPhase_bridging of np.float32 in size of (357, 880, 1480)
[======================= 87% ===============>      ] 20180911_20181005 1518s /   226sTraceback (most recent call last):
  File "/u/sarh0/rzinke/tools/MintPy/mintpy/smallbaselineApp.py", line 1079, in <module>
    main()
  File "/u/sarh0/rzinke/tools/MintPy/mintpy/smallbaselineApp.py", line 1069, in main
    app.run(steps=inps.runSteps, plot=inps.plot)
  File "/u/sarh0/rzinke/tools/MintPy/mintpy/smallbaselineApp.py", line 1007, in run
    self.run_unwrap_error_correction(sname)
  File "/u/sarh0/rzinke/tools/MintPy/mintpy/smallbaselineApp.py", line 507, in run_unwrap_error_correction
    unwrap_error_bridging.main(scp_args_bridge.split())
  File "/u/sarh0/rzinke/tools/MintPy/mintpy/unwrap_error_bridging.py", line 302, in main
    dsNameOut=inps.datasetNameOut)
  File "/u/sarh0/rzinke/tools/MintPy/mintpy/unwrap_error_bridging.py", line 246, in run_unwrap_error_bridge
    cc_obj.label()
  File "/u/sarh0/rzinke/tools/MintPy/mintpy/objects/conncomp.py", line 76, in label
    raise ValueError('input reference point is NOT included in the connectComponent.')
ValueError: input reference point is NOT included in the connectComponent.


I get this same error whether I specify the reference point manually, or using the "auto" feature. However, I did not get this message with the non-multilooked data. Have you seen anything like this before or could you provide any suggested fixes?

Thanks!

**Comment by ehavazli** [comment]
I recommend resetting the reference point first since it is not done automatically:

```
reference_point.py inputs/ifgramStack.h5 --reset
```
and then change the reference point to a valid pixel in **maskconnComp.h5** in **smallbaselineApp.cfg**.
After making this change you can run the process over again and it will use the new reference point given in the cfg file.

If you want to change the reference point you either need to change it manually or reset it using **reference_point.py** and then continue with the process. 
You can check the reference point information using **info.py**

**Comment by yunjunz** [comment]
Hi @rzinke,

Since the process went through 87%, I guess the interferogram that caused the error (20180911_20181005) is low coherent and has very sparse connected component, which does not cover the reference point. Please check it using `view.py inputs/ifgramStack.h5 connectComponent-of 20180911_20181005`.

I would recommend check the `maskConnComp.h5`. If the coverage of this file is fine, manually choose another reference point as @ehavazli pointed out. Otherwise, drop this interferogram (and other similarly low-coherence interferograms) during network modification step, to increase the coverage of `maskConnComp.h5`.

**Comment by rzinke** [comment]
Hi @ehavazli and @yunjunz. Thanks for the assistance! 
It seems that the issue you both identified was the culprit. I overwrote the old reference point using the --reset option and reran the smallbaselineApp process. The result completed successfully (in a fraction of the time it would have taken at full resolution). 
Good to know about the use of view.py to check individual interferograms/maps/masks. I will remember that for the future. 

Cheers,
Rob

**Comment by rzinke** [comment]
One quick question... Is there a way to determine the index of an interferogram given the date pair. Something like index.py 20180911_20181005 > 32 ?

**Comment by yunjunz** [comment]
Yes, use `info.py --date --num`.

```
MacBook-Pro:~/data/test/FernandinaSenDT128/mintpy>: info.py inputs/ifgramStack.h5 --date --num
20141213_20141225	0
20141213_20150307	1
20141213_20150319	2
20141225_20150307	3
20141225_20150319	4
20141225_20150331	5
20150307_20150319	6
20150307_20150331	7
```

**Comment by rzinke** [comment]
Thanks @yunjunz !

**Comment by rzinke** [comment]
Hi. I have a (hopefully) final challenge for the downsampling routine in MintPy. I have successfully processed velocity maps for ascending and descending tracks that overlap, and would like to compute the EW and Vertical displacements from those. I used MintPy's asc_desc2horz_vert.py function, however, it appears the multilooking produced very slightly different pixel sizes. I get the following error: 
(MintPy) [rzinke@sar AscDsc_practice]$ asc_desc2horz_vert.py velocityT41_42-44.h5 velocityT121_41-43.h5 -o TestHorz TestUp
Traceback (most recent call last):
  File "/u/sarh0/rzinke/tools/MintPy/mintpy/asc_desc2horz_vert.py", line 189, in <module>
    main()
  File "/u/sarh0/rzinke/tools/MintPy/mintpy/asc_desc2horz_vert.py", line 107, in main
    raise ValueError('input files do not have the same spatial resolution\n{}'.format(msg))
ValueError: input files do not have the same spatial resolution
file1: velocityT41_42-44.h5
Y_STEP: -0.0025000000000000022 m, X_STEP: 0.0025000000000000022 m
file2: velocityT121_41-43.h5
Y_STEP: -0.0025000000000000022 m, X_STEP: 0.0024999999999999988 m

Is there any way to override this error, or to replace the pixel size values in the velocity files themselves?

Thanks for any help!
Rob

**Comment by yunjunz** [comment]
Hi Rob, you could re-run geocoding with specified step size in lat/lon and bounding box, check the example from the help for details please.

```
MacBook-Pro:~>: asc_desc2horz_vert.py -h
...
example:
  # for data with different spatial resolution and coverage
  # use geocode.py -x/y --bbox option to make them consistent
  cd AlosAT424/mintpy
  mask.py velocity.h5 -m maskTempCoh.h5
  geocode.py velocity_msk.h5 -l inputs/geometryRadar.h5 -x 0.00027778 -y -0.00027778 --bbox 32.0 32.5 130.1 130.5

  cd AlosDT73/mintpy
  mask.py velocity.h5 -m maskTempCoh.h5
  geocode.py velocity_msk.h5 -l inputs/geometryRadar.h5 -x 0.00027778 -y -0.00027778 --bbox 32.0 32.5 130.1 130.5

  asc_desc2horz_vert.py AlosAT424/mintpy/geo_velocity_msk.py AlosDT73/mintpy/geo_velocity_msk.py
```

The `-x, -x and --bbox` option in command line can also be specified in the template file as `mintpy.geocode.lat/lonStep and mintpy.geocode.SNWE`.

**Comment by rzinke** [comment]
Hi Yunjun, thanks. However, the data were geocoded to begin with (ARIA data), and so the geocoding function does not work on them. I try:

(MintPy) [rzinke@sar T41a_36-38_PC]$ geocode.py velocity.h5 -l inputs/geometryGeo.h5 -x 0.00025 -y -0.00025 -o T41a_velocity.h5
geocode.py velocity.h5 -l inputs/geometryGeo.h5 -x 0.00025 -y -0.00025 --bbox 36 38 87.5 90.5 -o T41a_velocity.h5
input file is already geocoded
to resample geocoded files into radar coordinates, use --geo2radar option
exit without doing anything.

And so I tried converting to radar first, then would convert back, but I seem to be missing the files to do that: 
(MintPy) [rzinke@sar T41a_36-38_PC]$ geocode.py velocity.h5 -l inputs/geometryGeo.h5 --geo2radar
geocode.py velocity.h5 -l inputs/geometryGeo.h5 --geo2radar
No lookup table info range/lat found in files.
Traceback (most recent call last):
  File "/u/sarh0/rzinke/tools/MintPy/mintpy/geocode.py", line 341, in <module>
    main(sys.argv[1:])
  File "/u/sarh0/rzinke/tools/MintPy/mintpy/geocode.py", line 333, in main
    inps = cmd_line_parse(iargs)
  File "/u/sarh0/rzinke/tools/MintPy/mintpy/geocode.py", line 96, in cmd_line_parse
    inps = _check_inps(inps)
  File "/u/sarh0/rzinke/tools/MintPy/mintpy/geocode.py", line 120, in _check_inps
    raise FileNotFoundError('No lookup table found! Can not geocode without it.')
FileNotFoundError: No lookup table found! Can not geocode without it.

**Comment by rzinke** [comment]
As a workaround, I came up with a Python script that will replace the values in the h5 file: 

#!/usr/bin/env python3
import os
import h5py
fpath='/Users/rzinke/Documents/Tibet/AGUmaps/AscDscTesting'
ascName='T41a_42-44_PC_velocity.h5'
dscName='T121Nd_41-43_PC_velocity.h5'

ascDS=h5py.File(os.path.join(fpath,ascName))

print(ascDS.attrs.keys())
print(ascDS.attrs['Y_STEP'])
print(ascDS.attrs['X_STEP'])

ascDS.attrs.modify('Y_STEP',-0.0025)
ascDS.attrs['X_STEP']=0.0025


dscDS=h5py.File(os.path.join(fpath,dscName))

print(dscDS.attrs.keys())
print(dscDS.attrs['Y_STEP'])
print(dscDS.attrs['X_STEP'])

dscDS.attrs['Y_STEP']=-0.0025
dscDS.attrs['X_STEP']=0.0025

**Comment by yunjunz** [comment]
Hi Rob, your solution looks fine with me. In case of your future datasets, you could also use `add_attribute.py` to add/modify the metadata.

```
yunjunz:~>$ add_attribute.py -h

usage: add_attribute.py file metadata_file
       add_attribute.py file key1=value1 [key2=value2 [...]]

Add/Update attributes to file.

Example:
  add_attribute.py timeseries.h5  unavco_attribute.txt
  add_attribute.py timeseries.h5  track=422   frame=650
  add_attribute.py ifgramStack.h5 ref_y=None  ref_x=None  #Use None value to delete attribute
```

**Comment by yunjunz** [comment]
I added an constrain on `X/Y_STEP/FIRST` metadata in `prep_aria.py`, so that this problem won't exists for your future datasets. Cheers.

**Comment by rzinke** [comment]
Awesome! Thanks, @yunjunz

**Comment by EJFielding** [comment]
Thanks for the description of `add_attribute.py`. This should help with a problem I have with reference points that have round-off errors.

> Hi Rob, your solution looks perfectly fine with me. In case of your future datasets, you could also use `add_attribute.py` to add/modify the metadata.
> 
> ```
> yunjunz:~>$ add_attribute.py -h
> 
> usage: add_attribute.py file metadata_file
>        add_attribute.py file key1=value1 [key2=value2 [...]]
> 
> Add/Update attributes to file.
> 
> Example:
>   add_attribute.py timeseries.h5  unavco_attribute.txt
>   add_attribute.py timeseries.h5  track=422   frame=650
>   add_attribute.py ifgramStack.h5 ref_y=None  ref_x=None  #Use None value to delete attribute
> ```

**Comment by yunjunz** [comment]
Another big memory related issue #359. Noted here for bookkeeping.

**Comment by yunjunz** [comment]
This is now resolved by the PR above. Hooray!
