### ISSUE TITLE
Pixel weighting option

### ISSUE THREAD

**Issue by rzinke** [insarlab/MintPy#241]
Hello, 

I was wondering if there was any interest in creating a weighting scheme that weighted each pixel differently based on values from, e.g., connected components, filtered coherence, etc. 

The reason for requesting this is because the connected components mask is too conservative for our purposes. It nullifies pixel values for "all time", even if the connected components are valid for most dates. Instead, it would be helpful for us to down-weight the phase at epochs when the connected component mask is 0, and keep the values when the mask is > 1. 

For instance, for each pixel, the weighting matrix would contain the variance values for each interferogram when the connected component is 1. But when the connected component is 0, the weighting value for that interferogram would be trivially small, e.g., 10^-5. 

I would be happy to help contribute or explain further.

Is that something you are interested in?

Best regards,
Rob Zinke

**Comment by yunjunz** [comment]
Hi Rob,

I am not sure if I got your interest completely. 

The phase variance (var or fim) is converted from filtered coherence. 

To assign a low weight to pixels with connected component of 0 is equivalent to mask out those pixels. Have you tried the `mintpy.networkInversion.maskDataset` option? This option helps to increase the spatial coverage (temporal coherence) when the kept interferograms (with overall moderate or high coherence) has some low coherent pixels. This option will result in pixels with different numbers of interferograms, as explained in section 4.5.1 in our paper. 

We could meet on the Caltech campus if that's easier to discuss.

**Comment by rzinke** [comment]
Hi Yunjun, 
Ah, yes! I think the maskDataset option is what I am looking for... As I understand, instead of masking out a pixel entirely based on the connComp mask, it only masks out interferograms when which the connected component is zero. Thus, the pixels can contain different numbers of interferograms. Sorry, I'd missed that option last time I'd read through.

It would be great to meet up at Caltech one day.

**Comment by yunjunz** [comment]
I am glad that you got what you are looking for!
