### ISSUE TITLE
Processing parameters for similarity to ARIA GUNW-derived time series

### ISSUE THREAD

**Issue by falkamelung** [insarlab/MintPy#250]
**Description of the desired feature**

Hi @dbekaert and @yunjunz 
To facilitate the transition to ARIA GUNW products(once more widely available) I would like to use in my topsStack, MintPy processing  parameters to end up with products as close as possible to GUNW-derived MintPy products.

On https://aria.jpl.nasa.gov/node/97 I see that 19 range looks and 7 azimuth looks are used. What spacing does ARIA use for geocoding?  It says "~90 m" for the data group, but this is is not very precise. Is the spacing specified in meters or  degrees?  If the first it would be good to add a mintpy option for spacing in meters as it currently supports only `mintpy.geocode.latStep` and `mintpy.geocode.lonStep `.

@hfattahi , topsStack products may differ from ARIA standard products because of the  Spectral Diversity Threshold. On the ARIA page I found the blurb below. Is there an option in topsStack to do the same thing? If not, could you point me to an ISCE function that does this for possible implementation into topsStack?

Thank you!

_Default is 0.8. If coherence is too low and ESD fails, threshold is relaxed in steps of 0.05 until 0.5 is reached, after which processing is done using orbit information only._

**Comment by hfattahi** [comment]
@falkamelung in the tops stack processor, the --esd_coherence_threshold should do what you need:

https://github.com/isce-framework/isce2/blob/master/contrib/stack/topsStack/stackSentinel.py#L138

**Comment by falkamelung** [comment]
Hi @hfattahi , Thank you, but yes, I am aware of that. What I mean is a script that does the ARIA routine: when and interferogram, fails gradually reducing the threshold and when it still fails when the threshold has reached 0.5 and then switch to 'geometry'.
That must exist in ISCE as it is used for ARIA. Could that be implemented into topsStack?

**Comment by dbekaert** [comment]
@falkamelung the ARIA project wraps around ISCE, for additional functionality it would need. e.g. Data/DEM staging, pairing decisions, orbit decisions, ESD fallback, naming conventions etc. The ARIA code is all on public github if you want to have a look. In short, it will check if the ISCE code runs or errors out on the ESD step, and the makes decisions based on that. 

repo is here: https://github.com/aria-jpl/ariamh
Standard product specific is here: https://github.com/aria-jpl/ariamh/tree/develop/interferogram/sentinel
