### ISSUE TITLE
save_kmz.py not working if 'zip' is not available

### ISSUE THREAD

**Issue by falkamelung** [insarlab/MintPy#251]
**Description of the problem**
save_kmz.py expects the unix command 'zip' to be available. If it is not (as on the compute nodes of our HPC system) you get a `sh: zip: command not found`  and there is no `*.kmz` produced.  It would be preferred to replace the unix command  with a python command.

**Full script that generated the error**

```
HERE THE OFFENDING LINE:
cmd = 'cd {d1}; zip {fz} {fl} {fd} {fc}; cd {d2}'.format(
        d1=os.path.abspath(os.path.dirname(kmz_file)),
        fz=os.path.basename(kmz_file),
        fl=os.path.basename(kml_file),
        fd=os.path.basename(data_png_file),
        fc=os.path.basename(cbar_file),
        d2=os.getcwd()
    )
    print(cmd)
    os.system(cmd)
```

**Full error message**

```
PASTE ERROR MESSAGE HERE
```

**System information**

* Operating system:
* Version of Python and relevant dependencies if applicable
* Version of MintPy (output of `smallbaselineApp.py -v`):

**Comment by yunjunz** [comment]
Hi @falkamelung, the `zip` and `rm` commands are now replaced by functions from `zipfile` and `os` modules, for both `save_kmz.py` and `save_kmz_timeseries.py`.
