### ISSUE TITLE
Core dumped when using view.py

### ISSUE THREAD

**Issue by sssangha** [insarlab/MintPy#270]
**Description of the problem**
After generating a TS using the latest '49d89fb' commit, I am unable to use "view.py" to visualize any outputs without it crashing. I should mention that I am also unable to view existing outputs from older runs as well, so I don't think my outputs leveraging the latest commits are corrupted.

**Full error message**

```
(mintpy) [ssangha@leffe run1_12312019]$ view.py /u/leffe-data/dbekaert/ARIA_CA/CA_144/DWR/run1_01022020/mintpy/velocity.h5 velocity
run view.py in MintPy release version v1.2.0-12, release date 2020-02-09
input file is velocity file: /u/leffe-data/dbekaert/ARIA_CA/CA_144/DWR/run1_01022020/mintpy/velocity.h5 in float32 format
file size in y/x: (7528, 5027)
turning glob search OFF for velocity file
num of datasets in file velocity.h5: 2
datasets to exclude (0):
[]
datasets to display (1):
['velocity']
data   coverage in y/x: (0, 0, 5027, 7528)
subset coverage in y/x: (0, 0, 5027, 7528)
data   coverage in lat/lon: (-121.193758034, 40.049519538, -117.00420596400001, 33.776083322)
subset coverage in lat/lon: (-121.193758034, 40.049519538, -117.00420596400001, 33.776083322)
------------------------------------------------------------------------
colormap: jet
figure title: velocity
figure size : [6.0, 7.1875210842766935]
read mask from file: maskTempCoh.h5
reading data ...
masking data
data    range: [-12.647075, 3.8018768] cm/year
display range: [-12.647075, 3.8018768] cm/year
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Reinstalling the application may fix this problem.
Abort (core dumped)
```

**System information**

* Operating system: Linux
* Version of Python and relevant dependencies if applicable: Python 3.7.6
* Version of MintPy (output of `smallbaselineApp.py -v`): v1.2.0-12, release date 2020-02-09

**Comment by yunjunz** [comment]
Hi @sssangha, the error message says it could not load the Qt platform. Have you installed XQuartz?

**Comment by sssangha** [comment]
@yunjunz yes I had. Plus I also made a new mintpy conda environment from scratch to segregate this new commit, and confirmed with the earlier version that I was able to run view.py just fine.

**Comment by sssangha** [comment]
@yunjunz I figured it out! All I had to do was reinstall qt and pyqt in my conda environment. Now it works without this core dump!

**Comment by yunjunz** [comment]
Great!
