### ISSUE TITLE
asc_desc2horz_vert.py does not work with timeseries file type

### ISSUE THREAD

**Issue by EJFielding** [insarlab/MintPy#274]
**Description of the problem**

I have two timeseries Step Model files from ascending and descending tracks. When I tried to run `asc_desc2horz_vert.py` on them it fails to write out the result because `writefile.py` requires a reference file.

**Full script that generated the error**

```
asc_desc2horz_vert.py A135_geo_timeseriesStepModel_msk.h5 D098_geo_timeseriesStepModel_msk.h5
```

**Full error message**

```
Using default MintPy Path: /home/fielding/tools/MintPy
---------------------
reading A135_geo_timeseriesStepModel_msk.h5
reading D098_geo_timeseriesStepModel_msk.h5
---------------------
get design matrix
incidence angle: 38.95743031204843
heading angle: 349.125244140625
incidence angle: 33.72858887716663
heading angle: 190.9101104736328
project asc/desc into horz/vert direction
---------------------
writing horizontal component to file: hz.h5
Traceback (most recent call last):
  File "/home/fielding/tools/MintPy/mintpy/asc_desc2horz_vert.py", line 271, in <module>
    main(sys.argv[1:])
  File "/home/fielding/tools/MintPy/mintpy/asc_desc2horz_vert.py", line 260, in main
    writefile.write(dH, out_file=inps.outfile[0], metadata=atr)
  File "/home/fielding/tools/MintPy/mintpy/utils/writefile.py", line 56, in write
    raise Exception('Can not write {} file without reference file!'.format(k))
Exception: Can not write timeseries file without reference file!
```

**System information**

* Operating system: Linux
* Version of Python and relevant dependencies if applicable
* Version of MintPy (output of `smallbaselineApp.py -v`): MintPy release version v1.2.0-14, release date 2020-02-10

**Comment by EJFielding** [comment]
It seems that the `asc_desc2horz_vert.py` script or one of the scripts it calls needs the same fix as in PR #273 .  The script now writes the files, but the output files can't be displayed with `view.py` or other programs because the `timeseries` dataset lost a dimension.

**Comment by EJFielding** [comment]
I tried making the same additions to `asc_desc2horz_vert.py` that were done in the other files under PR #273 and that made an output .h5 file that I can display with `view.py`. I still had trouble with the `save_gmt.py` command. I wonder if it would be better to change the output `FILE_TYPE` attribute to another type instead.

**Comment by yunjunz** [comment]
Hi @EJFielding, I agree with you. `timeseries` file type is not designed to have one acquisition, thus, it would require quite some changes in the code to make it work through all scripts. Simply changing the file type to a different name, i.e. `displacement`, would much easier. This can be done by changing the dataset name in the root level of HDF5 file from `timeseries` to `displacement.`

**Comment by EJFielding** [comment]
Does that mean we need a program to extract a step function "date" and make that a `displacement` dataset? I understand the `timeseriesStepFunction` output can have multiple dates, but I have only asked for one date.

**Comment by yunjunz** [comment]
You are right. The existing program can not do it, but this can be easily done in python in a notebook. After all, it's HDF5, manually playing around is straightforward.

The current problem is just because `timeseries` is a defined keyword in mintpy, and can not be used for something else.

**Comment by EJFielding** [comment]
I tried modifying the `asc_desc2horz_vert.py` script to change the `FILE_TYPE` attribute to `displacement` before writing out the results, which worked to change the dataset type. 
```
    # if original data was timeseries, convert it to displacement
    if atr['FILE_TYPE'] == 'timeseries':
         atr['FILE_TYPE'] = 'displacement';
```
I could view it with no problem, but `save_gmt.py` still refused to work. I guess other things need to be changed.

**Comment by yunjunz** [comment]
The save_gmt.py bug should be fixed now.

**Comment by EJFielding** [comment]
Thanks @yunjunz it works great now!
