### ISSUE TITLE
asc_desc2horz_vert.py is too strict about reference point matching

### ISSUE THREAD

**Issue by EJFielding** [insarlab/MintPy#275]
**Description of the problem**

The asc_desc2horz_vert.py is checking that the reference point latitude and longitude for the two input datasets is the same using 4 decimal digits. The rounding of the location of the reference point can be different when the reference point is set to the same value. Maybe the reference point is rounded to the nearest pixel of each dataset and they are not geocoded on the same grid?

**Full script that generated the error**

```
add_attribute.py A135_geo_timeseriesStepModel_msk.h5 ref_lat=18.2 ref_lon=-67.15
add_attribute.py D098_geo_timeseriesStepModel_msk.h5 ref_lat=18.2 ref_lon=-67.15
asc_desc2horz_vert.py A135_geo_timeseriesStepModel_msk.h5 D098_geo_timeseriesStepModel_msk.h5
```

**Full error message**

Note, I added an extra line to the script to report the values of the reference point location if it finds they are different. I was able to get the script to work if I change the number of digits used for checking the reference point to 2 decimal places. I was not sure if that is the best solution or whether the way that the reference point is stored in the HDF5 files should be changed.

```
Using default MintPy Path: /home/fielding/tools/MintPy
---------------------
reading A135_geo_timeseriesStepModel_msk.h5
reading D098_geo_timeseriesStepModel_msk.h5
---------------------
get design matrix
incidence angle: 38.95743031204843
heading angle: 349.125244140625
incidence angle: 33.72858887716663
heading angle: 190.9101104736328
project asc/desc into horz/vert direction
---------------------
writing horizontal component to file: hz.h5
Traceback (most recent call last):
  File "/home/fielding/tools/MintPy/mintpy/asc_desc2horz_vert.py", line 271, in <module>
    main(sys.argv[1:])
  File "/home/fielding/tools/MintPy/mintpy/asc_desc2horz_vert.py", line 260, in main
    writefile.write(dH, out_file=inps.outfile[0], metadata=atr)
  File "/home/fielding/tools/MintPy/mintpy/utils/writefile.py", line 56, in write
    raise Exception('Can not write {} file without reference file!'.format(k))
Exception: Can not write timeseries file without reference file!
(mintpy) [fielding@sar combo]$ asc_desc2horz_vert.py A135_geo_timeseriesStepModel_msk.h5 D098_geo_timeseriesStepModel_msk.h5
Using default MintPy Path: /home/fielding/tools/MintPy
data1 reference point ['18.1999', '-67.1501'] data2 reference point ['18.2006', '-67.1495']
Traceback (most recent call last):
  File "/home/fielding/tools/MintPy/mintpy/asc_desc2horz_vert.py", line 271, in <module>
    main(sys.argv[1:])
  File "/home/fielding/tools/MintPy/mintpy/asc_desc2horz_vert.py", line 251, in main
    inps = cmd_line_parse(iargs)
  File "/home/fielding/tools/MintPy/mintpy/asc_desc2horz_vert.py", line 99, in cmd_line_parse
    raise ValueError('input files do not have the same reference point from REF_LAT/LON values')
ValueError: input files do not have the same reference point from REF_LAT/LON values
```

**System information**

* Operating system:
* Version of Python and relevant dependencies if applicable
* Version of MintPy (output of `smallbaselineApp.py -v`):

**Comment by yunjunz** [comment]
Hi @EJFielding, 0.0001 deg ~= 10 m on the equator, so I think relaxing it to 3 decimal digits should still be fine.

You could try `reference_point.py --write-data` to change the `REF_X/Y/LAT/LON` metadata and update the matrix value. MintPy uses UPPER_CASE style for all metadata and is case sensitive.

**Comment by EJFielding** [comment]
Three digits sounds good. Thanks for also mentioning that the metadata is case sensitive and key parameters are UPPER_CASE. It is a bit confusing because `info.py` prints out a bunch of parameters that are lower case also, including mintpy.network.ref_lat. I understand now that the one that matters is the REF_LAT. 

I see that you already changed the comparison to 3 decimal digits or ~100 m, so that seems reasonable.

**Comment by EJFielding** [comment]
By the way, I tried to run the `reference_point.py --write-data` command on my time-series step function file and it did not work.
```
reference_point.py --write-data -l 18.2 -L -67.15 A135_geo_timeseriesStepModel_msk.h5
Using default MintPy Path: /home/fielding/tools/MintPy
--------------------------------------------------
input reference point in lat/lon: (18.2, -67.15)
input reference point in y/x: (330, 179)
--------------------------------------------------
calculating the temporal average of timeseries file: A135_geo_timeseriesStepModel_msk.h5
reading timeseries data from file: A135_geo_timeseriesStepModel_msk.h5 ...
/home/fielding/tools/MintPy/mintpy/objects/stack.py:464: RuntimeWarning: Mean of empty slice
  dmean = np.nanmean(data, axis=0)
Traceback (most recent call last):
  File "/home/fielding/tools/MintPy/mintpy/reference_point.py", line 447, in <module>
    main(sys.argv[1:])
  File "/home/fielding/tools/MintPy/mintpy/reference_point.py", line 440, in main
    reference_file(inps)
  File "/home/fielding/tools/MintPy/mintpy/reference_point.py", line 186, in reference_file
    if mask[inps.ref_y, inps.ref_x] == 0.:
IndexError: too many indices for array
```

Maybe I should open a new issue?

Updating the `REF_LAT` and `REF_LON` with `add_attribute.py` works. I understand that it won't update the values of the array for the new location, but I am only changing the reference point by less than a pixel in this case.

**Comment by yunjunz** [comment]
The code does keep all the metadata during the loading process, for the sake of completeness, although it uses UPPER_CASE only. "mintpy.*" metadata is saved to check the processing configurations.

**Comment by yunjunz** [comment]
Hi @EJFielding, the reference_point.py bug is fixed now.

**Comment by rzinke** [comment]
Hello, I am encountering a similar issue. 
I am not able assign a single reference point to my data sets in a scripted fashion, as the rounding error is different for the ascending and descending data sets. 

When I use refLat=37.07010 and refLon=89.20000 I get the following error message:
```
Traceback (most recent call last):
  File "/u/sarh0/rzinke/tools/MintPy/mintpy/asc_desc2horz_vert.py", line 278, in <module>
    main(sys.argv[1:])
  File "/u/sarh0/rzinke/tools/MintPy/mintpy/asc_desc2horz_vert.py", line 258, in main
    inps = cmd_line_parse(iargs)
  File "/u/sarh0/rzinke/tools/MintPy/mintpy/asc_desc2horz_vert.py", line 101, in cmd_line_parse
    raise ValueError('input files do not have the same reference point from REF_LAT/LON values!\n{}'.format(msg))
ValueError: input files do not have the same reference point from REF_LAT/LON values!
	file1: 41velocityMaskedRefd.h5, REF_LAT/LON: ['37.071', '89.200'] degrees
	file2: 121velocityMaskedRefd.h5, REF_LAT/LON: ['37.070', '89.200'] degrees
```
I have tried "jiggling" the numbers in various directions, but always I get a similar same error message, with the ascending reference point different from the descending.

I will try removing this check for now, but might need more attention in the future.

**Comment by yunjunz** [comment]
Thanks for bringing it up @rzinke. The current way of checking is not very friendly to datasets with low resolution, we should change it to check if the two reference points are close in terms of pixels, e.g. <=3 pixels. Let's re-open for a reminder.

**Comment by EJFielding** [comment]
@rzinke It seems that there are often some round-off errors that cause the reference points to be slightly different. As @yunjunz wrote above, you can use `reference_point.py --write-data` to change the `REF_X/Y/LAT/LON` metadata in the files to be exactly the same. This worked for me.
