### ISSUE TITLE
SNAP input data, file missing for pair warning

### ISSUE THREAD

**Issue by jpeppelman** [insarlab/MintPy#296]
**Description of the problem**

Hello,

I am trying to open SNAP input data in MintPy. 
I created the input data using the workflow of this document:

github.com/insarlab/MintPy/wiki/SNAP-input-data

I also use the directory structure of the document. 

In MintPy I try to load 3 different dates: 
4th of June, 10th of July and 22th of July.
The 10th of July is the only date that is recognized. 
In the load data step I receive the following messages:

WARNING: unwrapPhase file missing for pair ['20180803', '20180722']
WARNING: coherence file missing for pair ['20180803', '20180722']
WARNING: unwrapPhase file missing for pair ['20180803', '20180604']
WARNING: coherence file missing for pair ['20180803', '20180604']

The warnings in MintPy are included in this issue as an image.

![Warnings](https://user-images.githubusercontent.com/41291417/76323922-a09e8e80-62e5-11ea-8adf-88df4ddf70aa.png)

The unwrap phase and coherence of the 22th July and 4th of June are however included in the directory. This image below is an example:

![Knipsel4](https://user-images.githubusercontent.com/41291417/76325788-07bd4280-62e8-11ea-862f-52fd3fdc30eb.PNG)

I run mintpy with the following line:

   docker run -it -v C:/Project/Zetting/workdir5:/home/work/ andretheronsa/mintpy:latest python /home/python/MintPy/mintpy/smallbaselineApp.py /home/work/inputs/ZuidHolland2018.txt 

The ZuidHolland2018 text file has the following content:

[ZuidHolland2018.txt](https://github.com/insarlab/MintPy/files/4313105/ZuidHolland2018.txt)

I would like to know what causes the warnings.
Is there someone who can help me with this?

Thank you in advance,
Jan

**Full script that generated the error**

```
   docker run -it -v C:/Project/Zetting/workdir5:/home/work/ andretheronsa/mintpy:latest python /home/python/MintPy/mintpy/smallbaselineApp.py /home/work/inputs/ZuidHolland2018.txt 

```

**Full error message**

```


WARNING: unwrapPhase file missing for pair ['20180803', '20180722']
WARNING: coherence file missing for pair ['20180803', '20180722']
WARNING: unwrapPhase file missing for pair ['20180803', '20180604']
WARNING: coherence file missing for pair ['20180803', '20180604']
```

**System information**

* Operating system: Windows 10, but Docker should be Linux (?)
* Version of Python and relevant dependencies if applicable Python in Docker
* Version of MintPy (output of `smallbaselineApp.py -v`): MintPy v1.2beta-10

**Comment by yunjunz** [comment]
Hi @jpeppelman, please do the following: 

+ attach the complete error message, WARNING message is fine.
+ update your code to the latest version

**Comment by yunjunz** [comment]
Close it since it's not followed up.
