### ISSUE TITLE
Wrong  Sentinel track number in some HDF5 files: problem from ISCE topsStack

### ISSUE THREAD

**Issue by falkamelung** [insarlab/MintPy#297]
**Description of the problem**
The S1_IW* file produced by save_hdf5eos has for some data sets the wrong track number. For Kilauea T87 it saves it as T41 :
./KilaueaSenDT87/mintpy/S1_IW1_041_0527_0531_20180505_20200301.he5

This is actually an ISCE (topsStack) problem:
```
info.py ifgramStack.h5 | grep 41
  relative_orbit                      41
  trackNumber                         41
```
Are the ISCE people aware of this? I have the ISCE products removed already, but can add details to this issue after reprocessing the data.

```
PASTE ERROR MESSAGE HERE
```

**System information**

* Operating system:
* Version of Python and relevant dependencies if applicable
* Version of MintPy (output of `smallbaselineApp.py -v`):

**Comment by yunjunz** [comment]
Hi @falkamelung, I believe ISCE repo would be a better place to post this issue. If you could attach 1) the `KilaueaSenDT87/master/IW*.xml` file with the 2) path of one example Sentinel-1 SLC from ASF, that would also help to re-produce the error.

**Comment by yunjunz** [comment]
This is reported here https://github.com/isce-framework/isce2/issues/104 and has been fixed here https://github.com/isce-framework/isce2/pull/109.
