### ISSUE TITLE
reference_point.py not working as expected

### ISSUE THREAD

**Issue by sssangha** [insarlab/MintPy#304]
**Description of the problem**
I tried to redefine a new reference point in my time-series using "reference_point.py" (with the "--force" flag), before then running "timeseries2velocity.py" to extract an updated velocity field. I confirmed that my new reference point was set in the metadata of these outputs with "info.py", however when visualizing the updated velocity std field, it became apparent that although the reference point marker was correctly plotted, the field itself was not re-scaled and still referenced to the original reference point (see attached image where orange is ~0.3 cm/yr).
<img width="122" alt="Screen Shot 2020-03-21 at 1 17 23 PM" src="https://user-images.githubusercontent.com/13227405/77235826-74e99700-6b76-11ea-9a06-f12c9b7eedc5.png">

What I had articulated was a valid procedure to redefine the reference point, right?

**System information**

* Operating system:
* Version of MintPy (output of `smallbaselineApp.py -v`): MintPy release version v1.2.0-30, release date 2020-03-05

**Comment by yunjunz** [comment]
Hi @sssangha, please add the `--write-data` option to write the re-referenced/updated matrix value to the disk file; otherwise, the script will just update the metadata.

The `--force` option is for updating the metadata REF_X/Y as well.

**Comment by yunjunz** [comment]
The old way is confusing, I just updated the script (by hiding the --write-data option by default and adjust it based on the input file type) to behave as you expected. Thank you for bringing it up. Cheers.
