### ISSUE TITLE
mintpy.subset doesn't work

### ISSUE THREAD

**Issue by thorly** [insarlab/MintPy#323]
I set yx in config file (mintpy.subset.yx = [0:1000,400:700]), then I load the isce_stack data. When this done, I check the data size, it has the same size of origin data. Why?

**Comment by thorly** [comment]
It is my template. Origin data size is 1424x3148.

> ##-------------------------------- MintPy -----------------------------##
> ########## 1. Load Data (--load to exit after this step)
> ##load_data.py -H to check more details and example inputs.
> mintpy.load.processor        = isce
> ##---------for ISCE only:
> mintpy.load.metaFile         = ../isce_stack/master/IW*.xml
> mintpy.load.baselineDir      = ../isce_stack/baselines
> ##---------interferogram datasets:
> mintpy.load.unwFile          = ../isce_stack/merged/interferograms/*/filt_*.unw
> mintpy.load.corFile          = ../isce_stack/merged/interferograms/*/filt_*.cor
> mintpy.load.connCompFile     = ../isce_stack/merged/interferograms/*/filt_*.unw.conncomp
> ##---------geometry datasets:
> mintpy.load.demFile          = ../isce_stack/merged/geom_master/hgt.rdr
> mintpy.load.lookupYFile      = ../isce_stack/merged/geom_master/lat.rdr
> mintpy.load.lookupXFile      = ../isce_stack/merged/geom_master/lon.rdr
> mintpy.load.incAngleFile     = ../isce_stack/merged/geom_master/los.rdr
> mintpy.load.azAngleFile      = ../isce_stack/merged/geom_master/los.rdr
> mintpy.load.shadowMaskFile   = ../isce_stack/merged/geom_master/shadowMask.rdr
> mintpy.load.waterMaskFile    = None
> mintpy.subset.yx   			= [0:1000,400:700]
> mintpy.troposphericDelay.method         = height_correlation
> mintpy.deramp                           = linear

**Comment by yunjunz** [comment]
Hi @thorly, it should be `mintpy.subset.yx = 0:1000,400:700`, not `mintpy.subset.yx = [0:1000,400:700]`. You could see it in the example input files.
