### ISSUE TITLE
Exporting a shapefile using save_qgis.py error 

### ISSUE THREAD

**Issue by lamarashed** [insarlab/MintPy#331]
Hello, 

I'm trying to export a shapefile from MintPy to QGIS using save_qgis.py, but I got the following error:  

**Full script that generated the error**

```
save_qgis.py timeseries.h5 -g inputs/geometryGeo.h5 -o ts.sh
```

**Full error message**

```
Output shape file ts.sh exists. Will be overwritten ....
open timeseries file: timeseries.h5
Number of points with time-series:  829805
0Traceback (most recent call last):
  File "/Users/lama/MintPy/mintpy/save_qgis.py", line 217, in <module>
    main(mintpyDict, inps.outshp)
  File "/Users/lama/MintPy/mintpy/save_qgis.py", line 174, in main
    lat = geomid['latitude'][line,:].astype(np.float64)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/Users/lama/python/miniconda3/envs/mintpy/lib/python3.7/site-packages/h5py/_hl/group.py", line 264, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'latitude' doesn't exist)"
```
 What should I do to fix it ?

@piyushrpt @dbekaert 

**System information**
* Operating system: Mac OS 
* Version of Python : 3.7.4
* Version of MintPy : v1.2.0-7

Thank you,
Lama

**Comment by yunjunz** [comment]
Hi @lamarashed, assuming your input interferogram stack is in radar coordinates, you should use:

```bash
save_qgis.py timeseries.h5 -g inputs/geometryRadar.h5 -o ts.shp
or
save_qgis.py geo/geo_timeseries_ERA5_ramp_demErr.h5 -g geo/geo_geometryRadar.h5 -o ts.shp
```

**Comment by lamarashed** [comment]
Thank you @yunjunz 

I don't have neither geometryRadar.h5 nor geo_timeseries_ERA5_ramp_demErr.h5 

I’m using ARIA products... and I ran the following commands : 
```
conda activate ARIA-tools
ariaDownload.py --track 87 --bbox "28.2618 28.5803 35.1965 37.0116"
ariaTSsetup.py  -f 'products/*.nc' -b '28.2618 28.5803 35.1965 37.0116' -d Download --mask Download
prep_aria.py -s stack/ -d DEM/SRTM_3arcsec.dem -i incidenceAngle/20141023_20141011.vrt  -a azimuthAngle/20141023_20141011.vrt --water-mask mask/watermask.msk
conda deactivate
conda activate mintpy
smallbaselineApp.py -g 
smallbaselineApp.py 
```

**Comment by dbekaert** [comment]
Hi Lama, I suspect you might not have pyaps installed and the for ERA5 was
not created.
You could consider turning it off in the config file and then re-run the
command.

**Comment by lamarashed** [comment]
Hello David,

I do have pyaps installed

```
******************** step - correct_troposphere ********************
Input data seems to be geocoded. Lookup file not needed.
Atmospheric correction using Weather Re-analysis dataset (PyAPS, Jolivet et al., 2011)
Weather Re-analysis dataset: ERA5
['timeseries_ERA5.h5'] exists and is newer than ['timeseries.h5', './inputs/ERA5.h5'] --> skip.
``` 
 I tried to change it to no instead of pyaps and re-run the smallbaselineApp.py but still didn't get the files
```
mintpy.troposphericDelay.method = no  #[pyaps / height_correlation / no], auto for pyaps 
```

**Comment by yunjunz** [comment]
Hi @lamarashed, now I know why the error happens: we don't explicitly have a latitude/longitude dataset in the geometry file while we load ARIA products, because they can be calculated on the fly from the metadata. However, this calculation is not implemented in save_qgis.py yet. It should be an easy fix.

**Comment by yunjunz** [comment]
It works for me now with ARIA+MintPy products. @lamarashed Could you check yours?

**Comment by lamarashed** [comment]
I tried the same command above: save_qgis.py timeseries.h5 -g inputs/geometryGeo.h5 -o ts.sh
and it worked ! Thanks a lot @yunjunz and @dbekaert

**Comment by nadiahassanpour** [comment]
> Hi @lamarashed, assuming your input interferogram stack is in radar coordinates, you should use:
> 
> ```shell
> save_qgis.py timeseries.h5 -g inputs/geometryRadar.h5 -o ts.shp
> or
> save_qgis.py geo/geo_timeseries_ERA5_ramp_demErr.h5 -g geo/geo_geometryRadar.h5 -o ts.shp
> ```
> 
> Check the script help message and example please.

Dear Yunjunz, Is there a script like 'save_qgis.py' to save text or CSV?

**Comment by irmayolii** [comment]
Hi @yunjunz How can I get  timeseries_SET_ERA5_ramp_demErr.h5 file?, because after I run all the script I just got timeseries.h5, and what's the different between timeseries_ERA5 and timeseries.h5?

I want to run this example script to visualization on my data

%matplotlib widget
import os
from mintpy.cli import tsview

ts_file = os.path.expanduser('~/data/test/FernandinaSenDT128/mintpy/timeseries_SET_ERA5_ramp_demErr.h5')
cmd = f'{ts_file} --yx 220 300 --figsize 9 3 --ref-date 20141225 '
tsview.main(cmd.split())
