### ISSUE TITLE
matplotlib behavior change

### ISSUE THREAD

**Issue by bbuzz31** [insarlab/MintPy#336]
There was a small change in the default behaviour of matplotlib's `imshow` function: https://github.com/matplotlib/matplotlib/issues/17345

I did a quick check and don't think it affects MintPy functionality (since the operational calls to MintPy seem to all have `interpolation` specified), but possibly worth a more robust check.

**Comment by yunjunz** [comment]
Thank you @bbuzz31 for the heads-up. We were aware of the antialiasing effect from matplotlib previously (not this recent default behavior change) used in `view.py` and `tsview.py`. I will do a thorough check on all the other scripts.

FYI, this antialiasing effect is usually more severe in the active display window than in the saved image files, as we could save the figure with higher dpi than the resolution of our monitor. For example, view.py is using 300 by default. I am using  >= 600 dpi for all my publication figures. In these circumstances, as described in the [matplotlib doc](https://matplotlib.org/gallery/images_contours_and_fields/image_antialiasing.html#sphx-glr-gallery-images-contours-and-fields-image-antialiasing-py), upsampling is desired and `interpolation = nearest` is more appropriate as we could see the sharp boundary between pixels. You might want to check that for https://github.com/aria-tools/ARIA-tools/pull/162.
