### ISSUE TITLE
dask options

### ISSUE THREAD

**Issue by falkamelung** [insarlab/MintPy#343]
I am not sure `mintpy.networkInversion` is a good option name to control dask. We also want to use dask for other processing steps (dem error, unwrap error correction)  Shall we give it its own name?  
Furthermore, on some HPC systems only shared queues are available (e.g. Deqing). So it would be good to use for the 'auto' values the values of environment variables if given. That would eliminate editing the *template file when switching

```
mintpy.dask                  = yes #[yes / no], auto for no, parallel processing using dask
mintpy.dask.cluster     = local #[slurm / pbs / lsf / local], auto for local, cluster type (auto overwritten by $DASK_CLUSTER envionment )
mintpy.dask.numWorker   = all #[int > 0 / all], auto for 4 (local) or 40 (non-local), 'all' to use all (auto overwritten by $DASK_NUM_WORKER )
mintpy.dask.walltime   = auto #[ 00:30 for auto , 'all' to use all (auto overwritten by $DASK_NUM_WORKER )
```

**Other items:** 
1. walltime: Do we still give walltime? If so we should be able to give both  HH:MM and HH:MM:SS format (used by LSF, SLURM)

2. @yunjunz : for an intermediate-big data set (Big Island) it calculates in 350 chunks. It this correct? Shall we not just use 16 chunks if we have 16 cores available?

3. @Ovec8hkin On pegasus we also need to support the general (shared) queue . We should make it work for all three localCluster, LSFCluster general queue, LSFCluster parallel queue.  

4. There are '/mintpy/defaults/dask.yaml` and `/mintpy/defaults/mintpy.yaml` . Can we reduce to one? There is Miami specific options hardwired, which we should get rid off:
```
  lsf:
    queue: general
    project: insarlab
```

**Comment by yunjunz** [comment]
I agree with renaming the template option, but this is not necessary or urgent currently. `dem_error.py` is the second most time-consuming script in the workflow. If someone implemented the dask support for that, then we could change the template option for dask.

**Comment by yunjunz** [comment]
Tieing the template option value to the environment name does not sound like a good idea to me. 

The chunk size is more for memory handling, not for parallel. It's an option in the script, you could change it according to your own need.

There is only one `mintpy/defaults/*.yaml` in the code, you might want to re-check your code, we cleaned that when Josh pushed the generic cluster support.

**Comment by falkamelung** [comment]
Sorry. Yes. You are right. I got confused with versions.

I would suggest to rename mintpy.yaml to mintpy_dask.yaml . There may be other *yaml files at a later stage. How do you think?

Regarding  defaults and environment variables , I hear you.   But it would make sense to switch dask on and off using an environment variable. How about:

`MINTPY_DASK_CLUSTER = false, local, scheduler`  (variable not set would be false)

This would eliminate
```
mintpy.networkInversion.parallel
mintpy.networkInversion.cluster
```

We certainly should not specify lsf, slurm in the file. If 'scheduler' is given, it would use JOB_SCHEDULER which we have in minsar

**Comment by yunjunz** [comment]
> I would suggest to rename mintpy.yaml to mintpy_dask.yaml . There may be other *yaml files at a later stage. How do you think?

`~/.config/dask/mintpy.yaml` seems pretty unique and clear to me. Uses are expected to modify it according to their need. If this is not clear, we should update our doc.

**Comment by falkamelung** [comment]
I am not a fan of having anything in ~/.config . If you re-install you may forget.   I would much prefer to use /mintpy/defaults/mintpy_dask.yaml.  If it gets modified because of queue or wall time changes a copy in the workdir  should be used (/FernandinaSenDt128/mintpy/mintpy_dask.yaml). Else you can't run two datasets with different task parameters.

We don't need to do this for LocalCluster (I think) but we do need for LsfCLuster, etc.

**Comment by yunjunz** [comment]
A local copy of minpty_dask.yaml does sound great, if it's doable.

**Comment by yunjunz** [comment]
If you have a working version of any of these, please issue a pull request. 

I don't have any strong opinion on filenames, and it's easy to change whenever it's needed.

**Comment by Ovec8hkin** [comment]
@falkamelung I agree with Yunjun that we should **not** introduce environment variables in any capacity into MintPy. Their use enforces our idea of software architecture on anyone who uses MintPy and will make its adoption by other users more tedious and difficult. Remember that MintPy does not exist to conform precisely to InSAR-lab needs, and has to remain generalized for the wider community. If YOU would like to use environment variables to control MintPy options, I would suggest you right your own custom wrappers around MintPy to do so.

@yunjunz You mentioned above that `dem_error.py` is the next most costly compute step. Should I look into parallelizing it with Dask as `ifgram_inversion.py` is done?

@falkamelung @yunjunz I can look into whether you can have "local" copies of the `dask.yaml` file to use for each project. I agree that this would actually be a good idea to have. If this feature does not exist, we can pretty easily implement it ourselves, by reading in a custom `dask.yaml` file and passing all of the parameters to the cluster object manually.

**Comment by yunjunz** [comment]
Hi @Ovec8hkin, I think we should focus on further improving `ifgram_inversion.py`. It's more important than improving `dem_error.py`. I put a list here at #347.

**Comment by Ovec8hkin** [comment]
Regarding local copies `dask.yaml`, there does not appear to be a built in way to accomplish this. Let me know the priority level and I can start working on a wrapper to read this information ourselves.

**Comment by yunjunz** [comment]
Since the `local` cluster does not use *.yaml file, I would say this can wait, because the current way still work, even though it's not as convenient as I would like. What do you think @falkamelung ?

**Comment by falkamelung** [comment]
Yeah, lets first get the local one to work.  
So there is no environment variable for its location? Then we can modify that one as needed and possible have a link in the local directory.

**Comment by Ovec8hkin** [comment]
The file location can not be specified at runtime, so you would have to modify the environment variable value before every run to point to the correct location, which would be a hassle. There is an environment variable, but its for global use.
