### ISSUE TITLE
Why mintpy numpy functions don't run in parallel under linux? 

### ISSUE THREAD

**Issue by falkamelung** [insarlab/MintPy#346]
Hi @hfattahi @Ovec8hkin @yunjunz 
If you run MintPy on a Mac the top command  shows you occasionally 400%, indicating that 4 processors are working (for numpy and scipy, I think, e.g dem_error.py).  Under linux it does not do that? Why is that? Are we just missing some conda libraries/run options?

An easy way to test this would be to run a dummy script that  we know works in parallel on the Mac under linux. Did anybody try that? On Stampede you can log into  your node, so that would be easy to try.

The reason why I am adamant on optimizing speed is because on Stampede requested wall time matters. Wait time is about twice the requested wall time. So, a job with 2 hours wall time waits 4 hours until it starts.  I hope to assign wall time based on the size of the job.

**Is your feature request related to a problem? Please describe**

**Describe the solution you'd like**

**Describe alternatives you have considered**

**Additional context**

**Are you willing to help implement and maintain this feature?** Yes/No

**Comment by Ovec8hkin** [comment]
You probably will not see this type of information reported via `top` on an HPC cluster FYI. The best way to test if it is working is to run the same scripts under Mac and Linux OS's and see if their runtimes are similar (+/- 30s).

**Comment by falkamelung** [comment]
We did Mac-pegasus comparisons. The Mac is generally a factor of 4-10 faster. The wen  we realized what causes it. Fernandina from MintPy could be a useful data set for initial comparison

**Comment by yunjunz** [comment]
FYI, On Linux RedHat, without dask, ifgram_inversion.py (one process) could use up to 1300% CPU, which just means it uses 13 CPUs. With the 'local' cluster turned ON, more processes (6) are initiated with each of them using ~%200 CPU, so similar performance. 

I thought the 'local' cluster helped you solved this issue of using more CPUs. Why are we still discussing here?

**Comment by Ovec8hkin** [comment]
According to the LocalCluster documentation if the number of workers specified is less than or equal to the number of CPUs on the machine, each worker will be allocated a single CPU to use.   This is specified by the `mintpy.networkInverison.numWorkers` option.

**Comment by Ovec8hkin** [comment]
On Stampede, I see a significant speed increase when increasing the number of workers being used, indicating more CPUs are being used simultaneously.

**Comment by Ovec8hkin** [comment]
@falkamelung It is also possible that Pegasus has something that is somehow restricting the number of parallel processes that are running, because I have experience something similar on the compute nodes on Comet. I

**Comment by falkamelung** [comment]
Wow, you were able to get 1300%?  Are you doing special tricks?   I only get 100% (see screenshot below). Am I missing something? This is why we discuss. We could use this for dem_error.py where we don't have LocalCLuster

<img width="630" alt="image" src="https://user-images.githubusercontent.com/11162588/81773220-d6aee900-94b5-11ea-99d9-2a909c3dca61.png">

**Comment by yunjunz** [comment]
@falkamelung, I don't think I did anything special, just conda or mac-ports. I always guess it's maybe the restriction from the cluster. I got the same 100% on pegasus too. The 1300% one is a local cluster, without job scheduler.

**Comment by Ovec8hkin** [comment]
I expect you will not see >100% CPU usage on an HPC Custer (either Stampede or Pegasus), as such overclocking behavior is probably not supported on those large machines,.

**Comment by Ovec8hkin** [comment]
Here are the results of running the Fernandina, Kilauea, and Galapagos datasets with various numbers of cores on Stampede. It appears the LocalCluster significantly increases performance up until ~32 cores, after which performance increase is negligible.

![Screen Shot 2020-05-16 at 6 52 15 PM](https://user-images.githubusercontent.com/9124240/82132585-e45eba00-97a6-11ea-937f-98ccd91d8cef.png)

**Comment by yunjunz** [comment]
I believe the question is answered by the 3 comments above.

**Comment by falkamelung** [comment]
Here options that TACC consult suggests. The last one is important but it does no resolve this.

#SBATCH -N 1
#SBATCH -n 48
export OMP_NUM_THREADS=48
