### ISSUE TITLE
dask wrapper for generic parallelization of pixel-wise computing 

### ISSUE THREAD

**Issue by yunjunz** [insarlab/MintPy#354]
To facilitate the mitigation of block-by-block IO and dask parallel strategy https://github.com/insarlab/MintPy/issues/347 to other steps, I believe there is still room to further pack the dask calling code, by moving everything from [L986](https://github.com/insarlab/MintPy/blob/master/mintpy/ifgram_inversion.py#L986) to [L1058](https://github.com/insarlab/MintPy/blob/master/mintpy/ifgram_inversion.py#L1058) into a dask wrapper / class, i.e.  `daskCluster` in objects/cluster.py.

The input should be:
+ the computing function
+ box - one element of the primary box list.
+ inps - a namespace object containing all the other data that are invariant to different boxes.

The output should be multiple 2D or 3D matrices, representing the output result of the input box. All the result gathering and assembly could be done within the wrapper function, because all the computing are done in a pixel-by-pixel basis, thus, the splitting for parallelization is always in space (x or y dimension). And the assembly could grab the splitting info from the `sub_boxes`.

And the dask relevant code in ifgram_inversion.py should be like as below:

```python
cluster_obj = daskCluster(cluster=inps.cluster, num_worker=inps.numWorker, walltime=inps.walltime, config=inps.config)
cluster_obj.open()
cluster_obj.submit(func=ifgram_inversion_patch, box=box, inps=inps)
tsi, temp_cohi, num_inv_ifgi = cluster_obj.results
cluster_obj.close()
```

Then for dem_error.py or any other pixel-by-pixel computing scripts, we would just need to write a patch/box-based function, similar to ifgram_inversion_patch(), and then use the above code to call dask to speedup (the number of output matrices would vary of course).

**Comment by yunjunz** [comment]
To achieve this, we need to get rid of using `parallel_ifgram_inversion_patch()` style wrapper function, and to use `ifgram_inversion_patch()` directly. Can we do that @2gotgrossman, @Ovec8hkin ?

I could modify the current version of `ifgram_inversion_patch()` to take 2 arguments (box, inps) instead of the current 10.

**Comment by Ovec8hkin** [comment]
This sound reasonable. The abstraction is nice and simple should port easily since the outputs will always be the same type. 

I will look more closely and begin implementations on Monday.

**Comment by yunjunz** [comment]
Hi @Ovec8hkin, I just committed the arguments change for ifgram_inversion_patch().

Please also note the template options change for the related configurations.
