### ISSUE TITLE
Mulitlook interpolate example

### ISSUE THREAD

**Issue by 4restwilliams** [insarlab/MintPy#378]
The second Multilook.py example that covers the interpolation of an image to larger sizes (link [here](https://github.com/insarlab/MintPy/blob/17ec4830dcfef01fda9bb01ed3aadb716f06d3a3/mintpy/multilook.py#L29)) appears to have incorrect syntax:
`multilook.py  bperp.rdr  -10 -2 -o bperp_full.rdr`
I imagine that syntax should be:
`multilook.py  bperp.rdr  -r -10 -a -2 -o bperp_full.rdr`
But this throws an error. What would be the correct way to interpolate an image to a larger size?

**Comment by yunjunz** [comment]
Hi @4restwilliams, interpolation within multilook.py is not implemented. Please ignore this usage, I will remove it in the next commit.

Interpolation itself is a very general and wide concept, so I guess the "correct way" depends on the specific scenario. 

In the "example" above, I was trying to interpolate the coarse resolution bperp grid from ISCE into a linearly continuous surface. This is eventually implemented here: https://github.com/insarlab/MintPy/blob/master/mintpy/objects/stackDict.py#L570.

**Comment by 4restwilliams** [comment]
Good to know. Thanks for clarifying this!
