### ISSUE TITLE
ifgram_inversion.py: skip existing patches in the file

### ISSUE THREAD

**Issue by falkamelung** [insarlab/MintPy#382]
**Description of the desired feature**
It would be useful to display the time passed after each patch so that you can get a rough idea of how long a run will take (and adjust walltime accordingly).   From the current stdout output I find the lines below useful but you can't predict ETA with this  

```
grep patch out_mintpy.o 
split 4359 lines into 22 patches for processing
    with each patch up to 200 lines
------- processing patch 1 out of 22 --------------
split patch into 16 sub boxes in x direction for workers to process
------- processing patch 2 out of 22 --------------
split patch into 16 sub boxes in x direction for workers to process
------- processing patch 3 out of 22 --------------
split patch into 16 sub boxes in x direction for workers to process
------- processing patch 4 out of 22 --------------
split patch into 16 sub boxes in x direction for workers to process
------- processing patch 5 out of 22 --------------
split patch into 16 sub boxes in x direction for workers to process
------- processing patch 6 out of 22 --------------
split patch into 16 sub boxes in x direction for workers to process
------- processing patch 7 out of 22 --------------
```

Some other mintpy functions display time. Maybe something simple like:
```
start_time = time.time()
print (round (time.time()-start_time)
```

Actually, a  more useful feature would be to save `time_series.h5` after each patch and the next run would start after the last complete patch, but this sounds a bit complicated.

**Comment by yunjunz** [comment]
Both features are implemented already.

**Comment by falkamelung** [comment]
I see that it is there. But it does not show up in piped stdout. It is the same issue as 
https://github.com/insarlab/MintPy/issues/168

Adding a `sys.stdout.flush()` may solve this.

**Comment by yunjunz** [comment]
I suspect so. If you or other people could find a solution, this will be a useful feature.

**Comment by falkamelung** [comment]
Regarding 'both features are implemented',  do you mean interrupting is possible, and it will continue with the patch where it left off?  That would be very useful.  

I tried but it does not seem to work. I ran `smallbaselineApp.py --start invert_network` and interrupted after one patch (control c). When I run again it skips `ifgram_inversion.py` . The image suggests only one patch was processed. Is that a bug?
![image](https://user-images.githubusercontent.com/11162588/85247878-38e7fb80-b41d-11ea-9d8e-460a001e8754.png)

**Comment by yunjunz** [comment]
Now I get what you meant. No, that feature is not available. If the output for each patch is independent files, that feature would be very useful; with the current one output file, it sounds risky and error-prone to me.

**Comment by Ovec8hkin** [comment]
> I see that it is there. But it does not show up in piped stdout. It is the same issue as 
> 
> https://github.com/insarlab/MintPy/issues/168
> 
> 
> 
> Adding a `sys.stdout.flush()` may solve this. 
> 
> 

Use of sys.stdout.flush() is not recommended per Python standards. The true problem is due to computing configurations not flushing their stdout as it’s computationally expensive. This is not something for us to deal with.

**Comment by Ovec8hkin** [comment]
> Now I get what you meant. No, that feature is not available. 
> 
> I agree that this would be a very useful feature, especially for large dataset. Contributions are definitely welcomed. 

This would be nice. I’m not sure how you detect what the most recently completed patch is though. If this is easy to determine, them this implementation shouldn’t be horribly difficult.
