### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by Riley-coder7** [insarlab/MintPy#392]
there is no .bash_profile file in my computer(ubuntu16),when i create it,seem not useful

**Comment by Riley-coder7** [comment]
CONDA_PREFIX/bin/conda activate mintpy

CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.

# install dependencies with conda
$CONDA_PREFIX/bin/conda config --add channels conda-forge
$CONDA_PREFIX/bin/conda install --yes --file $MINTPY_HOME/docs/conda.txt
$CONDA_PREFIX/bin/pip install git+https://github.com/tylere/pykml.git

**Comment by yunjunz** [comment]
Hi @Riley-coder7, please fill the info in the bug report template if you want help.

**Comment by Riley-coder7** [comment]
Thanks for your answer,I have solve the install problem,  the eviveriment path edit file is ~/.profile;
the second problem is  change "CONDA_PREFIX/bin/conda activate mintpy" to "conda activate mintpy ".
But there is anaother problem "No module named 'pyresample'". i can't found this moudle in the Mintpy

**Comment by yunjunz** [comment]
Please read the documents. 

Close it this issue since it's not a bug, discussion, or feature request related.
