### ISSUE TITLE
KeyError: 'range_resolution' in prep_aria.py

### ISSUE THREAD

**Issue by ReemAlshammari** [insarlab/MintPy#408]
**Description of the problem**
I got error with step - correct_topography, when reading "incidenceAngle".
I think "incidenceAngle" is empty,  the geometryGeo.h5 created by using "prep_aria.py".

**Full script that generated the error**

```
smallbaselineApp.py 
```

**Full error message**

```
open geometry file: geometryGeo.h5
read 2D incidenceAngle,slantRangeDistance from geometry file: geometryGeo.h5
read mean bperp from timeseries file
/mintpy/dem_error.py:259: RuntimeWarning: invalid value encountered in sin
inps.sinIncAngle = np.sin(inps.incAngle * np.pi / 180.)```


**System information**

* Operating system: macOS
* Python environment: conda
* Version of MintPy: MintPy release version v1.2, release date 2020-01-03

**Comment by yunjunz** [comment]
You can run `view.py inputs/geometryGeo.h5 incidenceAngle` to see how it looks like.

My guess is this is a bug/warning related with no-data, and it has been fixed before. You should try it with the latest version.

**Comment by ReemAlshammari** [comment]
You're right I'm using old version but this is because when I RUN the latest version (MintPy release version v1.2.3, release date 2020-07-14), I got error when running ""prep_aria.py"" . 
The error is : 
""
extract metadata from /stack/unwrapStack.vrt
Traceback (most recent call last):
  File "/MintPy/mintpy/prep_aria.py", line 504, in <module>
    main()
  File "/MintPy/mintpy/prep_aria.py", line 442, in main
    metadata = extract_metadata(inps.unwFile)
  File "/MintPy/mintpy/prep_aria.py", line 261, in extract_metadata
    rgfact = sen_dict['IW2']['range_resolution'] / sen_dict['range_pixel_size']
KeyError: 'range_resolution' ""

how to solve it ? 
Thank you.

**Comment by yunjunz** [comment]
Hi @ReemAlshammari, the KeyError above is a bug introduced in the recent commit, after the v1.2.3 release. Thank you for identifying this! It should be fixed now. Please update your mintpy code and try again.
