### ISSUE TITLE
support GACOS for correcting troposphere

### ISSUE THREAD

**Issue by thorly** [insarlab/MintPy#414]
**Description of the desired feature**

**Is your feature request related to a problem? Please describe**

**Describe the solution you'd like**

**Describe alternatives you have considered**

**Additional context**

**Are you willing to help implement and maintain this feature?** Yes/No

**Comment by yunjunz** [comment]
https://nbviewer.jupyter.org/github/insarlab/MintPy-tutorial/blob/master/applications/tropo_gacos.ipynb

**Comment by thorly** [comment]
thanks

**Comment by thorly** [comment]
Hi @yunjunz, do you plan to add gacos to the smallbaselineApp.py?

**Comment by yunjunz** [comment]
Hi @thorly, it's not on the to-do list. Contributions are welcomed.

**Comment by thorly** [comment]
Thanks, I will try it.
