### ISSUE TITLE
SNAP preprocessing

### ISSUE THREAD

**Issue by deyress** [insarlab/MintPy#415]
Hello,

I am trying to make SNAP preprocessing work along with MintPy. I have followed the tutorial and reached the exact same file structure. 

> 
> -20200606_202006012/
> 
> >    -20200606_202006012_unw_tc/
> >    -20200606_202006012_coh_tc/
> 
> -20200606_202006018/
> 
> >    -20200606_202006018_unw_tc/
> >    -20200606_202006018_coh_tc/
> 
> -dem_tc/

I have register master/slave pair individually.

When I try to exectue: prep_snap.py ../interferogram/*/*/coh*.img, I got the following error:

`"prep_snape.py", line 202, in extract_snap_metadata
    xyz = (float(x[0]), float(y[0]), float(z[0]))
IndexError: list index out of range`

My data looks fine (when opened in SNAP) but fail to load with Mintpy. Any idea why?

**Comment by yunjunz** [comment]
There was a bug in `prep_snap.py`. It's fixed now. Not sure if this is related to the error you have. 

Here is the two example *.dim files for your reference: https://gist.github.com/yunjunz/00a5b2a418666475cf7fd4413c2b686e

**Comment by deyress** [comment]
Thank you! It solved the issue.
