### ISSUE TITLE
view.py plotting multiple points

### ISSUE THREAD

**Issue by liuykai** [insarlab/MintPy#418]
**Description of the problem**

There might be a problem when using view.py to plot multiple self-defined points from a file composed of two columns (lat/lon). 

There is no issue when the point file has only one row (one point). But as the second row (a second point) presents, the coordinates are messed up. 

I think the problem lies within utils/plot.py and the function read_pts2inps(). I can say all the points in my file were read correctly (I print them out). But I couldn't see what might went wrong after reading the file.

Only one point: 

![image](https://user-images.githubusercontent.com/55262505/89719839-3d428680-d981-11ea-8743-43163ec583eb.png)

![image](https://user-images.githubusercontent.com/55262505/89719759-965dea80-d980-11ea-86ea-9e98c0c1fd6d.png)

With a second point: 

![image](https://user-images.githubusercontent.com/55262505/89719835-33b91e80-d981-11ea-843a-dfebcdfcda78.png)

![image](https://user-images.githubusercontent.com/55262505/89719769-a8d82400-d980-11ea-9a42-cdbcd972ad9e.png)

**Full script that generated the error**

```
view.py avgSpatialCoh.h5 --pts-marker r^ --pts-ms 10 --pts-file pixels_coast.txt
```

**Full error message**

N/A

**System information**

* Operating system: 
* Python environment: 
* Version of MintPy: 
* Your custom / default template file (if the bug is related to a specific dataset):

**Comment by yunjunz** [comment]
You are right @liuykai, it was a bug while reshaping the array of coordinates for multiple points input in utils.plot.read_pts2inps(). It's fixed now, as shown below. Thank you!

```
view.py geo_velocity.h5 velocity --pts-file pts.latlon
```
![Screen Shot 2020-08-08 at 4 16 23 PM](https://user-images.githubusercontent.com/13143710/89721488-f6f62300-d992-11ea-8ea3-65ee9f619515.png)

**Comment by liuykai** [comment]
Thank you for fixing it.
