### ISSUE TITLE
Key Error DATE12 for ISCE Sentinel stack

### ISSUE THREAD

**Issue by rzinke** [insarlab/MintPy#432]
Hello, I have processed ISCE stack data before, but have not encountered this issue before. I have tried to find the source of the issue myself, but have not yet been able. I was hoping for some help solving it.

I processed six interferograms using the ISCE stack processor. All six turned out fine. I am trying to load these into MintPy using the following specifications in a Parameters.txt file:

mintpy.load.processor = isce
mintpy.load.metaFile = ../master/IW*.xml
mintpy.load.baselineDir = ../baselines
mintpy.load.unwFile = ../merged/interferograms/*/filt_*.unw
mintpy.load.corFile = ../merged/interferograms/*/filt_*.cor
mintpy.load.connCompFile = ../merged/interferograms/*/filt_*.unw.conncomp
mintpy.load.demFile = ../merged/geom_master/hgt.rdr
mintpy.load.lookupYFile = ../merged/geom_master/lat.rdr
mintpy.load.lookupXFile = ../merged/geom_master/lon.rdr
mintpy.load.incAngleFile = ../merged/geom_master/los.rdr
mintpy.load.azAngleFile = ../merged/geom_master/los.rdr
mintpy.load.shadowMaskFile = ../merged/geom_master/shadowMask.rdr
mintpy.load.waterMaskFile = None

I have checked that each of the filepaths contains something that looks like an input, and all do.

When I run

```
smallbaselineApp.py Parameters.txt --dostep load_data
```

I get the error message:

```
--RUN-at-2020-08-30 12:56:09.219238--
Current directory: /u/sar-r2/rzinke/Xizang/Tr12/stack20200718_20200823/7_19Looks_3Lags/Mintpy_std
Run routine processing with smallbaselineApp.py on steps: ['load_data', 'modify_network', 'reference_point', 'quick_overview', 'correct_unwrap_error', 'invert_network', 'correct_LOD', 'correct_troposphere', 'deramp', 'correct_topography', 'residual_RMS', 'reference_date', 'velocity', 'geocode', 'google_earth', 'hdfeos5']
Remaining steps: ['modify_network', 'reference_point', 'quick_overview', 'correct_unwrap_error', 'invert_network', 'correct_LOD', 'correct_troposphere', 'deramp', 'correct_topography', 'residual_RMS', 'reference_date', 'velocity', 'geocode', 'google_earth', 'hdfeos5']
--------------------------------------------------
Project name: Parameters
Go to work directory: /u/sar-r2/rzinke/Xizang/Tr12/stack20200718_20200823/7_19Looks_3Lags/Mintpy_std
read custom template file: /u/sar-r2/rzinke/Xizang/Tr12/stack20200718_20200823/7_19Looks_3Lags/Mintpy_std/Parameters.txt
update default template based on input custom template
No new option value found, skip updating /u/sar-r2/rzinke/Xizang/Tr12/stack20200718_20200823/7_19Looks_3Lags/Mintpy_std/smallbaselineApp.cfg
read default template file: /u/sar-r2/rzinke/Xizang/Tr12/stack20200718_20200823/7_19Looks_3Lags/Mintpy_std/smallbaselineApp.cfg


******************** step - load_data ********************
load_data.py --template /u/sar-r2/rzinke/Xizang/Tr12/stack20200718_20200823/7_19Looks_3Lags/Mintpy_std/smallbaselineApp.cfg /u/sar-r2/rzinke/Xizang/Tr12/stack20200718_20200823/7_19Looks_3Lags/Mintpy_std/Parameters.txt --project Parameters
processor : isce
SAR platform/sensor : unknown from project name "Parameters"
--------------------------------------------------
prepare metadata files for isce products
prep_isce.py -m ../master/IW2.xml -g ../merged/geom_master -b ../baselines -d ../merged/interferograms -f filt_*.unw
extract metadata from ISCE/topsStack xml file: ../master/IW2.xml
--------------------------------------------------
searching interferometric pairs info
input data files:
unwrapPhase     : ../merged/interferograms/*/filt_*.unw
coherence       : ../merged/interferograms/*/filt_*.cor
connectComponent: ../merged/interferograms/*/filt_*.unw.conncomp
number of unwrapPhase     : 6
number of coherence       : 6
number of connectComponent: 6
Traceback (most recent call last):
  File "/u/sarh0/rzinke/tools/MintPy/mintpy/smallbaselineApp.py", line 1116, in <module>
    main()
  File "/u/sarh0/rzinke/tools/MintPy/mintpy/smallbaselineApp.py", line 1106, in main
    app.run(steps=inps.runSteps, plot=inps.plot)
  File "/u/sarh0/rzinke/tools/MintPy/mintpy/smallbaselineApp.py", line 1035, in run
    self.run_load_data(sname)
  File "/u/sarh0/rzinke/tools/MintPy/mintpy/smallbaselineApp.py", line 363, in run_load_data
    mintpy.load_data.main(iargs)
  File "/u/sarh0/rzinke/tools/MintPy/mintpy/load_data.py", line 655, in main
    stackObj = read_inps_dict2ifgram_stack_dict_object(inpsDict)
  File "/u/sarh0/rzinke/tools/MintPy/mintpy/load_data.py", line 400, in read_inps_dict2ifgram_stack_dict_object
    date12 = readfile.read_attribute(dsPath)['DATE12'].replace('_','-')
KeyError: 'DATE12'
```

**System information**

* Operating system: MacOS Mojave
* Python environment: MintPy, Python = 3.8
* Version of MintPy: MintPy release version v1.2.3-28, release date 2020-08-27
* Your custom / default template file (if the bug is related to a specific dataset): See attached
[Parameters.txt](https://github.com/insarlab/MintPy/files/5147380/Parameters.txt)

**Comment by mirzaees** [comment]
Hi @rzinke , it is probably from not reading metadata correctly, there was a fix for this recently, have you updated?

**Comment by rzinke** [comment]
Hi @mirzaees, I updated my MintPy repo this morning (to insarlab/Main).
I am using an older version of ISCE (2.3.2), could that have to do with it?

Thanks

**Comment by yunjunz** [comment]
Hi @rzinke, I think isce v2.3.2 should be fine. Could you:

+ post one of the `filt_fine.unw.rsc` file if it exsits?
+ run the `prep_isce.py` call in the command line to how it goes?

**Comment by rzinke** [comment]
Hi @yunjunz and @mirzaees, it appears this was the result of a user error. I'd forgotten to run the prep_isce.py script in advance. 
It appears to be working now as expected.
Thanks for the assistance.

**Comment by yunjunz** [comment]
prep_isce.py should have been called by smallbaselineApp.py, but isce is required to be installed for it. Is this the reason?

**Comment by rzinke** [comment]
I have ISCE and MintPy installed in separate conda environments. 
As I recall, the first time I ran smallbaselineApp.py I was using the MintPy environment. 
When I ran prep_isce.py just now, I was using the ISCE environment.

**Comment by yunjunz** [comment]
Right, this makes sense.

**Comment by guangbaoshen** [comment]
Hi@yunjunz ,I have met exactly the same error with @rzinke(keyError:DATA12). However, when I activate the isce environment and try to run the prep_isce.py scripts. A new error comes out as below:

Traceback (most recent call last):
 file "/home/guangbao/python/Mintpy/mintpy/prep_isce.py", line 14, in <module>
 from mintpy.utils import (
File "/home/guangbao/python/Mintpy/mintpy/utils/readfile.py", line 13 , in <module>
 import defusedxml.ElementTree as ET
 ModuleNotFoundError: No module named 'defusedxml'

 In Ubuntu 18.04 system, I use the isce v2.5.1 and python 3.6, and I am new to ISCE and Mintpy. 
All your help will be appreciated, thank you very much!

**Comment by yunjunz** [comment]
Hi @guangbaoshen, you need to install defusedxml in your python environment.

**Comment by guangbaoshen** [comment]
@yunjunz Thank you very much, and after installing defusexml module, mintpy works. Thank you for your reply.
