### ISSUE TITLE
residual_RMS step failing

### ISSUE THREAD

**Issue by EJFielding** [insarlab/MintPy#435]
**Description of the problem**

I added some more scenes to a stack processed with ISCE2 topsStack and tried to run the full `smallbaselineApp` on it. The processing went well until it reached the `residual_RMS` step, which failed with a `Segmentation fault`. Re-running that step gives the same error. Previous runs of this stack had no problems.

**Full script that generated the error**

```
smallbaselineApp.py PuertoRicoSenA135.txt --start=residual_RMS
```

**Full error message**

```
          MintPy v1.2.3-30, 2020-09-03
_________________________________________________

--RUN-at-2020-09-03 23:19:46.633647--
Current directory: /u/sar-r2/fielding/Puerto_Rico/S1AB/A135/seismic/MintPy_v6
Run routine processing with smallbaselineApp.py on steps: ['residual_RMS', 'reference_date', 'velocity', 'geocode', 'google_earth', 'hdfeos5']
Remaining steps: ['reference_date', 'velocity', 'geocode', 'google_earth', 'hdfeos5']
--------------------------------------------------
Project name: PuertoRicoSenA135
Go to work directory: /u/sar-r2/fielding/Puerto_Rico/S1AB/A135/seismic/MintPy_v6
read custom template file: /u/sar-r2/fielding/Puerto_Rico/S1AB/A135/seismic/MintPy_v6/PuertoRicoSenA135.txt
update default template based on input custom template
No new option value found, skip updating /u/sar-r2/fielding/Puerto_Rico/S1AB/A135/seismic/MintPy_v6/smallbaselineApp.cfg
read default template file: /u/sar-r2/fielding/Puerto_Rico/S1AB/A135/seismic/MintPy_v6/smallbaselineApp.cfg


******************** step - residual_RMS ********************
timeseries_rms.py timeseriesResidual.h5 -t /u/sar-r2/fielding/Puerto_Rico/S1AB/A135/seismic/MintPy_v6/smallbaselineApp.cfg
read options from template file: smallbaselineApp.cfg
remove quadratic ramp from file: timeseriesResidual.h5
read mask file: maskTempCoh.h5
reading data ...
estimating phase ramp ...
Segmentation fault (core dumped)
```

**System information**

* Operating system: Linux-CentOS 
* Python environment: conda
* Version of MintPy: MintPy v1.2.3-30, 2020-09-03
* Your custom / default template file (if the bug is related to a specific dataset): 
[PuertoRicoSenA135.txt](https://github.com/insarlab/MintPy/files/5173196/PuertoRicoSenA135.txt)

**Comment by EJFielding** [comment]
In case it helps, I ran the plotting script and here is the timeseries output plot.
![timeseries_wrap20 0](https://user-images.githubusercontent.com/7253576/92209833-85e74580-ee42-11ea-8e67-7de9051a032c.png)

**Comment by yunjunz** [comment]
Hi @EJFielding, I believe this is a memory issue. We are working on a fix for a few limited steps, including `residual_RMS` in `smallbaselineApp.py` and hope to be able to commit it in the coming week. Another big memory eater is `geocode`, which is not included in our working list above, and I won't be surprised if your processing failed at that step even after this fix.

Alternatively, you might want to try cropping using `mintpy.subset.lalo/yx` in mintpy or more looks in topsStack.

**Comment by EJFielding** [comment]
Hi @yunjunz, thanks for the suggestions about memory issues. I am already using a subset of only 800 by 1200 pixels in MintPy, which does not seem so large with 129 interferograms and 34 dates.

**Comment by yunjunz** [comment]
Hmm, this small size could not cause memory issues. If you could send me your data (timeseriesResidual.h5 and maskTempCoh.h5), I could take a deeper look.

**Comment by EJFielding** [comment]
Thanks for the off-line help. As you suggested, I cloned a new copy of MintPy and that fixed the problem.
