### ISSUE TITLE
plot & save to pic-error

### ISSUE THREAD

**Issue by ReemAlshammari** [insarlab/MintPy#442]
The error is related to the latest updated version , it was working good before . 
The only change I made was within deramp step  "mintpy.deramp= linear", I'm not sure if it's cause the error or not.
**Full script that generated the error**

```
!smallbaselineApp.py
```

**Full error message**

```
******************** plot & save to pic ********************
./plot_smallbaselineApp.sh
Traceback (most recent call last):
  File "/MintPy/mintpy/view.py", line 1485, in <module>
    main(sys.argv[1:])
  File "/MintPy/mintpy/view.py", line 1479, in main
    obj.plot()
  File "/MintPy/mintpy/view.py", line 1459, in plot
    plot_figure(j, self, metadata=self.atr)
  File "/MintPy/mintpy/view.py", line 1153, in plot_figure
    data = read_data4figure(i_start, i_end, inps, metadata)
  File "/MintPy/mintpy/view.py", line 963, in read_data4figure
    ystep=inps.multilook_num)[0]
TypeError: read() got an unexpected keyword argument 'xstep'
Traceback (most recent call last):
```

**System information**

* Operating system: macOS 
* Python environment:  conda
* Version of MintPy: MintPy v1.2.3, 2020-07-14

**Comment by yunjunz** [comment]
Hi @ReemAlshammari, `readfile.read(x/ystep)` is introduced after the release of v1.2.3. It seems like you have multiple versions of mintpy that led to this error.

**Comment by ReemAlshammari** [comment]
Thanks Yunjunz. 
I have the latest files from the githup here:
https://github.com/insarlab/MintPy
It has the same version number since v1.2.3

**Comment by yunjunz** [comment]
It might be the master --> main default branch change. But your codebase is not the latest.

FYI, mine looks like below:
```
(base) yunjunz:~>$ smallbaselineApp.py -v
MintPy release version v1.2.3-39, release date 2020-09-15
```

**Comment by ReemAlshammari** [comment]
Thank you @yunjunz, the issue was because I have two different versions! 
Now , I'm sure it's the latest and there is no error, but the version number is still "MintPy release version v1.2.3, release date 2020-07-14": https://github.com/insarlab/MintPy/blob/main/mintpy/version.py
