### ISSUE TITLE
timeseries2velocity.py with --step writes some corrupted output layers

### ISSUE THREAD

**Issue by EJFielding** [insarlab/MintPy#454]
**Description of the problem**

I ran the new `timeseries2velocity.py` version that includes the step-function fit, and it ran successfully but it wrote out the step layer and the velocity error with some corruption in the `velocity.h5` output. The step and velocity standard deviation layers are correct, so it seems to be only in the file writing, not the computation. I don't see any similar errors in the original `timeseries.h5` file.

**Full script that generated the error**

```
timeseries2velocity.py timeseries.h5 --step 20200107
```

**Full error message**

There is no error reported, but I paste the output here for diagnosis.

```
Using default MintPy Path: /home/fielding/tools/MintPy
open timeseries file: timeseries.h5
--------------------------------------------------
dates from input file: 35
['20190718', '20190730', '20190811', '20190823', '20190904', '20190916', '20190928', '20191010', '20191022', '20191103', '20191115', '20191127', '20191209', '20191221', '20200102', '20200114', '20200126', '20200207', '20200219', '20200302', '20200314', '20200326', '20200407', '20200419', '20200501', '20200513', '20200525', '20200606', '20200618', '20200630', '20200712', '20200724', '20200805', '20200817', '20200910']
--------------------------------------------------
using all dates to calculate the velocity
--------------------------------------------------
reading data from file timeseries.h5 ...
skip pixels with zero/nan value in all acquisitions
estimate deformation model with the following assumed time functions:
polynomial : 1
periodic   : []
step       : ['20200107']
add/update the following configuration metadata:
['startDate', 'endDate', 'excludeDate', 'bootstrap', 'bootstrapCount']
open file: velocity.h5 with "w" mode
create dataset /velocity             of <class 'numpy.float32'>   in size of (830, 1319)  with compression=None
create dataset /velocityStd          of <class 'numpy.float32'>   in size of (830, 1319)  with compression=None
create dataset /step20200107         of <class 'numpy.float32'>   in size of (830, 1319)  with compression=None
create dataset /step20200107Std      of <class 'numpy.float32'>   in size of (830, 1319)  with compression=None
finished writing to file: velocity.h5
```
This is the `view.py velocity.h5 --save` output.
![velocity](https://user-images.githubusercontent.com/7253576/95029181-50a95f80-065b-11eb-8156-014aea262a11.png)
Similarly, the bad patch is still there after geocoding.
![geo_velocity](https://user-images.githubusercontent.com/7253576/95029214-759dd280-065b-11eb-8339-3048827739ea.png)

**System information**

* Operating system:  Linux-CentOS
* Python environment:  conda
* Version of MintPy: 
Using default MintPy Path: /home/fielding/tools/MintPy
MintPy release version v1.2.3-49, release date 2020-10-01

* Your custom / default template file (if the bug is related to a specific dataset): 

[PuertoRicoSenD098.txt](https://github.com/insarlab/MintPy/files/5324587/PuertoRicoSenD098.txt)

**Comment by yunjunz** [comment]
Hi @EJFielding, the current `timeseries2velocity.py` is reading/inverting/writing all pixels at once, so I cannot recall any part wrong in the code. To help diagnose, could you plot the time-series of one pixel in the horizontal strike? 

If you could send me your timeseries.h5 and maskTempCoh.h5 file, I could take a deeper look.

**Comment by EJFielding** [comment]
I ran the same command on another version of the same timeseries and it worked fine. Maybe there is some subtle problem with my `timeseries.h5` file. I copied them over to your computer. I will send an email with details.

**Comment by EJFielding** [comment]
Here is a time series plot from the `timeseries.h5` from a point inside the bad stripe. Looks normal to me.
<img width="737" alt="timeseries-bad-stripe" src="https://user-images.githubusercontent.com/7253576/95035683-b2c58d00-067a-11eb-9daf-ea988a66b117.png">

**Comment by EJFielding** [comment]
I ran the same script on the same data using the Red Hat computer at Caltech. It does not have the strange stripe. Maybe this is a problem with one of the subroutine library versions I have on our CentOS machine.

**Comment by yunjunz** [comment]
Same here @EJFielding: velocity.h5 looks normal without the stripe while running on kamb.

I am not sure of the reason for your original issue, maybe try an independent conda environment for mintpy?

**Comment by EJFielding** [comment]
I had the same bad stripe problem for another timeseries on the same CentOS machine. I have been using an independent conda environment for MintPy, but I guess it had a bad version of some library. I did not investigate all the library versions or try to update them. I removed the environment and made a new one. Now the same command works perfectly. 
Problem solved.
