### ISSUE TITLE
asc_desc2horz_vert.py only uses first dataset of input files

### ISSUE THREAD

**Issue by EJFielding** [insarlab/MintPy#456]
**Description of the problem**

The `asc_desc2horz_vert.py` script reads the first dataset of the two input files and assumes that it is `velocity`. The new version of `timeseries2velocity.py` includes the option to do a fit to a timeseries using multiple basis components and writing a number of datasets into the output `velocity.h5` file. The new components are now stored before `velocity` in the `velocity.h5` file so the first dataset is no longer velocity. The present implementation of `asc_desc2horz_vert.py` does not check the name of the dataset it is reading and it provides no way to use a component other than the first dataset.

**Full script that generated the error**

```
asc_desc2horz_vert.py A135_geo_velocity_v6a_subset.h5 D098_geo_velocity_v3a_subset.h5
```

**Full error message**

```
Using default MintPy Path: /home/fielding/tools/MintPy
---------------------
reading A135_geo_velocity_v6a_subset.h5
reading D098_geo_velocity_v3a_subset.h5
---------------------
get design matrix
incidence angle: 38.95743031204843
heading angle: 349.125244140625
incidence angle: 33.72858887716663
heading angle: 192.2511058816865
project asc/desc into horz/vert direction
---------------------
writing horizontal component to file: hz.h5
create HDF5 file: hz.h5 with w mode
create dataset /velocity of float32    in size of (614, 1072)          with compression=None
finished writing to hz.h5
writing   vertical component to file: up.h5
create HDF5 file: up.h5 with w mode
create dataset /velocity of float32    in size of (614, 1072)          with compression=None
finished writing to up.h5

```

but the input file has many datasets:
```
info.py D098_geo_velocity_v3a_subset.h5
...
HDF5 dataset "/step20200107        ": shape (614, 1072)         , dtype <float32>
HDF5 dataset "/step20200107Std     ": shape (614, 1072)         , dtype <float32>
HDF5 dataset "/step20200502        ": shape (614, 1072)         , dtype <float32>
HDF5 dataset "/step20200502Std     ": shape (614, 1072)         , dtype <float32>
HDF5 dataset "/step20200703        ": shape (614, 1072)         , dtype <float32>
HDF5 dataset "/step20200703Std     ": shape (614, 1072)         , dtype <float32>
HDF5 dataset "/velocity            ": shape (614, 1072)         , dtype <float32>
HDF5 dataset "/velocityStd         ": shape (614, 1072)         , dtype <float32>
```

I guess I could make four copies of the `velocity.h5` file and then remove all the datasets but the one I want to use in the  `asc_desc2horz_vert` program, but that seems like a painful workaround.

**System information**

* Operating system: Linux-CentOS
* Python environment: conda
* Version of MintPy:  Using default MintPy Path: /home/fielding/tools/MintPy
MintPy release version v1.2.3-49, release date 2020-10-01
* Your custom / default template file (if the bug is related to a specific dataset):

**Comment by yunjunz** [comment]
Hi @EJFielding, the above commit should allow a customized dataset to vert/horz projection, i.e. "velocity" or "step20200107". Could you confirm whether it works for your dataset? Then I will go ahead to merge it.

**Comment by EJFielding** [comment]
Yes, this works perfectly. Thanks!
