### ISSUE TITLE
Geocoded maskTemCoh for UAVSAR data has gaps

### ISSUE THREAD

**Issue by EJFielding** [insarlab/MintPy#466]
**Description of the problem**

The geocoded temporal coherence mask `geo_maskTempCoh.h5` has small gaps that are not present in the ungeocoded mask or the geocoded temporal coherence image. This seems to be due to the way geocoding is done.
Here is the mask
![15302-s1 MaskTempCoh BerkeleyHills ](https://user-images.githubusercontent.com/7253576/97235995-5e0cc200-17a1-11eb-9f68-ae73e396d93d.png)
Here is the geocoded temporal coherence
![15302-s1 TempCoherence BerkeleyHills](https://user-images.githubusercontent.com/7253576/97236125-a75d1180-17a1-11eb-95c0-9eb9700759f5.png)

**Full script that generated the error**

I ran the whole smallbaselineApp including the geocoding step. Then I ran 
```
save_gmt.py geo_maskTempCoh.h5
```
Final plots were from QGIS.

**Full error message**

```
no error message
```

**System information**

* Operating system:  Linux-CentOS
* Python environment:  conda
* Version of MintPy:  MintPy release version v1.2.3-63, release date 2020-10-21
* Your custom / default template file (if the bug is related to a specific dataset): 
[Haywrd_15302_03-s1.txt](https://github.com/insarlab/MintPy/files/5441925/Haywrd_15302_03-s1.txt)

**Comment by yunjunz** [comment]
`maskTempCoh.h5` file uses info from temporal coherence, water mask and shadow mask. To further confirm the issue, @EJFielding could you plot/show the following files with view.py?

+ inputs/geometryRadar.h5 shadowMask
+ inputs/geometryRadar.h5 waterMask
+ temporalCoherence.h5
+ maskTempCoh.h5
+ geo/geo_maskTempCoh.h5

**Comment by EJFielding** [comment]
shadowMask
![shadowMask](https://user-images.githubusercontent.com/7253576/97241850-87344f00-17af-11eb-8723-ecf65293e530.png)
waterMask
![waterMask](https://user-images.githubusercontent.com/7253576/97241864-90252080-17af-11eb-9a59-1d9e4000ddef.png)
temporal coherence
![temporalCoherence](https://user-images.githubusercontent.com/7253576/97241881-9f0bd300-17af-11eb-966d-423c6fb8ed4c.png)
maskTempCoh
![maskTempCoh](https://user-images.githubusercontent.com/7253576/97241912-acc15880-17af-11eb-9f6c-1f08dab91f92.png)
geo_maskTempCoh
![geo_maskTempCoh](https://user-images.githubusercontent.com/7253576/97241928-b64ac080-17af-11eb-8ace-389efa49bb94.png)

**Comment by EJFielding** [comment]
Maybe it is coming from the shadowMask.

**Comment by yunjunz** [comment]
I agree. 

The following option can be used to not use the shadow mask info while generating `maskTempCoh.h5`.

```
mintpy.networkInversion.shadowMask  = auto #[yes / no], auto for yes [if shadowMask is in geometry file] or no.
```

**Comment by EJFielding** [comment]
Thanks. That helps. I will close this as it is not a MintPy problem.
