### ISSUE TITLE
Memory error for very large data set -- revisit

### ISSUE THREAD

**Issue by rzinke** [insarlab/MintPy#473]
**Description of the problem**
I am getting a Segmentation Fault when computing the velocity field for a large data set (445 x 3223 x 1394). The timeseries (which is tiled) computes fine. Then, the process fails every time at the velocity computation step.

**Full script that generated the error**
```
smallbaselineApp.py Parameters.txt --start=velocity
```

**Full error message**
```
******************** step - velocity ********************
timeseries2velocity.py timeseries.h5 -t /u/sar-r2/rzinke/Tibet/T41_FullTrack_aria/41_OG_Tibet/ML5/smallbaselineApp.cfg -o velocity.h5 --update
open timeseries file: timeseries.h5
read option from template file: /u/sar-r2/rzinke/Tibet/T41_FullTrack_aria/41_OG_Tibet/ML5/smallbaselineApp.cfg
read options from template file: smallbaselineApp.cfg
--------------------------------------------------
dates from input file: 136
['20141020', '20141113', '20141207', '20141231', '20150124', '20150217', '20150301', '20150325', '20150512', '20150605', '20150629', '20150723', '20150816', '20150909', '20151003', '20151027', '20151120', '20151214', '20160107', '20160131', '20160224', '20160319', '20160412', '20160506', '20160530', '20160717', '20160810', '20160903', '20160927', '20161021', '20161114', '20161208', '20170101', '20170125', '20170206', '20170218', '20170302', '20170314', '20170326', '20170407', '20170419', '20170501', '20170513', '20170525', '20170606', '20170618', '20170630', '20170712', '20170724', '20170805', '20170817', '20170829', '20170910', '20171004', '20171016', '20171028', '20171109', '20171121', '20171203', '20171215', '20171227', '20180108', '20180120', '20180201', '20180213', '20180225', '20180321', '20180402', '20180414', '20180426', '20180508', '20180601', '20180613', '20180625', '20180707', '20180719', '20180731', '20180812', '20180824', '20180905', '20180917', '20180929', '20181011', '20181023', '20181104', '20181116', '20181128', '20181210', '20181222', '20190103', '20190115', '20190127', '20190208', '20190220', '20190304', '20190316', '20190328', '20190409', '20190421', '20190503', '20190515', '20190527', '20190608', '20190620', '20190702', '20190714', '20190726', '20190819', '20190831', '20190912', '20190924', '20191006', '20191018', '20191030', '20191111', '20191123', '20191205', '20191217', '20191229', '20200110', '20200122', '20200203', '20200215', '20200227', '20200310', '20200322', '20200403', '20200415', '20200427', '20200509', '20200521', '20200602', '20200614', '20200626', '20200708', '20200720']
--------------------------------------------------
using all dates to calculate the velocity
--------------------------------------------------
update mode: ON
1) output file velocity.h5 NOT found.
run or skip: run.
reading data from file timeseries.h5 ...
skip pixels with zero/nan value in all acquisitions
estimate deformation model with the following assumed time functions:
polynomial : 1
periodic   : []
step       : []
Segmentation fault (core dumped)
```

**System information**

* Operating system: Linux-CentOS, 32 core, 125 Gb mem (85 Gb available at start of processing)
* Python environment: conda
* Version of MintPy: MintPy release version v1.2.3-49, release date 2020-10-01

**Comment by yunjunz** [comment]
Hi @rzinke, based on the info, your time-series file is ~2.3 GB, which does not seem big, I would be very surprised if this script took >85 GB of memory. Could you confirm it via `htop`?

Another potential cause could be due to some limitations on the local cluster that limits the max memory a single program could use. If this is the case, I would recommend trying this script alone (`timeseries2velocity.py timeseries.h5 smallbaselineApp.cfg -o velocity.h5`) on your laptop (copy the `timeseries.h5` and `smallbaselineApp.cfg file`). I have a time-series file of 18 GB, and it runs fine on my laptop (with 16 GB memory).

**Comment by rzinke** [comment]
Hmm. Yes. ```timeseries.h5``` is only 2.5 Gb. I ran ```timeseries2velocity.py timeseries.h5 --template Parameters.txt -o velocity.h5``` on my laptop and it produced the result in a few seconds.

Do you know a way to increase the memory per job on a typical Linux server?

**Comment by yunjunz** [comment]
> Do you know a way to increase the memory per job on a typical Linux server?

I don't know, I would recommend asking the system manager.

**Comment by yunjunz** [comment]
#216

**Comment by yunjunz** [comment]
This should now be resolved in the PR above.
