### ISSUE TITLE
No data value recognition for match.py

### ISSUE THREAD

**Issue by rzinke** [insarlab/MintPy#475]
**Description of the desired feature**
When I use ```match.py``` the zero-values representing no data are included as non-zero values in the output. It would be helpful to have some way of telling ```match.py``` which values to ignore.

E.g., 
```match.py avgSpatialCoh1.h5 avgSpatialCoh2.h5 -m 0.0 -o avgSpatialCohCombo.h5```

**Current problems**
The current implementation of ```match.py``` introduces additional fields with "data" values, as shown below for two avgSpatialCoh maps.

![Screen Shot 2020-11-16 at 1 21 58 PM](https://user-images.githubusercontent.com/48299159/99311016-be2add00-2810-11eb-8ec4-7a3635ed7c89.png)

**Are you willing to help implement and maintain this feature?**
Yes, if possible.

**Comment by rzinke** [comment]
I have tried masking the zero values using ```mask.py```.  E.g.,
```mask.py velocity.h5 -m maskTempCoh.h5 -o velocityMasked.h5```

but this fails for other data sets, e.g., 
```mask.py avgSpatialCoh.h5 -m maskTempCoh.h5 -o avgSpatialCohMasked.h5```

returns the error: 
```
Traceback (most recent call last):
  File "/u/sarh0/rzinke/tools/MintPy/mintpy/mask.py", line 244, in <module>
    main(sys.argv[1:])
  File "/u/sarh0/rzinke/tools/MintPy/mintpy/mask.py", line 236, in main
    mask_file(inps.file, inps.mask_file, inps.outfile, inps)
  File "/u/sarh0/rzinke/tools/MintPy/mintpy/mask.py", line 138, in mask_file
    dsDict[dsName] = data
UnboundLocalError: local variable 'data' referenced before assignment
```

I should mention that I am using ARIA data.

**Comment by yunjunz** [comment]
Hi @rzinke, your solution of running `mask.py` before `match.py` sounds good to me. The error in the mask.py is caused by [mask.py#L128](https://github.com/insarlab/MintPy/blob/main/mintpy/mask.py#L128), which seems unnecessary. Removing it should work. Could you confirm? If yes, please feel free to issue a PR.

**Comment by rzinke** [comment]
Hi @yunjunz, did you mean mask.py#L138? Line 128 is a block of code behind an ```if``` statement:

```
    for dsName in dsNames:
        if dsName not in ['coherence']:
            print('masking {d:<{w}} from {f} ...'.format(d=dsName, w=maxDigit, f=fname))
            data = readfile.read(fname, datasetName=dsName, print_msg=False)[0]

            # keep timeseries data as 3D matrix when there is only one acquisition
            # because readfile.read() will squeeze it to 2D
            if atr['FILE_TYPE'] == 'timeseries' and len(data.shape) == 2:
                data = np.reshape(data, (1, data.shape[0], data.shape[1]))

            data = mask_matrix(data, mask, fill_value=inps.fill_value)
        dsDict[dsName] = data
```

Commenting out lines 128-137 gives the same error:
```
Traceback (most recent call last):
  File "/u/sarh0/rzinke/tools/MintPy/mintpy/mask.py", line 244, in <module>
    main(sys.argv[1:])
  File "/u/sarh0/rzinke/tools/MintPy/mintpy/mask.py", line 236, in main
    mask_file(inps.file, inps.mask_file, inps.outfile, inps)
  File "/u/sarh0/rzinke/tools/MintPy/mintpy/mask.py", line 138, in mask_file
    dsDict[dsName] = data
NameError: name 'data' is not defined
```

Leaving lines 128-137 but commenting out line 138 gives a different error:
```
(MintPy) [rzinke@sar ML3_ERA5_topo_PxMsk]$ mask.py 121_A_maskTempCoh.h5 -m 121_A_maskTempCoh.h5 -o 121_A_maskTempCohMasked.h5
masking mask from 121_A_maskTempCoh.h5 ...
in order to fill the invalid pixels with np.nan
	convert input matrix from bool to np.float32
create HDF5 file: 121_A_maskTempCohMasked.h5 with w mode
Traceback (most recent call last):
  File "/u/sarh0/rzinke/tools/MintPy/mintpy/mask.py", line 244, in <module>
    main(sys.argv[1:])
  File "/u/sarh0/rzinke/tools/MintPy/mintpy/mask.py", line 236, in main
    mask_file(inps.file, inps.mask_file, inps.outfile, inps)
  File "/u/sarh0/rzinke/tools/MintPy/mintpy/mask.py", line 145, in mask_file
    writefile.write(dsDict, out_file=out_file, ref_file=fname)
  File "/u/sarh0/rzinke/tools/MintPy/mintpy/utils/writefile.py", line 80, in write
    maxDigit = max([len(i) for i in dsNames])
ValueError: max() arg is an empty sequence
```

**Comment by yunjunz** [comment]
I meant changing lines 128-137 from

```python
        if dsName not in ['coherence']:
            print('masking {d:<{w}} from {f} ...'.format(d=dsName, w=maxDigit, f=fname))
            data = readfile.read(fname, datasetName=dsName, print_msg=False)[0]
            
            # keep timeseries data as 3D matrix when there is only one acquisition
            # because readfile.read() will squeeze it to 2D
            if atr['FILE_TYPE'] == 'timeseries' and len(data.shape) == 2:
                data = np.reshape(data, (1, data.shape[0], data.shape[1]))

            data = mask_matrix(data, mask, fill_value=inps.fill_value)
```

to 

```python
        print('masking {d:<{w}} from {f} ...'.format(d=dsName, w=maxDigit, f=fname))
        data = readfile.read(fname, datasetName=dsName, print_msg=False)[0]

        # keep timeseries data as 3D matrix when there is only one acquisition
        # because readfile.read() will squeeze it to 2D
        if atr['FILE_TYPE'] == 'timeseries' and len(data.shape) == 2:
            data = np.reshape(data, (1, data.shape[0], data.shape[1]))

        data = mask_matrix(data, mask, fill_value=inps.fill_value)
```

**Comment by yunjunz** [comment]
`match.py` was designed for the relative phase/velocity, thus, besides the mosaic, it estimates an offset between the two input files and applies this offset to the 2nd file at [L212](https://github.com/insarlab/MintPy/blob/main/mintpy/match.py#L212), you should turn it off (comment out this line) for your purpose. 

A more flexible solution would be adding a new argument, i.e. --no-offset, and pass it to this line as an `if` judgement.

**Comment by rzinke** [comment]
Good idea. I have made the addition #477 and tested it out. 
Let me know if you have any questions!
