### ISSUE TITLE
IndexError: list index out of range--At first step: load_data

### ISSUE THREAD

**Issue by Hikersp** [insarlab/MintPy#484]
I used isce2=2.3.3 to produce a stack of ifgrams and then post-processed them in mintpy. But unluckily, an index error occured when performing 1st step load_data. I tested mintpy with the example dataset and it passed. Does anyone kindly give me hand?
My operating system: CentOS Linux release 7.6.1810 (Core)

Here are detailed error and output messages:
```bash
Traceback (most recent call last):
  File "/public/home/zzusaa02/tools/MintPy/mintpy/smallbaselineApp.py", line 1116, in <module>
    main()
  File "/public/home/zzusaa02/tools/MintPy/mintpy/smallbaselineApp.py", line 1104, in main
    app.startup()
  File "/public/home/zzusaa02/tools/MintPy/mintpy/smallbaselineApp.py", line 235, in startup
    self._read_template()
  File "/public/home/zzusaa02/tools/MintPy/mintpy/smallbaselineApp.py", line 301, in _read_template
    self.templateFile = ut.update_template_file(self.templateFile, self.customTemplate)
  File "/public/home/zzusaa02/tools/MintPy/mintpy/utils/utils1.py", line 502, in update_template_file
    old_value_str = re.findall(delimiter+'[\s]*'+value, line)[0]
IndexError: list index out of range

SLURM_JOB_PARTITION=normal”
“SLURM_JOB_NODELIST=a03r2n15”
MintPy release version v1.2.3-73, release date 2020-11-16
--RUN-at-2020-12-01 21:27:37.329753--
Current directory: /public/home/zzusaa02/SBAS_labs/keke4/mintpy
Run routine processing with smallbaselineApp.py on steps: ['load_data']
Remaining steps: ['modify_network', 'reference_point', 'quick_overview', 'correct_unwrap_error', 'invert_network', 'correct_LOD', 'correct_troposphere', 'deramp', 'correct_topography', 'residual_RMS', 'reference_date', 'velocity', 'geocode', 'google_earth', 'hdfeos5']
--------------------------------------------------
Project name: keke4
Go to work directory: /public/home/zzusaa02/SBAS_labs/keke4/mintpy
read custom template file: /public/home/zzusaa02/SBAS_labs/keke4/mintpy/inputs/keke4.txt
update default template based on input custom template
```

Here are parameters of mintpy:
```cfg
##-------------------------------- MintPy -----------------------------##
########## 1. Load Data (--load to exit after this step)
## load_data.py -H to check more details and example inputs.
mintpy.load.processor        = isce
##---------for ISCE only:
mintpy.load.metaFile         = ../master/IW*.xml
mintpy.load.baselineDir      = ../baselines
##---------interferogram datasets:
mintpy.load.unwFile          = ../merged/interferograms/*/filt_*.unw
mintpy.load.corFile          = ../merged/interferograms/*/filt_*.cor
mintpy.load.connCompFile     = ../merged/interferograms/*/filt_*.unw.conncomp
##---------geometry datasets:
mintpy.load.demFile          = ../merged/geom_master/hgt.rdr
mintpy.load.lookupYFile      = ../merged/geom_master/lat.rdr
mintpy.load.lookupXFile      = ../merged/geom_master/lon.rdr
mintpy.load.incAngleFile     = ../merged/geom_master/los.rdr
mintpy.load.azAngleFile      = ../merged/geom_master/los.rdr
mintpy.load.shadowMaskFile   = ../merged/geom_master/shadowMask.rdr
mintpy.load.waterMaskFile    = None

mintpy.deramp                = linear
```

**Comment by yunjunz** [comment]
Your code installation should be fine since the example dataset passed. Could you show your data/directory structure here? It might be a path issue. 

I would also recommend to try it again with the absolute path, relative path is always tricky and needs extra care.

**Comment by Hikersp** [comment]
> Your code installation should be fine since the example dataset passed. Could you show your data/directory structure here? It might be a path issue.
> 
> I would also recommend to try it again with the absolute path, relative path is always tricky and needs extra care.

Hello, yunjunz. Here is my data/directory structure.
![image](https://user-images.githubusercontent.com/33457102/101158613-f7fc4000-3666-11eb-8edd-b2bf1745d8d8.png)

I followed your advice and then set the absolute path to corresponding parameters, but it came out the same IndexError. I also configure a neat data/directory structure like the example dataset, but the IndexError came again.

**Comment by yunjunz** [comment]
I am suspicious that this index error is not the first error you have since the beginning of isce stack processing, not sure where though since the non-first error message is not really informative.

My recommendation would be: compare your detailed file structure against the Fernandina example dataset, and check the detailed output and/or error message from the stack processing.

**Comment by Hikersp** [comment]
Thank you, sir. I found difference between Fernandian dataset and mine at directory merged/geo_reference(master). We could see that my processing results lacked of several xml files compared to example dataset shown in the below picture.
![image](https://user-images.githubusercontent.com/33457102/101909219-24c8ce00-3bf8-11eb-8493-514a7277007a.png)

By the way, one of my friends got the same files compared with mine and he post-processed with his mintpy successufully.
I think it is versions of isce2 that result in this differnce. In order to test MintPy, at this time I processed 3 S-1A slcs with isce2=2.4.1 in my laptop with ubuntu18.04 which is newly reinstalled and the version of mintpy installed with conda is 1.2.3. I tested mintpy with Fernandian dataset and it passed, too. But I encountered the same Index error when setting absolute path in input txt files. I tried relative path and then I got an KeyError. Here are the infomations of this new bug.
![image](https://user-images.githubusercontent.com/33457102/101911911-01a01d80-3bfc-11eb-85c1-e54b5ff756f8.png)

The message underlain by red line in the picture attracted my attention and reminded me of checking the contents of IW1.xml file. I found nothing various but the value of the attribute <property name="procesingfacility"> is different between the example and mine; the former is DLR-Oberpfaffenhofen, Germany, and the latter is Airbus DS-Newport, United Kingdom. This confued me. I have been trapped by this for so long.
Could you pleasae tell me the version of isce2  which you used to processed Fernandian dataset?

**Comment by yunjunz** [comment]
Your dataset doesn't have the "hgt.rdr.rsc" file. It is required and should have been generated by `prep_isce.py`, which is failed as shown in the terminal message. 

`isce` module is required to run prep_sice.py. If you installed mintpy and isce in different python (conda) environment, run prep_isce.py in isce environment first to generate all the required metadata; then switch to mintpy environment to run smallbaselineApp.py.

**Comment by Hikersp** [comment]
Thank you very much! Mr Zhang, you really do a huge favour for me.
