### ISSUE TITLE
setup.py for MintPy cannot find "openmp"

### ISSUE THREAD

**Issue by pbrotoisworo** [insarlab/MintPy#495]
There is an error when running `setup.py` because it cannot find `openmp`. I replace it with `intel-openmp` and MintPy still works, but I'm not sure if that's the appropriate package to use. I did notice that `openmp` can install from conda since it is part of `conda_env.yml`. Tested on Python 3.8 Windows 8.1 and Windows 10.

Steps to reproduce:

1. Create MintPy virtual environment using `conda_env.yml`
2. Run `setup.py install` in MintPy

Result of running setup.py:
![image](https://user-images.githubusercontent.com/32087633/103189263-c8a7be80-4906-11eb-9dc3-ca8bd62ed516.png)

**Is your feature request related to a problem? Please describe**

Cannot run `setup.py`

**Describe the solution you'd like**

Replace `openmp` with something else or possibly remove it since it is installed during virtual environment creation.

**Describe alternatives you have considered**

Replace `openmp` with `intel-openmp`

**Additional context**

None.

**Are you willing to help implement and maintain this feature?** Yes/No

Yes. Relatively simple fix.

**Comment by yunjunz** [comment]
`setup.py` is currently a work in progress and not finished yet. Please following the note on the installation page and ignore setup.py. Thanks for checking this issue though!

**Comment by pbrotoisworo** [comment]
Oh i see. Perhaps I can create another thread for feature suggestion regarding the installation process. I've actually been using a modified installation process for MintPy and the software is able to work fine.

1. Create environment from `conda_env.yml`
2. Install MintPy using modified `setup.py` where it utilizes `intel-openmp` instead of `openmp`
3. Install PyAPS3 using custom `setup.py`

I don't set any environment variables during this process.

**Comment by yunjunz** [comment]
That will be a useful feature, yes, please.

Regarding OpenMP or potentially other dependencies in setup.py, removing them is preferred because intel-openmp is meant for macOS only, thus not cross-platform. And they are already installed through conda as you have pointed out.
