### ISSUE TITLE
installation process via conda and setup.py

### ISSUE THREAD

**Issue by pbrotoisworo** [insarlab/MintPy#497]
Hello everyone. May I recommend the following revisions to the installation process below. I've been testing it on my personal download of MintPy and it can run the MintPy analysis just fine. I'm hoping this will work in other operating systems and so that you don't have to make separate instructions for Linux/MacOS/Windows.

My testing environment:

- Windows 8.1/Windows 10
- Python 3.8 Anaconda

**Description of the desired feature**

Update MintPy installation process so that it is easier to install.

**Describe the solution you'd like**

Here are some of the revisions I did in my testing environment.

1.  Create a `setup.py` for [pyaps3](https://github.com/yunjunz/pyaps3)
I've been using a simple setup script as seen in the codeblock below and it works for me. I'm able to import `pyaps3` as a normal Python library. I `cd` into the pyaps directory and use `python setup.py install`.

```python
from setuptools import setup, find_packages

setup(
    name='pyaps3',
    version='1.0',
    author='Angelique Benoit',
    packages=find_packages(include=['pyaps3', 'pyaps3.*']),
    package_data={'': ['*.cfg', 'LICENSE']},
    include_package_data=True
)
```

2. Remove `openmp` from MintPy `setup.py` file.

`openmp` does not exist in the pip library. It exists in the conda library [here](https://anaconda.org/conda-forge/openmp). In my experience you can run `python setup.py install` if you remove `openmp` and you can run and import the MintPy software without any issue. However, I noticed some errors pop up due to improper formatting in `lookup_geo2radar.py` as seen in the image below.

![image](https://user-images.githubusercontent.com/32087633/103189263-c8a7be80-4906-11eb-9dc3-ca8bd62ed516.png)

**Notes on Config Files**:
Installing in the standard python path will make the config file harder to access. We can access the location of the CFG file by doing this:

```python
    import pyaps3
    import os

    pyaps3_cfg_dir = os.path.dirname(pyaps3.__file__)
    pyaps3_cfg_path = os.path.join(pyaps3_cfg_dir, 'model.cfg')
```

**My installation process**:
After those revisions my final installation process is as follows:

1.  Create virtual environment using provided `conda_env.yml` file
2. Run `python setup.py install` for MintPy
3. Run `python setup.py install` for PyAPS3

I did not need to setup any environment variables.

**Are you willing to help implement and maintain this feature?** Yes/No
Yes.

I'm not sure if this method works on MacOS and Linux operating systems. May someone try?

**Comment by yunjunz** [comment]
This is great @pbrotoisworo! 

The procedure works fine for me, after comment out openmp/gfortran in setup.py as you suggested  in the PR above: `mintpy` python module is available.

How did you run smallbaselineApp.py in the command line? I manually add `smallbaselineApp.py`, `(ts)view.py` in setup.py so that they are available as executables in the command line, but this is pretty limited; unless there is a automatic way to add the directory to mintpy folder into $PATH.

**Comment by yunjunz** [comment]
Could you issue a PR to [Angelique's pyaps3 repo](https://github.com/AngeliqueBenoit/pyaps3) for the setup.py? This would make it easier for other users to use it as well.

I would suggest the following changes:
```python
    description="Python based Atmospheric Phase Screen Estimation",
    url="https://github.com/AngeliqueBenoit/pyaps3"
    author="Angelique Benoit, Romain Jolivet",
    author_email="insar@geologie.ens.fr",
```

**Comment by pbrotoisworo** [comment]
> 
> 
> This is great @pbrotoisworo!
> 
> The procedure works fine for me, after comment out openmp/gfortran in setup.py as you suggested in the PR above: `mintpy` python module is available.
> 
> How did you run smallbaselineApp.py in the command line? I manually add `smallbaselineApp.py`, `(ts)view.py` in setup.py so that they are available as executables in the command line, but this is pretty limited; unless there is a automatic way to add the directory to mintpy folder into $PATH.

Great to hear it works @yunjunz!

In my version of MintPy I've been accessing MintPy modules by using a separate Python script that runs terminal commands but maybe you can integrate this into MintPy so that it is easier to use.

In my program I generate the following parameters for the terminal command:

- Absolute path of Python executable. `sys.executable`
- Absolute path of MintPy directory `import mintpy` then run `os.path.dirname(mintpy.__file__)`. Then I use `os.path.join(mintpy_directory, 'smallbaselineApp.py')`
- Parameters such as `-o`, `--nodisplay`, or path of the config file

Here is a sample where I generate the command to create Temporal Coherence figures:
```python
command = f'{self.python_interpreter_path} {self.path_mintpy_view} {os.path.join(self.sbas_output_dir, "temporalCoherence.h5")} -o {os.path.join(self.path_sbas_output_figs, "temporalCoherence.png")} --nodisplay'
subprocess.call(command)
```

I think this method is a platform-neutral way of running the scripts as well. I have a function where it runs a bunch of code  similar to the codeblock above because my Windows machine can't run the Linux .sh commands.



> 
> 
> Could you issue a PR to [Angelique's pyaps3 repo](https://github.com/AngeliqueBenoit/pyaps3) for the setup.py? This would make it easier for other users to use it as well.
> 
> I would suggest the following changes:
> 
> ```python
>     description="Python based Atmospheric Phase Screen Estimation",
>     url="https://github.com/AngeliqueBenoit/pyaps3"
>     author="Angelique Benoit, Romain Jolivet",
>     author_email="insar@geologie.ens.fr",
> ```

Sure! I'll do a pull request.

**Comment by yunjunz** [comment]
Hi @pbrotoisworo, I have updated the `yunjunz/PyAPS` repo against your PR AngeliqueBenoit/pyaps3#2, together with an update on the installation. 

From my testing, `pip install git+https://github.com/yunjunz/PyAPS.git` works fine on my laptop. 

Thank you for your suggestion on setup.py and cheers!

**Comment by pbrotoisworo** [comment]
Nice. I just tried creating a new virtual environment using the latest MintPy commit and the MintPy analysis seems to work. Is there any plan to update the [installation documentation](https://github.com/insarlab/MintPy/blob/main/docs/installation.md)?

**Comment by yunjunz** [comment]
Here is the list to check for us to update the installation:
1. support grabbing CDS API account info from an `~/.*rc` file if no valid account info is found on `os.path.join(os.path.dirname(pyaps3.__file__), 'model.cfg')`. Details on the `.*rc` file is available on CDS website. In this way, users won't need to dig into the complicated pyaps3 dir if it's installed via `setup.py`. Then PyAPS can be installed in the same way as PySolid with one line.
2. What's the impact of not using `openmp` for geocoding via `pyresample`?
3. `{self.python_interpreter_path} {self.path_mintpy_view}` does not sounds attractive enough to me, as I am running individual mintpy scripts, such as `subset.py`, `save_*.py`, manually in the command line so many times a day. There should be a better way to make all the executables available directly without absolute path, similar to the scripts in `ISCE-2/applications`.

**Comment by pbrotoisworo** [comment]
Regarding point 3, that is true. Adding MintPy to the PATH environment such as what they mentioned in `ISCE-2` is really the best way to do it if you will be frequently using the command line. I'm not very familiar with the other topics. I'll close this issue since it appears to be done.
