### ISSUE TITLE
unwrap_error_bridging.py error when bridge a single Unwrapping interferogram

### ISSUE THREAD

**Issue by EllenLee183** [insarlab/MintPy#498]
![shot_20201230165739](https://user-images.githubusercontent.com/50619110/103340884-3c40fb80-4ac0-11eb-99c8-21e20fdc31a8.png)

I guess it may be due to the lack of files. Could you tell me what files are needed to correct the unwrapping error of the single-scene interferogram?

**Comment by yunjunz** [comment]
Yes, the connected components file is required by the method and is missing. It could be generated by SNAPHU.

**Comment by EllenLee183** [comment]
If I want to correct the phase of the unwrapping interferogram generated by the gamma software, what files do I need to prepare? Gamma uses the MCF phase unwrapping method, and there is no *.conncomp file generated. Another question is how to produce the .unw.rsc and *.cor.rsc in the case data you gave，the gamma software processing does not seem to generate these two files.
![微信图片_20201231151929](https://user-images.githubusercontent.com/50619110/103399372-bda99400-4b7b-11eb-9bad-9f98133c494c.png)

**Comment by yunjunz** [comment]
This option is not supported for gamma products because gamma does not produce conn comp file as far as I know.

**Comment by yunjunz** [comment]
All metadata files are created using prep_*.py.

**Comment by EllenLee183** [comment]
Ok, thank you very much for your reply
