### ISSUE TITLE
TypeError: Indexing arrays must have integer dtypes

### ISSUE THREAD

**Issue by neverstoplearn** [insarlab/MintPy#501]
After I successfully installed MintPy, I tried
 `wget https://zenodo.org/record/3952953/files/FernandinaSenDT128.tar.xz
tar -xvJf FernandinaSenDT128.tar.xz
cd FernandinaSenDT128/mintpy
smallbaselineApp.py ${MINTPY_HOME}/mintpy/data/input_files/FernandinaSenDT128.txt`
but I got this error:
`(mintpy) rsgis@rsgis10:/mnt/FernandinaSenDT128/mintpy$ smallbaselineApp.py /mnt/MintPy/mintpy/data/input_files/FernandinaSenDT128.txt
Using default MintPy Path: /home/rsgis/miniconda3/envs/mintpy/lib/python3.6/site-packages/mintpy-1.2.3-py3.6.egg

___________________________________________________________

  /##      /## /##             /##     /#######           
 | ###    /###|__/            | ##    | ##__  ##          
 | ####  /#### /## /#######  /######  | ##  \ ## /##   /##
 | ## ##/## ##| ##| ##__  ##|_  ##_/  | #######/| ##  | ##
 | ##  ###| ##| ##| ##  \ ##  | ##    | ##____/ | ##  | ##
 | ##\  # | ##| ##| ##  | ##  | ## /##| ##      | ##  | ##
 | ## \/  | ##| ##| ##  | ##  |  ####/| ##      |  #######
 |__/     |__/|__/|__/  |__/   \___/  |__/       \____  ##
                                                 /##  | ##
                                                |  ######/
   Miami InSAR Time-series software in Python    \______/ 
          MintPy v1.2.3, 2020-07-14
___________________________________________________________

--RUN-at-2021-01-04 14:42:36.175716--
Current directory: /mnt/FernandinaSenDT128/mintpy
Run routine processing with smallbaselineApp.py on steps: ['load_data', 'modify_network', 'reference_point', 'quick_overview', 'correct_unwrap_error', 'invert_network', 'correct_LOD', 'correct_troposphere', 'deramp', 'correct_topography', 'residual_RMS', 'reference_date', 'velocity', 'geocode', 'google_earth', 'hdfeos5']
Remaining steps: ['modify_network', 'reference_point', 'quick_overview', 'correct_unwrap_error', 'invert_network', 'correct_LOD', 'correct_troposphere', 'deramp', 'correct_topography', 'residual_RMS', 'reference_date', 'velocity', 'geocode', 'google_earth', 'hdfeos5']
--------------------------------------------------
Project name: FernandinaSenDT128
Go to work directory: /mnt/FernandinaSenDT128/mintpy
copy default template file /home/rsgis/miniconda3/envs/mintpy/lib/python3.6/site-packages/mintpy-1.2.3-py3.6.egg/mintpy/defaults/smallbaselineApp.cfg to work directory
read custom template file: /mnt/MintPy/mintpy/data/input_files/FernandinaSenDT128.txt
update default template based on input custom template
    mintpy.load.processor: auto --> isce
    mintpy.load.metaFile: auto --> ../reference/IW*.xml
    mintpy.load.baselineDir: auto --> ../baselines
    mintpy.load.unwFile: auto --> ../merged/interferograms/*/filt_*.unw
    mintpy.load.corFile: auto --> ../merged/interferograms/*/filt_*.cor
    mintpy.load.connCompFile: auto --> ../merged/interferograms/*/filt_*.unw.conncomp
    mintpy.load.demFile: auto --> ../merged/geom_reference/hgt.rdr
    mintpy.load.lookupYFile: auto --> ../merged/geom_reference/lat.rdr
    mintpy.load.lookupXFile: auto --> ../merged/geom_reference/lon.rdr
    mintpy.load.incAngleFile: auto --> ../merged/geom_reference/los.rdr
    mintpy.load.azAngleFile: auto --> ../merged/geom_reference/los.rdr
    mintpy.load.shadowMaskFile: auto --> ../merged/geom_reference/shadowMask.rdr
    mintpy.load.waterMaskFile: auto --> None
    mintpy.reference.lalo: auto --> -0.30,-91.43
    mintpy.deramp: auto --> linear
    mintpy.topographicResidual.stepFuncDate: auto --> 20170910,20180613
copy FernandinaSenDT128.txt to inputs directory for backup.
copy smallbaselineApp.cfg to inputs directory for backup.
copy FernandinaSenDT128.txt to pic directory for backup.
copy smallbaselineApp.cfg to pic directory for backup.
read default template file: /mnt/FernandinaSenDT128/mintpy/smallbaselineApp.cfg
copy /home/rsgis/miniconda3/envs/mintpy/lib/python3.6/site-packages/mintpy-1.2.3-py3.6.egg/mintpy/sh/plot_smallbaselineApp.sh to work directory: /mnt/FernandinaSenDT128/mintpy

******************** step - load_data ********************

load_data.py --template /mnt/FernandinaSenDT128/mintpy/smallbaselineApp.cfg /mnt/MintPy/mintpy/data/input_files/FernandinaSenDT128.txt --project FernandinaSenDT128
processor : isce
SAR platform/sensor : Sen
--------------------------------------------------
prepare metadata files for isce products
prep_isce.py -m ../reference/IW1.xml -g ../merged/geom_reference -b ../baselines -d ../merged/interferograms -f filt_*.unw
['../reference/data.rsc'] exists and is newer than ['../reference/IW1.xml'] --> skip.
prepare .rsc file for geometry files
write /mnt/FernandinaSenDT128/merged/geom_reference/hgt.rdr.rsc
write /mnt/FernandinaSenDT128/merged/geom_reference/lat.rdr.rsc
write /mnt/FernandinaSenDT128/merged/geom_reference/lon.rdr.rsc
write /mnt/FernandinaSenDT128/merged/geom_reference/los.rdr.rsc
write /mnt/FernandinaSenDT128/merged/geom_reference/shadowMask.rdr.rsc
read perp baseline time-series from ../baselines
prepare .rsc file for  filt_*.unw
[==================================================] 20180607_20180619    0s /     0s
Done.
--------------------------------------------------
searching interferometric pairs info
input data files:
unwrapPhase     : ../merged/interferograms/*/filt_*.unw
coherence       : ../merged/interferograms/*/filt_*.cor
connectComponent: ../merged/interferograms/*/filt_*.unw.conncomp
number of unwrapPhase     : 288
number of coherence       : 288
number of connectComponent: 288
--------------------------------------------------
searching geometry files info
input data files:
height          : ../merged/geom_reference/hgt.rdr
latitude        : ../merged/geom_reference/lat.rdr
longitude       : ../merged/geom_reference/lon.rdr
incidenceAngle  : ../merged/geom_reference/los.rdr
azimuthAngle    : ../merged/geom_reference/los.rdr
shadowMask      : ../merged/geom_reference/shadowMask.rdr
--------------------------------------------------
updateMode : True
compression: None
x/ystep: 1/1
--------------------------------------------------
create HDF5 file /mnt/FernandinaSenDT128/mintpy/inputs/ifgramStack.h5 with w mode
create dataset /unwrapPhase      of <class 'numpy.float32'>   in size of (288, 450, 600) with compression = None
[==================================================] 20180607_20180619    4s /     0s
create dataset /coherence        of <class 'numpy.float32'>   in size of (288, 450, 600) with compression = None
[==================================================] 20180607_20180619    4s /     0s
create dataset /connectComponent of <class 'numpy.int16'>     in size of (288, 450, 600) with compression = lzf
[==================================================] 20180607_20180619    9s /     0s
create dataset /date             of <class 'numpy.bytes_'>    in size of (288, 2)
create dataset /bperp            of <class 'numpy.float32'>   in size of (288,)
create dataset /dropIfgram       of <class 'numpy.bool_'>     in size of (288,)
add extra metadata: {'PROJECT_NAME': 'FernandinaSenDT128', 'PLATFORM': 'Sen'}
Finished writing to /mnt/FernandinaSenDT128/mintpy/inputs/ifgramStack.h5
--------------------------------------------------
create HDF5 file /mnt/FernandinaSenDT128/mintpy/inputs/geometryRadar.h5 with w mode
create dataset /height             of <class 'numpy.float32'>   in size of (450, 600) with compression = lzf
create dataset /latitude           of <class 'numpy.float32'>   in size of (450, 600) with compression = lzf
create dataset /longitude          of <class 'numpy.float32'>   in size of (450, 600) with compression = lzf
create dataset /incidenceAngle     of <class 'numpy.float32'>   in size of (450, 600) with compression = lzf
create dataset /azimuthAngle       of <class 'numpy.float32'>   in size of (450, 600) with compression = lzf
create dataset /shadowMask         of <class 'numpy.bool_'>     in size of (450, 600) with compression = lzf
create dataset /slantRangeDistance of <class 'numpy.float32'>   in size of (450, 600) with compression = lzf
add extra metadata: {'PROJECT_NAME': 'FernandinaSenDT128', 'PLATFORM': 'Sen'}
Finished writing to /mnt/FernandinaSenDT128/mintpy/inputs/geometryRadar.h5
time used: 00 mins 21.6 secs.

Loaded dataset are processed by InSAR software: isce
Loaded dataset is in RADAR coordinates
Interferograms Stack: /mnt/FernandinaSenDT128/mintpy/inputs/ifgramStack.h5
Geometry File       : /mnt/FernandinaSenDT128/mintpy/inputs/geometryRadar.h5
Lookup Table File   : /mnt/FernandinaSenDT128/mintpy/inputs/geometryRadar.h5
--------------------------------------------------
All data needed found/loaded/copied. Processed 2-pass InSAR data can be removed.
--------------------------------------------------
updating ifgramStack.h5, geometryRadar.h5 metadata based on custom template file: FernandinaSenDT128.txt

******************** step - modify_network ********************

modify_network.py /mnt/FernandinaSenDT128/mintpy/inputs/ifgramStack.h5 -t /mnt/FernandinaSenDT128/mintpy/smallbaselineApp.cfg
read options from template file: smallbaselineApp.cfg
No input option found to remove interferogram
Keep all interferograms by enable --reset option
--------------------------------------------------
reset dataset 'dropIfgram' to True for all interferograms for file: /mnt/FernandinaSenDT128/mintpy/inputs/ifgramStack.h5
All dropIfgram are already True, no need to reset.

plot_network.py /mnt/FernandinaSenDT128/mintpy/inputs/ifgramStack.h5 -t /mnt/FernandinaSenDT128/mintpy/smallbaselineApp.cfg --nodisplay -d coherence -v 0.2 1.0
read options from template file: smallbaselineApp.cfg
read temporal/spatial baseline info from file: /mnt/FernandinaSenDT128/mintpy/inputs/ifgramStack.h5
calculating spatial mean of coherence in file /mnt/FernandinaSenDT128/mintpy/inputs/ifgramStack.h5 ...
read mask from file: waterMask.h5
[==================================================] 288/288    3s /     0s
write average value in space into text file: coherenceSpatialAvg.txt
number of acquisitions: 98
number of interferograms: 288
--------------------------------------------------
number of interferograms marked as drop: 0
number of interferograms marked as keep: 288
number of acquisitions marked as drop: 0
save figure to bperpHistory.pdf
save figure to coherenceMatrix.pdf
save figure to coherenceHistory.pdf
max perpendicular baseline: 214.31 m
max temporal      baseline: 96.0 days
showing coherence
data range: [0.9150893, 0.9917158]
display range: [0.2, 1.0]
save figure to network.pdf

******************** step - reference_point ********************

generate_mask.py /mnt/FernandinaSenDT128/mintpy/inputs/ifgramStack.h5 --nonzero -o maskConnComp.h5 --update
input ifgramStack file: /mnt/FernandinaSenDT128/mintpy/inputs/ifgramStack.h5
--------------------------------------------------
update mode: ON
1) output file maskConnComp.h5 NOT exist.
run or skip: run.
calculate the common mask of pixels with non-zero connectComponent value
[==================================================] 288/288    3s /     0s
create HDF5 file: maskConnComp.h5 with w mode
create dataset /mask of bool       in size of (450, 600)           with compression=None
finished writing to maskConnComp.h5

temporal_average.py /mnt/FernandinaSenDT128/mintpy/inputs/ifgramStack.h5 --dataset coherence -o avgSpatialCoh.h5 --update
output file: avgSpatialCoh.h5
--------------------------------------------------
update mode: ON
1) output file avgSpatialCoh.h5 NOT exist.
run or skip: run.
calculate the temporal average of coherence in file /mnt/FernandinaSenDT128/mintpy/inputs/ifgramStack.h5 ...
[==================================================] lines 450/450 
create HDF5 file: avgSpatialCoh.h5 with w mode
create dataset /coherence of float32    in size of (450, 600)           with compression=None
finished writing to avgSpatialCoh.h5
time used: 00 mins 1.4 secs

reference_point.py /mnt/FernandinaSenDT128/mintpy/inputs/ifgramStack.h5 -t /mnt/FernandinaSenDT128/mintpy/smallbaselineApp.cfg -c avgSpatialCoh.h5
--------------------------------------------------
reading reference info from template: /mnt/FernandinaSenDT128/mintpy/smallbaselineApp.cfg
input reference point in lat/lon: (-0.3, -91.43)
input reference point in y/x: (76, 156)
mask: maskConnComp.h5
--------------------------------------------------
calculate the temporal average of unwrapPhase in file /mnt/FernandinaSenDT128/mintpy/inputs/ifgramStack.h5 ...
[==================================================] lines 450/450 
Add/update ref_x/y attribute to file: /mnt/FernandinaSenDT128/mintpy/inputs/ifgramStack.h5
{'REF_Y': '76', 'REF_X': '156'}
touch avgSpatialCoh.h5
touch maskConnComp.h5
Done.

******************** step - quick_overview ********************

temporal_average.py /mnt/FernandinaSenDT128/mintpy/inputs/ifgramStack.h5 --dataset unwrapPhase -o avgPhaseVelocity.h5 --update
output file: avgPhaseVelocity.h5
--------------------------------------------------
update mode: ON
1) output file avgPhaseVelocity.h5 NOT exist.
run or skip: run.
calculate the temporal average of unwrapPhase in file /mnt/FernandinaSenDT128/mintpy/inputs/ifgramStack.h5 ...
Traceback (most recent call last):
  File "/home/rsgis/miniconda3/envs/mintpy/bin/smallbaselineApp.py", line 4, in <module>
    __import__('pkg_resources').run_script('mintpy==1.2.3', 'smallbaselineApp.py')
  File "/home/rsgis/miniconda3/envs/mintpy/lib/python3.6/site-packages/pkg_resources/__init__.py", line 665, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/rsgis/miniconda3/envs/mintpy/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1463, in run_script
    exec(code, namespace, namespace)
  File "/home/rsgis/miniconda3/envs/mintpy/lib/python3.6/site-packages/mintpy-1.2.3-py3.6.egg/EGG-INFO/scripts/smallbaselineApp.py", line 1144, in <module>
    main(sys.argv[1:])
  File "/home/rsgis/miniconda3/envs/mintpy/lib/python3.6/site-packages/mintpy-1.2.3-py3.6.egg/EGG-INFO/scripts/smallbaselineApp.py", line 1134, in main
    app.run(steps=inps.runSteps, plot=inps.plot)
  File "/home/rsgis/miniconda3/envs/mintpy/lib/python3.6/site-packages/mintpy-1.2.3-py3.6.egg/EGG-INFO/scripts/smallbaselineApp.py", line 1072, in run
    self.run_quick_overview(sname)
  File "/home/rsgis/miniconda3/envs/mintpy/lib/python3.6/site-packages/mintpy-1.2.3-py3.6.egg/EGG-INFO/scripts/smallbaselineApp.py", line 526, in run_quick_overview
    mintpy.temporal_average.main(iargs)
  File "/home/rsgis/miniconda3/envs/mintpy/lib/python3.6/site-packages/mintpy-1.2.3-py3.6.egg/mintpy/temporal_average.py", line 102, in main
    inps.outfile = ut.temporal_average(inps.file, datasetName=inps.datasetName, outFile=inps.outfile)
  File "/home/rsgis/miniconda3/envs/mintpy/lib/python3.6/site-packages/mintpy-1.2.3-py3.6.egg/mintpy/utils/utils1.py", line 342, in temporal_average
    dataMean = ifgramStack(File).temporal_average(datasetName=datasetName)
  File "/home/rsgis/miniconda3/envs/mintpy/lib/python3.6/site-packages/mintpy-1.2.3-py3.6.egg/mintpy/objects/stack.py", line 1064, in temporal_average
    ref_val = dset[ifgram_flag, self.refY, self.refX]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/rsgis/miniconda3/envs/mintpy/lib/python3.6/site-packages/h5py/_hl/dataset.py", line 777, in __getitem__
    selection = sel.select(self.shape, args, dataset=self)
  File "/home/rsgis/miniconda3/envs/mintpy/lib/python3.6/site-packages/h5py/_hl/selections.py", line 82, in select
    return selector.make_selection(args)
  File "h5py/_selector.pyx", line 272, in h5py._selector.Selector.make_selection
  File "h5py/_selector.pyx", line 183, in h5py._selector.Selector.apply_args
TypeError: Indexing arrays must have integer dtypes
(mintpy) rsgis@rsgis10:/mnt/FernandinaSenDT128/mintpy$ 

I use ubuntu20.04  conda  python3.6  and mintpy1.2.3
thanks, look forward someone help.

**Comment by yunjunz** [comment]
Close this one as similar issues have been reported and discussed several times on GitHub and google forum.

**Comment by neverstoplearn** [comment]
> Close this one as similar issues have been reported and discussed several times on GitHub and google forum.

can you give me a link？ I have looked over the all closed issues, but I can not found the same issues,thanks.

**Comment by yunjunz** [comment]
https://groups.google.com/g/mintpy/c/AZWfYQghmk4/m/Hu0A24J5BAAJ

**Comment by yuxuan-dyx** [comment]
I encountered a similar problem, have you solved it ？
