### ISSUE TITLE
`fractal` turbulence simulator producing incorrect scales for some regimes

### ISSUE THREAD

**Issue by scottstanie** [insarlab/MintPy#502]
**Description of the problem**

The default settings in the turbulence simulator aren't producing the right scale output.

**Full script that generated the error**

(for python 3.8):
```
from mintpy.simulation import fractal
import matplotlib.pyplot as plt

regime = [0.001, 0.999, 1.0]
f1 = fractal.fractal_surface_atmos(shape=(1000, 1000), regime=regime)

plt.figure()
plt.imshow(f1)
plt.title(f"{regime = }")

regime = [0.01, 0.99, 1.0]
f2 = fractal.fractal_surface_atmos(shape=(1000, 1000), regime=regime)

plt.figure()
plt.imshow(f2)
plt.title(f"{regime = }")
```

No error, but here's the results:

Both of these should be "large scale turbulance", as the docstring says `regime=[0.001, 0.999, 1.0] for larger scale turbulence`

<img width="965" alt="image" src="https://user-images.githubusercontent.com/8291800/103841561-7fb7de80-5059-11eb-9479-bb0595a7b0f3.png">

**System information**

* Operating system: macOS 
* Python environment: conda 
* Version of MintPy: 
MintPy release version v1.2.3-121, release date 2021-01-02

**Comment by scottstanie** [comment]
I found the Hanssen MATLAB script online, where his " scale" examples dont have as drastic a separation for the CDF cutoffs as 0.1% and 99.9% ... I think I know what's causing this: 

the line 
```python
fraction[regime2] = fraction2 / np.min(fraction2) * np.max(fraction[regime1])
```
is setting this to 0 when `regime1` is so small that the only array item it picks is "0", so it means there's nothing in the first regime and the multiplication makes the second fraction[regime2] also 0 (and the 3rd). This then means that the final PSD that we take the IFFT of is just the original white noise, not reshaped into a power law.

I should be able to put up a PR for this in a minute

**Comment by scottstanie** [comment]
```python
-    fraction[regime1] = fraction1
+    fraction[regime1] = np.maximum(fraction1, 1)
```
Making this change seems like it's closer to expectations:

<img width="441" alt="image" src="https://user-images.githubusercontent.com/8291800/103843368-526d2f80-505d-11eb-9ac1-d2e620733174.png">

I admit that I don't know why there's the `.../ np.min(fraction2) * np.max(fraction[regime1])` and `.../ np.min(fraction3) * np.max(fraction[regime2])`, as I'm only getting a grasp on the power spectral material from the Hanssen book now, but making sure that `fraction1` isn't only zero seems to fix it, and making the single 0 into a 1 doesn't seem to affect the results either.

**Comment by yunjunz** [comment]
[fractal.py#L111-L113](https://github.com/insarlab/MintPy/blob/main/mintpy/simulation/fractal.py#L111-L113) ensure continuity while adjusting the slope of the power spectrum to the specified `beta`.

I guess the issue you have should be because the calculated regime 1 (for small spatial scale component) is smaller than the defined `resolution`, thus becoming meaningless. Could you try changing [fractal.py#L99](https://github.com/insarlab/MintPy/blob/main/mintpy/simulation/fractal.py#L99) from `k1 = regime[0] * kmax` to `k1 = max(regime[0] * kmax, resolution*4)` and plot the resulting power spectrum using `get_power_spectral_density(display=True)`?

**Comment by scottstanie** [comment]
Yep that also seems like it works:
<img width="441" alt="image" src="https://user-images.githubusercontent.com/8291800/103932727-e5eb4280-50e7-11eb-8f28-b05ac5b68fbc.png">
<img width="1074" alt="image" src="https://user-images.githubusercontent.com/8291800/103932776-f7cce580-50e7-11eb-8605-2abea6709485.png">

With the change I had, it looks like this (basically the same). 
<img width="930" alt="image" src="https://user-images.githubusercontent.com/8291800/103932948-3b275400-50e8-11eb-8f93-c0a2c6cd3283.png">
So since your suggestion is more sensible/less of a hack like mine, I'll switch it in the PR

(before either fix, that second plot looked like this:)
<img width="894" alt="image" src="https://user-images.githubusercontent.com/8291800/103932858-16cb7780-50e8-11eb-8110-2dfaea089ad2.png">

**Comment by yunjunz** [comment]
Great, thank you for looking into this @scottstanie.
