### ISSUE TITLE
load_data.py error with alosStack dataset

### ISSUE THREAD

**Issue by gracebato** [insarlab/MintPy#515]
Hi, 

I am trying to run smallbaselineApp.py but encountered the following error:

Traceback (most recent call last):
  File "/u/tiger-z5/bato/tools/MintPy/mintpy/smallbaselineApp.py", line 1182, in <module>
    main(sys.argv[1:])
  File "/u/tiger-z5/bato/tools/MintPy/mintpy/smallbaselineApp.py", line 1172, in main
    app.run(steps=inps.runSteps, plot=inps.plot)
  File "/u/tiger-z5/bato/tools/MintPy/mintpy/smallbaselineApp.py", line 1098, in run
    self.run_load_data(sname)
  File "/u/tiger-z5/bato/tools/MintPy/mintpy/smallbaselineApp.py", line 364, in run_load_data
    mintpy.load_data.main(iargs)
  File "/u/tiger-z5/bato/tools/MintPy/mintpy/load_data.py", line 759, in main
    stackObj = read_inps_dict2ifgram_stack_dict_object(iDict)
  File "/u/tiger-z5/bato/tools/MintPy/mintpy/load_data.py", line 430, in read_inps_dict2ifgram_stack_dict_object
    date12 = readfile.read_attribute(dsPath)['DATE12'].replace('_','-')
KeyError: 'DATE12'

I found this problem with stackSentinel products too but was able to solve it before by just commenting this line. I couldn't make it run now with the alosStack products. Seems DATE12 is not in the attribute list.

**Comment by yunjunz** [comment]
Hi @gracebato, `DATE12` is extracted by `prep_isce.py`, which requires the `isce` module and is called by `load_data.py`, so this works seamlessly only if isce-2 and mintpy are installed in one environment. If not, you should run `prep_isce.py` in your ISCE-2 python environment, then switch to mintpy python environment to run `smallbaselineApp.py`.

**Comment by gracebato** [comment]
Hi Yunjun,

This is exactly what I did. Ran prep_isce.py first then smallbaselineApp.py.
I thought I initial ran prep_isce correctly, but there was some error apparently (i.e. I needed to put " " in when defining the directory). So now, when I ran prep_isce, I have a new error:

2021-02-03 16:19:39,562 - isce.swath - ERROR - Error. The attribute corresponding to the key "azimuthbandwidth" is not present in the object "<class 'isceobj.Sensor.MultiMode.Swath.Swath'>".
Possible causes are the definition in the xml file of such attribute that is no longer defined 
in the object "<class 'isceobj.Sensor.MultiMode.Swath.Swath'>" or a spelling error
/u/tiger-z5/bato/tools/MintPy/mintpy/load_data.py:652: UserWarning: prep_isce.py failed. Assuming its result exists and continue...
  warnings.warn('prep_isce.py failed. Assuming its result exists and continue...')

Thanks for all the help!

**Comment by yunjunz** [comment]
Could you provide the following info for me to better diagnose?
1. Your template file
2. Compare your `data.rsc` file generated by prep_isce.py if it did with the one attached below from the example directory structure?
3. If I could access your data files, e.g. on kamb, I could take a deeper look.

[data.rsc.txt](https://github.com/insarlab/MintPy/files/5922875/data.rsc.txt)

**Comment by gracebato** [comment]
This issue is related to the isce version imported when running prep_isce.py using alosStack products. Issue was solved if one uses the isce version with alosStack processor.
