### ISSUE TITLE
ERA5 correction using tropo_pyaps3.py

### ISSUE THREAD

**Issue by mohseniaref-InSAR** [insarlab/MintPy#522]
Hi Yunjun,

The following error message I found it strange because I calculated it several times ERA5 corrections. I removed  ERA5.h5 in the input folder and process everything again. I checked all grb file sizes in the ERA5 folder and all were the same size. I tried to trace the error but I couldn't find any reasonable answer so far. I really appreciate it if you can guide me to solve this issue.

Thanks in advance.

all the best,
Mohammad

**Full script that generated the error**

```
tropo_pyaps3.py -f timeseries.h5 -g inputs/geometryRadar.h5

```

**Full error message**

```
weather model: ERA5 - dry (hydrostatic) and wet delay
weather directory: /raid-k2/maref/InSAR/slc-p83-fr-672-680/INSAR_20180821/SMALL_BASELINES/fast
output tropospheric delay file: inputs/ERA5.h5
output corrected time-series file: timeseries_ERA5.h5
read dates/time info from file: timeseries.h5
time of cloest available product: 10:00 UTC

------------------------------------------------------------------------------
downloading weather model data using PyAPS ...
common file size: 1478520 bytes
number of grib files existed    : 69
number of grib files to download: 0
------------------------------------------------------------------------------

update mode: ON
output file: inputs/ERA5.h5
1) output file either do NOT exist or is NOT newer than all GRIB files.
run or skip: run
open geometry file: geometryRadar.h5
reading incidenceAngle  data from file: inputs/geometryRadar.h5 ...
reading height          data from file: inputs/geometryRadar.h5 ...
reading latitude        data from file: inputs/geometryRadar.h5 ...
reading longitude       data from file: inputs/geometryRadar.h5 ...
--------------------------------------------------
create HDF5 file: inputs/ERA5.h5 with w mode
create dataset  : date       of |S8                       in size of (69,)                with compression = None
create dataset  : timeseries of <class 'numpy.float32'>   in size of (69, 8105, 5326)     with compression = None
close  HDF5 file: inputs/ERA5.h5

------------------------------------------------------------------------------
calcualting absolute delay for each date using PyAPS (Jolivet et al., 2011; 2014) ...
number of grib files used: 69
Traceback (most recent call last):
  File "/raid-manaslu/maref/Software/python/MintPy/mintpy/tropo_pyaps3.py", line 786, in <module>
    main(sys.argv[1:])
  File "/raid-manaslu/maref/Software/python/MintPy/mintpy/tropo_pyaps3.py", line 758, in main
    calc_delay_timeseries(inps)
  File "/raid-manaslu/maref/Software/python/MintPy/mintpy/tropo_pyaps3.py", line 687, in calc_delay_timeseries
    tropo_data = get_delay(grib_file,
  File "/raid-manaslu/maref/Software/python/MintPy/mintpy/tropo_pyaps3.py", line 564, in get_delay
    aps_obj = pa.PyAPS(grib_file,
  File "/raid-manaslu/maref/Software/python/PyAPS/pyaps3/objects.py", line 168, in __init__
    hgt = np.linspace(self.dict['minAltP'], gph.max().round(), self.dict['nhgt'])
  File "/raid-manaslu/maref/Software/anaconda3/envs/myisceenv/lib/python3.8/site-packages/numpy/core/_methods.py", line 39, in _amax
    return umr_maximum(a, axis, None, out, keepdims, initial, where)
ValueError: zero-size array to reduction operation maximum which has no identity
```

**System information**

* Operating system: Linux-Ubuntu 
* Python environment: conda 
* Version of MintPy: MintPy release version v1.2.3-125, release date 2021-01-14 
* Your custom / default template file (if the bug is related to a specific dataset):

**Comment by yunjunz** [comment]
Could you plot your `timeseries.h5` and `geometryRadar.h5` file here for me to check?

**Comment by mohseniaref-InSAR** [comment]
Yes, The result is attached as you see 

time series :
![Figure_1_-_timeseries png](https://user-images.githubusercontent.com/26392211/110292339-55e54e80-7fed-11eb-91a1-a35d1ac4908c.png)
The geometry file :
![Figure_1_-_geometryRadar png](https://user-images.githubusercontent.com/26392211/110292375-64336a80-7fed-11eb-93e6-bd907a1e8c12.png)
GACOS time series as example
![Figure_1_-_GACOS png](https://user-images.githubusercontent.com/26392211/110292477-947b0900-7fed-11eb-86dc-507a24e31c40.png)

I have tried to compile the script

´´´

tropo_pyaps3.py -f timeseries.h5 -g inputs/geometryRadar.h5

´´´

The following line is not working properly?

´´´

    aps_obj = pa.PyAPS(grib_file,
                       grib=tropo_model,
                       Del=delay_type,
                       dem=dem,
                       inc=inc,
                       lat=lat,
                       lon=lon,
                       verb=verbose)

´´´

I traced the error and it seems the following line in objects.py in PyAPS have a strange error

´´´
         self.lon[self.lon < 0.] += 360.0
        self.minlon = np.nanmin(self.lon*self.mask) - self.bufspc
        self.maxlon = np.nanmax(self.lon*self.mask) + self.bufspc
        self.minlat = np.nanmin(self.lat*self.mask) - self.bufspc
        self.maxlat = np.nanmax(self.lat*self.mask) + self.bufspc
´´´
the coverage does not make sense

INFO: INCIDENCE ANGLE AS AN ARRAY
INFO: AREA COVERAGE IN SNWE: (1.20, -28.95, -1.20, 295.61)

therefore I think the following line doesn't work

´´´
        elif self.grib in ('ERA5','ERAINT','HRES'):
            [lvls,latlist,lonlist,gph,tmp,vpr] = era.get_ecmwf(self.model,
                                                               self.gfile,
                                                               self.minlat,
                                                               self.maxlat,
                                                               self.minlon,
                                                               self.maxlon,
                                                               self.dict,
                                                               humidity=self.humidity,
                                                               verbose=verb)

´´´

Thanks in advance for your support,

Best regards,
Mohammad

**Comment by yunjunz** [comment]
I agree with you @mohseniaref-InSAR. The SNWE calculation seems failed to exclude the invalid pixels in the input geometry datasets, thus resulting in a wrong SNWE. We could adjust either in [pyaps/objects.py#83](https://github.com/yunjunz/PyAPS/blob/main/pyaps3/objects.py#L83) to ignore those values or in [mintpy/tropo_pyaps3](https://github.com/insarlab/MintPy/blob/main/mintpy/tropo_pyaps3.py#L630).py to mask out them (set to NaN). 

If you could send me your data for testing (timeseries.h5 and geometryRadar.h5 file, please run `multilook.py -m nearest -a 10 -r 10` to reduce the file size), I could try the above.

**Comment by yunjunz** [comment]
Hi @mohseniaref-InSAR, with the above commits in `insarlab/MintPy` and `yunjunz/PyAPS`, the bug should be fixed. Attached below is how ERA5.h5 looks like using the test data you sent me. Cheers.
![ERA5](https://user-images.githubusercontent.com/13143710/111059210-96f3bd80-8448-11eb-9744-6e83a21c40f0.png)

**Comment by mohseniaref-InSAR** [comment]
Thanks so much @yunjunz !
