### ISSUE TITLE
Add Windows functionality to plot_result function

### ISSUE THREAD

**Issue by pbrotoisworo** [insarlab/MintPy#531]
I'm using MintPy on a Windows machine and it cannot run the `.sh` file used to generate the plots and figures. I think it would be a good idea to add this so Windows users can easily see the output. I see that in the `plot_result` function it just copies a template `.sh` file into the work directory.

I have something like this in my own personal analysis using MintPy. This could use the following format below:
```python
# Paths
pic_dir = os.path.join(self.workDir, 'pic')
dem = os.path.join(self.workDir, 'inputs', 'geometryGeo.h5')
velocity_h5 = os.path.join(self.workDir, 'velocity.h5')
mask = os.path.join(self.workDir, 'maskTempCoh.h5')

# Run view.py
view_py = f'{self.python_interpreter_path} {self.path_mintpy_view} --nodisplay --dpi 150 --update'

# Create command
cmd = f'{view_py} {velocity_h5} --dem {dem} --mask {mask} -u cm -o {os.path.join(pic_dir, "velocity.png")}'

# Run
proc = subprocess.Popen(cmd, shell=True)
```
That's just one sample but would do that for all the desired output figures. I think this can work for Linux, MacOS, and Windows systems.

I can do a pull request if interested.

**Comment by yunjunz** [comment]
Hi @pbrotoisworo, I see you are translating the `view.py` from the command line to python. I agree it's more generic, we could write a python script, e.g. `plot_smallbaselineApp.py` to replace the shell script. 

I remember @Ovec8hkin and @falkamelung was interested in looking at this, any updates? It will be a good place to join the discussion here.

For the translation, I would recommend to import `view` as module directly, instead of calling `subprocess`, e.g.:

```python
from mintpy import view
iargs = [vel_file, '--dem', dem_file, '--mask', mask_file, '-u', 'cm'];  view.main(iargs)
```

**Comment by pbrotoisworo** [comment]
I'm not entirely familiar with the MintPy code so the PR https://github.com/insarlab/MintPy/pull/538 uses a bunch of if statements to check if the file is there. If there are some parameters I can use to check the output then I think it would be good so I can clean up the code.

For example, I'm not sure how to check if the data is UNAVCO or Envisat data.

**Comment by falkamelung** [comment]
If you contribute a new`plot_smallbaselineApp.py`, it will be good to use the `mintpy.compute` attributes to decide whether to generate  plots in a serial or parallel way.  If you use 8 cores you get a factor of 8 speed up. Using ~50 cores the generation of all plots just takes for us just a few seconds.  We use a slightly modified `plot_smallbaselineApp.bash` that sends all `view.py` processes in the background, simply by adding a `&`, e.g.:
```
    file=velocity.h5;              test -f $file && $view $file $opt               >> $log_file &
    file=temporalCoherence.h5;     test -f $file && $view $file -c gray --vlim 0 1 >> $log_file &
    file=maskTempCoh.h5;           test -f $file && $view $file -c gray --vlim 0 1 >> $log_file &
    file=inputs/geometryRadar.h5;  test -f $file && $view $file                    >> $log_file &
    file=inputs/geometryGeo.h5;    test -f $file && $view $file                    >> $log_file &
```
I believe in Python this is achieved by omitting `.wait()` in the `subprocess.Popen` call, but I don't remember well.

**Comment by pbrotoisworo** [comment]
I see. Should it follow something similar to this format? I think this is code that uses `mintpy.compute`.
https://github.com/insarlab/MintPy/blob/main/mintpy/ifgram_inversion.py#L131

I see that it loads the `mintpy.compute` parameters and updates the namespace before executing the code.

**Comment by falkamelung** [comment]
You probably would read the `mintpy.compute` attributes from the `smallbaselineApp.cfg` as does `smallbaselineApp.py`. I don't really know how to handle the case of 10 workers and 30 `view.py` processes. It would be best to submit 10 processes and  then wait until a process has completed before  submitting a new one, but this could make it complicated. So, just submitting all processes at the same time  is fine. If it causes a problem we can deal with that later.

**Comment by yunjunz** [comment]
Hi @pbrotoisworo, I would suggest completing the pure python translation first. Once it's done in a clean way, the parallelization should be straightforward.

**Comment by yunjunz** [comment]
Now the new `plot_result()` is completed, one could use `joblib` for the parallelization, as shown here: https://github.com/insarlab/MintPy/blob/1a6de6302b433e37a3272f98e7fbad4843b9389c/pysar/geocode.py#L245

**Comment by yunjunz** [comment]
close this issue as the initial goal is completed.
