### ISSUE TITLE
smallbaselineapp fails to read updated config file

### ISSUE THREAD

**Issue by bbuzz31** [insarlab/MintPy#551]
I'm trying to exclude a bunch of inferferograms using e.g.:
`mintpy.network.excludeIfgIndex = 67,68,84` 
However, it can't read the input:
```
File "/Users/bb/Software_InSAR/MintPy_git/mintpy/modify_network.py", line 142, in <listcomp>
    c = sorted([int(i) for i in idx.split(':')])
ValueError: invalid literal for int() with base 10: '[67' 
```
That extra `'['` is added early on, my guess is when reading the template file. More specifically, adding `print (value)` on line 172 of modify_network.py results in the string: `[67, 68, 84]` for key = excludeIfgIndex

### -- UPDATE --
This appears to not be the root of the problem. I originally entered `mintpy.network.excludeIfgIndex = [67,68,84]` , which caused the bug above. However, correcting the error (and indeed setting `mintpy.network.excludeIfgIndex = None`) causes the same error above to be raised. So for some reason, MintPy is not correctly reading the input file.

**Comment by yunjunz** [comment]
Maybe the `mintpy.network.excludeIfgIndex = None` is not reflected in the `smallbaselineApp.cfg` file. Could you confirm? The code reads the custom template file to update the default template file (smallbaselineApp.cfg) and use the default template file only.

**Comment by bbuzz31** [comment]
Interesting. Before posting I did check the smallbaselineApp.cfg in the './inputs' directory  (from `prep_aria.py`) and the stack itself (from info.py ifgramStack.h5); they were both updated to `None`. But you're right, the `smallbaselineApp.cfg` in the directory where I call `smallbaselineApp.py` is not updated after I run `smallbaselinApp.py myconfig`

**Comment by yunjunz** [comment]
With the above PR, the code now ignores/tolerates the [] in the inputs now.
