### ISSUE TITLE
Comparing InSAR with GPS

### ISSUE THREAD

**Issue by alevasca** [insarlab/MintPy#553]
I got this error when running the jupyter notebook Fig_08_S06_InSAR_vs_GPS.ipynb with my data: 
 _ValueError: datetime.datetime(2015, 9, 22, 0, 0) is not in list._
The code did not find this datetime because all the InSAR-datetimes have a time (acquisition time) different to zero. To solve this issue, I included a for-loop in the script insar_vs_gps.py after the line 234 (section # 2.4 reference insar and gps to a common date), in order to "cut" the time from the date:

```
for i in range(len(insar_date)):
                insar_date[i] = dt.combine(insar_date[i], time.min)
```

**Comment by yunjunz** [comment]
Thank you @alevasca, the PR above should resolve the issue.
