### ISSUE TITLE
Pedantic Linux find does not like find in plot_smallbaselineApp.sh

### ISSUE THREAD

**Issue by EJFielding** [insarlab/MintPy#560]
**Description of the problem**

I have been running a version of the tutorial script for ISCE stripmapApp output on a CentOS Linux virtual machine, and the `plot_smallbaselineApp.sh` script stops in the middle with a warning  message about the `find ‘./geo/geo_timeseries_*.h5’`.

**Full script that generated the error**

```
sh plot_smallbaselineApp.sh
```

**Full error message**

```
unwrapPhase              Dataset {12/Inf, 2472, 2554}
unwrapPhase              Dataset {12/Inf, 2472, 2554}
coherence                Dataset {12/Inf, 2472, 2554}
connectComponent         Dataset {12/Inf, 2472, 2554}
unwrapPhase_bridging**NOT FOUND** unwrapPhase_phaseClosure**NOT FOUND** unwrapPhase_bridging_phaseClosure**NOT FOUND**
 find: warning: Unix filenames usually don't contain slashes (though pathnames do). That means that '-name ‘./geo/geo_timeseries_*.h5’' will probably evaluate to false all the time onthis system.  You might find the '-wholename' test more useful, or perhaps '-samefile'.  Alternatively, if you are using GNU grep, you could use 'find ... -print0 | grep -FzZ ‘./geo/geo_timeseries_*.h5’'.

```

**System information**

* Operating system:  CentOS
* Python environment:  Jupyter notebook on nisar-jupyter.jpl.nasa.gov
* Version of MintPy: MintPy release version v1.3.0-8, release date 2021-03-19

* Your custom / default template file (if the bug is related to a specific dataset):

**Comment by yunjunz** [comment]
Thank you @EJFielding for letting me know. The shell script is never the ideal solution. The `plot_smallbaselineApp.sh` has been translated to and replaced by a pure python function `plot_result()` https://github.com/insarlab/MintPy/pull/538 recently by @pbrotoisworo. If you update to the latest version, these warnings should be gone.

**Comment by EJFielding** [comment]
Thanks, I did not notice the new version with pure Python instead of the `sh` script. For now, I will use the version that is installed on our NISAR JupyterHub, but it will be updated at some point. I could install the latest MintPy version locally in my non-volatile storage, but there are advantages to using the default instance system installation.

**Comment by yunjunz** [comment]
With the new release of version 1.3.1, users who migrated to the latest released or development version should not have this problem anymore. Close the issue.
