### ISSUE TITLE
mintPy has issue to work with hyp3 product

### ISSUE THREAD

**Issue by cirrusasf** [insarlab/MintPy#562]
**Description of the problem**
I want to make the mintPy work against hyp3 intererogram. I had an issue the step "correct_troposphere". It can not download the ERA5 data. It can bring the the session correctly. But it can not retrieve the data, because it can not pass the verification on the server side. My dem.tif is in "WGS 84 / UTM zone 53N" projection, bbox re presented in unit of meter.  I wonder if the server side only accept the bbox in degree.

result = self._api("%s/resources/%s" % (self.url, name), request, "POST")

**Full script that generated the error**

```
PASTE CODE HERE
```
result = self._api("%s/resources/%s" % (self.url, name), request, "POST")

**Full error message**

Exception: Assertion failed: bbox.north() <= Latitude::NORTH_POLE in check

```
PASTE ERROR MESSAGE HERE
```

**System information**

* Operating system: 
* Python environment: 
* Version of MintPy: 
* Your custom / default template file (if the bug is related to a specific dataset):

**Comment by EJFielding** [comment]
@cirrusasf The easiest way to deal with this is to turn the atmospheric corrections. Add this to the configuration file:
`mintpy.troposphericDelay.method = no  #[pyaps / height_correlation / no], auto for pyaps`

**Comment by cirrusasf** [comment]
Hi Insarlab/Mintpy,

Thank you for your reply.

I figured out the way to make the the mintpy works against our ASF hyp3
product. I modified several places of your code to make it work. I would
like to contribute the code back to you. What should I do?  May I push my
branch and submit the PR?

Thank you very much for your help!

Jiang

**Comment by EJFielding** [comment]
@cirrusasf I am not one of the maintainers of MintPy, only a user, but I have contributed some Pull Requests in the past. They have a contribution guide here: https://github.com/insarlab/MintPy/blob/main/docs/CONTRIBUTING.md
