### ISSUE TITLE
MintPy doesn't recognized redundant network of interferograms in HyP3 products

### ISSUE THREAD

**Issue by bjmarfito** [insarlab/MintPy#574]
I've used HyP3 to generate three interferograms from three Sentinel-1 SLC. The dates of the images are the ff: (1). Oct 2, 2019; (2) Oct 14, 2019; and October 26,2019. The three interferograms produced by HyP3 are the ff: (1)20191002_20191014; (2)20191014_20191026; and (3) 20191002_20191026. However, MintPy only recognizes two of the three interferograms which are 20191002_20191014 and 20191002_20191026. The 20191014_20191026 interferogram was not recognized by MintPy so I can't have a redundant network of interferograms.

Below is the interferogram network diagram for your reference. The diagram shows connection between 20191002 and 20191014, 20191002 and 20191026 while no connection between 20191014 and 20191026.

![network](https://user-images.githubusercontent.com/21336508/121767877-ac829b80-cb8d-11eb-9d27-f9db3de9c20d.jpg)

**System information**

* Operating system:  macOS
* Python environment: conda
* Version of MintPy: https://github.com/insarlab/MintPy/commit/2e3dcea0415dd96f02dbcafc7d36aafcbee6ef69
* Your custom / default template file (if the bug is related to a specific dataset): 
[2019_Cotabato.txt](https://github.com/insarlab/MintPy/files/6641790/2019_Cotabato.txt)

**Comment by yunjunz** [comment]
Hi @bjmarfito, it will be helpful if you could paste the printout msg of running smallbaselineApp.py.

My first guess from your attached template file is that you may forget to cut the files, as suggested in the brief instruction (https://mintpy.readthedocs.io/en/latest/dir_structure/#asf_hyp3).

**Comment by bjmarfito** [comment]
Thank you @yunjunz. Apologies for not posting the printout message. Your guess is right that I didn't cut the files before ingesting into MintPy. Now the interferogram network is fully connected.

![network](https://user-images.githubusercontent.com/21336508/121791810-9376fa80-cc20-11eb-94ff-f91320bb2069.jpg)
