### ISSUE TITLE
Add Way to Output all Result as Georeferenced Raster 

### ISSUE THREAD

**Issue by jldz9** [insarlab/MintPy#582]
**Description of the desired feature**

The template for ISCE stack processing only has the option to output times-series in hdfeos5 format, Other maps only output as png, and KMZ format.  
example for current output:: 
```
../pic
|-- avgPhaseVelocity.png
|-- avgSpatialCoh.png
|-- bperpHistory.pdf
|-- coherenceHistory.pdf
|-- coherenceMatrix.pdf
|-- coherenceSpatialAvg.txt
|-- exclude_date.txt
|-- geo_maskTempCoh.png
|-- geometryRadar.png
|-- geo_temporalCoherence.png
|-- geo_timeseries_demErr.png
|-- geo_velocity.kmz
|-- geo_velocity.png
|-- ISCE_mintpy.txt
|-- maskConnComp.png
|-- maskTempCoh.png
|-- network.pdf
|-- numInvIfgram.png
|-- numTriNonzeroIntAmbiguity.png
|-- reference_date.txt
|-- rms_timeseriesResidual_ramp.pdf
|-- rms_timeseriesResidual_ramp.txt
|-- smallbaselineApp.cfg
|-- temporalCoherence.png
|-- timeseries_demErr.png
|-- timeseries.png
`-- velocity.png
```

I would like to request adding the option in the template to output all results as georeferenced raster, Either `.tiff .grd .tif` would be good as long as it could be load into the Arcmap or Qgis as georeferenced rasters for future post-processing. 
**Is your feature request related to a problem? Please describe**

Only velocity map output as KMZ format that could only be opened by google earth. Other figures like coherence map only output as png and not georeferenced. 
Arcmap failed to convert kmz file to ArcMap readable raster using kmz to layer feature. 

**Describe the solution you'd like**

Add option to output all result as georeferenced raster including 
```
geo_velocity.tif /grd /tiff
time_series_xxxxxxx.tif  (times series as a single raster for each date)
coherence.tif 
std.tif
DEM_error.tif
```

The option in template file like 
```
########## 11.4 Arcmap  (post-processing)
mintpy.save.qgis              =  auto    #[yes/no]   auto for no, 
mintpy.save.gdal              = auto ......
mintpy.save.gmt               .............
```

**Describe alternatives you have considered**

N/A

**Additional context**

N/A

**Are you willing to help implement and maintain this feature?** No
Sorry, I'm not quite familiar with the mintpy program so I'm not able to figure this out by my own. 

Thank you and appreciate your hard work

Jiawei Li

**Comment by yunjunz** [comment]
Hi @jldz9, with the limited number of developers, I don't think we will be able to do this feature request if you can not lead the effort because: 1) it can be done manually with utility scripts e.g. save_gdal/gmt.py; 2) too much work not related to the essential funcationalities.
