### ISSUE TITLE
add timeseriesResidual in ts2vel.py

### ISSUE THREAD

**Issue by yunjunz** [insarlab/MintPy#588]
**Description of the desired feature**

As noted in #587: with the more advanced time function capability, it makes more sense to use the time series fitting residual (`timeseriesResidual.h5` file) from `timeseries2velocity.py` rather than the current `dem_error.py`, if the more advance (not by default) time functions is turned ON. For this, we could simply add a new option in ts2vel.py to generate/update the TS residual file.

For the script, the updated TS residual file from ts2vel.py should be equivalent to an updated TS residual file from dem_error.py, thus, it should be automatically used during re-run for noise evaluation purpose.

**Comment by forrestfwilliams** [comment]
Hey @yunjunz, I'd like to take this on! Where do you think the best place to start would be?

**Comment by yunjunz** [comment]
That will be great @forrestfwilliams. I would imagine in `timeseries2velocity.h5`:
+ add `--save-res / --save-residual` option to turn ON the functionality (off by default).
+ add `--res-file / --residual-ts-file` option to specify the output h5 file name with default value of `timeseriesResidual.h5`
+ calculate the residual time series data to file at [timeseries2velocity.py#L659](https://github.com/insarlab/MintPy/blob/2ff5a78920b8185ff5cece190def8e40b661e0af/mintpy/timeseries2velocity.py#L659): `ts_res = ts_data - np.dot(G, m)`
+ intiate and write the the TS h5 file next to the velocity/time_func_param file. `dem_erro.py` could be a good reference for this.

**Comment by forrestfwilliams** [comment]
Sounds good! I'll work on it this week.

**Comment by yunjunz** [comment]
It turns out I need this functionality myself now, so I added it in the PR above. Cheers!

**Comment by forrestfwilliams** [comment]
Thank you @yunjunz ! Sorry I've been absent from MintPy for a while!

**Comment by yunjunz** [comment]
No worries at all!
