### ISSUE TITLE
need ability to specify walltime for Dask

### ISSUE THREAD

**Issue by falkamelung** [insarlab/MintPy#59]
Hi @2gotgrossman : Pysar with Dask works great. Thank you!  

Issues:
-  for longer jobs we need longer walltime then 30 min specified in the dash_pysar.yaml
-  its location in ~/.config/dask is not good if it is updated for different runs.

Suggestion: For each Dask invocation we copy the /`PYSAR/defaults/dask_pysar.yaml` into the `projectname/PYSAR` dir and modify it for the specific case. The walltime could be adjusted as a PySAR option:

```
pysar.networkInversion.parallel     = yes              # [yes / no], auto for no, parallel 
pysar.networkInversion.parallel.walltime   = 3:00         #  walltime in HH:MM, auto for 0:30
processing using dask
```
Are there any other options we may want to modify (e.g. number of workers? - I don't see it). 

Any thoughts?

Others:
- Some documentation on it on the pysar page would be great, including how to assess progress.
- I did not see messages such as 'inversion split into 200 chunks' and information when chunks are finished.
- there are two incidences of walltime. Which one is used: jobqueue or Ingram_inversion?
- Who can/like/will do this?

**Comment by yunjunz** [comment]
Hi @falkamelung, 

The number of workers can be specified through `pysar.networkInversion.numWork`:
https://github.com/insarlab/PySAR/blob/master/pysar/defaults/pysarApp_template.txt#L109

**Comment by falkamelung** [comment]
Great! Then we just need an option to specify the wall time.
------------------------------------------------------
Falk Amelung
Professor
Department of Marine Geosciences
Rosenstiel School of Marine and Atmospheric Sciences
University of Miami
4600 Rickenbacker Causeway
Miami, FL 33149
USA
Tel: 305 421 4949
E-mail: famelung@rsmas.miami.edu<mailto:famelung@rsmas.miami.edu>
Web: http://insar.rsmas.miami.edu
InSAR data:
http://insarmaps.miami.edu




On May 5, 2019, at 10:08 AM, Zhang Yunjun <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @falkamelung<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ffalkamelung&data=02%7C01%7Cfamelung%40rsmas.miami.edu%7Cd493c4db81d0414dbf3e08d6d0fe9e54%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C636926189337484786&sdata=ArBS4r4pE2Tr6Zor7xJqGnawZyCm5N%2BwgmlovsrR7Ck%3D&reserved=0>,

The number of workers can be specified through pysar.networkInversion.numWork:
https://github.com/insarlab/PySAR/blob/master/pysar/defaults/pysarApp_template.txt#L109<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Finsarlab%2FPySAR%2Fblob%2Fmaster%2Fpysar%2Fdefaults%2FpysarApp_template.txt%23L109&data=02%7C01%7Cfamelung%40rsmas.miami.edu%7Cd493c4db81d0414dbf3e08d6d0fe9e54%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C636926189337484786&sdata=LFGU1RyomFZ68z%2B%2FmMAk5nT5ntJeKieOoIkKR2HFe2E%3D&reserved=0>

**Comment by falkamelung** [comment]
I see that LSFCluster has a walltime option. So it seems pretty straightforward to add a walltime similar to the number of workers. To be consistent with that option, it probably should be
`pysar.networkInversion.walltime`.  @yunjunz @mirzaees

**Comment by yunjunz** [comment]
Feel free to try it when you got a chance @falkamelung. I guess this should be easy for someone who is familiar with `dask_jobqueue` too.

**Comment by falkamelung** [comment]
Given that mintpy is more widely used than minsar or minopy I will rename the dask_pysar.yaml to dask.yaml and adjust the minsar DASK_CONFIG accordingly. @yunjunz @mirzaees please yell if that is not a good ide.

**Comment by yunjunz** [comment]
Test before your pull request please. 

Yunjun

**Comment by Keplere** [comment]
there are some questions when i install the software on ubuntu16.04

**Comment by yunjunz** [comment]
> there are some questions when i install the software on ubuntu16.04

Hi @Keplere, please post your installation related question in a separated issue or in the google group, with more details, to help the diagnose.
