### ISSUE TITLE
MintPy dependencies installation error

### ISSUE THREAD

**Issue by ShadiAbdelhadi** [insarlab/MintPy#606]
I successfully downloaded both MintPy and PyAPS. then I couldn't set the environmental variables into the source file because whenever I type ~/.bash_profile   ,  I receive this error messegae "bash: /home/shadi/.bash_profile: Permission denied" 

Now I am very new to Linux and there are may things I may have performed incorrectly. I tried to install the dependencies after, then I got this error. 
![Screenshot from 2021-07-11 17-18-16](https://user-images.githubusercontent.com/85242237/125200771-96d7c300-e26c-11eb-9be0-da05295f70d2.png)

Any suggestions?

**System information**

* Operating system: <Linux-Ubuntu>
* Python environment: < 3.8, comda>

**Comment by jhkennedy** [comment]
@ShadiAbdelhadi From the screenshot it looks like you're using Linux, not Mac, so you'll want to download the [Linux installer](https://docs.conda.io/en/latest/miniconda.html#linux-installers):

```
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
```
Here's the miniconda linux install guide: https://conda.io/projects/conda/en/latest/user-guide/install/linux.html

**Comment by ShadiAbdelhadi** [comment]
Terminal won't verify the downloaded miniconda file
![Screenshot from 2021-07-17 13-21-15](https://user-images.githubusercontent.com/85242237/126035247-5bda40a7-2209-4c62-b0b1-d65dbde4cfab.png)

**Comment by ShadiAbdelhadi** [comment]
> @ShadiAbdelhadi From the screenshot it looks like you're using Linux, not Mac, so you'll want to download the [Linux installer](https://docs.conda.io/en/latest/miniconda.html#linux-installers):
> 
> ```
> wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
> ```
> 
> Here's the miniconda linux install guide: https://conda.io/projects/conda/en/latest/user-guide/install/linux.html

I have successfully installed the Miniconda Environment, I appreciate your tip. Then I have tried to install the dependencies, Does this mean I have had a successful installation ?
![Screenshot from 2021-07-18 20-50-01](https://user-images.githubusercontent.com/85242237/126079090-65df478d-fef0-4a65-893a-1044031d811f.png)
![Screenshot from 2021-07-18 20-50-08](https://user-images.githubusercontent.com/85242237/126079092-1a2bc242-ed50-418a-bc25-b4d4f182da44.png)
