### ISSUE TITLE
Mask velocity based on velocityStd

### ISSUE THREAD

**Issue by forrestfwilliams** [insarlab/MintPy#613]
**Description of the desired feature**
Similar to [Bekaert et al 2020](https://doi.org/10.1016/j.rse.2020.111983), I would like to implement masking of velocity data based on velocityStd data according to the formula: `|velocity| > (2*velocityStd)` . This masking procedure is helpful when trying to isolate areas that have a high magnitude of local deformation. 

**Describe the solution you'd like**

I can think of two approaches for how this could be done within `generate_mask.py`, but I would love to know which method @yunjunz thinks is best!

1. Implement the entire masking procedure at once, which would not allow a high degree of user modification and restrict this masking process to `velocity.h5` datasets
2. Implement each portion separately (see bullets below) so that future mask generation features can use some of the functionality
    - Add absolute value option to `image_math.py`
    - Multiply velocityStd by two using existing functionality
    - Allow the `-m` and `-M` options of `generate_mask.py` to accept filenames with a dataset specification

**Are you willing to help implement and maintain this feature?** Yes/No
Yes, I am willing to implement this improvement as soon as we determine which method we would like to use!

**Comment by yunjunz** [comment]
Hi @forrestfwilliams, both approaches sound good to me. Since the formula is not very very simple, I may prefer the 1st one as it's tighter, thus easier to understand.
