### ISSUE TITLE
DEM is not being displayed in view.py

### ISSUE THREAD

**Issue by bjmarfito** [insarlab/MintPy#627]
**Description of the problem**

I want to add a DEM on the `view.py` to generate a map of the geo_velocity.h5. However the DEM was not being read.

In `tsview.py`, the DEM is being read properly by MintPy.

**Full script that generated the error**

`view.py geo_velocity.h5 --dem ../../Sentinel1_ASC/dem/demLat_N14_N16_Lon_E120_E121.dem.wgs84`

**Full error message**

```
run view.py in MintPy release version v1.3.1, release date 2021-08-02
input file is velocity file: /Volumes/BJM/Sentinel1_ASC/mintpy/geo/geo_velocity.h5 in float32 format
file size in y/x: (1066, 2221)
num of datasets in file geo_velocity.h5: 2
datasets to exclude (0):
[]
datasets to display (2):
['velocity', 'velocityStd']
data   coverage in y/x: (0, 0, 2221, 1066)
subset coverage in y/x: (0, 0, 2221, 1066)
data   coverage in lat/lon: (119.70189928793693, 15.346906807500991, 121.4525272867701, 14.466206405084456)
subset coverage in lat/lon: (119.70189928793693, 15.346906807500991, 121.4525272867701, 14.466206405084456)
------------------------------------------------------------------------
area exceed 2000 pixels, turn off default DEM contour display
colormap: jet
figure title: geo_velocity
figure size : [15.00, 8.00]
dataset number: 2
row     number: 2
column  number: 1
figure  number: 1
read mask from file: geo_maskTempCoh.h5
Input DEM file has different size than data file, ignore it.
----------------------------------------
Figure 1 - geo_velocity.png
reading data as a list of 2D matrices ...
[==================================================] velocityStd 0s /     0s
data    range: [-16.843628, 9.382716] cm/year
display range: [-16.843628, 9.382716] cm/year
masking data
plotting ...
[==================================================] velocityStd 0s /     0s
data    range: [-16.843628, 5.7017303] cm/year
display range: [-14.806741, 4.5539207] cm/year
show colorbar
showing ...
```

**System information**

* Operating system: macOS
* Python environment: Python 3.8
* Version of MintPy: dd9512bf458d1971c6eaf8f81d31d158699c387e
* Your custom / default template file (if the bug is related to a specific dataset): 
[Lubao_S1_asc.txt](https://github.com/insarlab/MintPy/files/6923901/Lubao_S1_asc.txt)

**Comment by yunjunz** [comment]
Hi @bjmarfito, this is expected, as the msg shown above `Input DEM file has different size than data file, ignore it.` This feature only works for single subplots as below, and not for multi-subplots, which is not plotted with geo-coordinates info, thus, can not handle the different size or resolution.

```bash
view.py geo_velocity.h5 velocity --dem ../../Sentinel1_ASC/dem/demLat_N14_N16_Lon_E120_E121.dem.wgs84
```

**Comment by yunjunz** [comment]
I will add a more detailed WARNING msg for this in the next commit.

**Comment by bjmarfito** [comment]
This is great. Thank you @yunjunz!
