### ISSUE TITLE
Unable to get ecCodes definition path

### ISSUE THREAD

**Issue by pbrotoisworo** [insarlab/MintPy#637]
**Description of the problem**

`smallbaselineApp.py` encounters an error when calculating the delay for each date. It cannot find the ecCodes variable. I've fixed this in my own scripts by setting up the environment parameters before running smallbaselineApp in my script.

```python
import os
os.environ['ECCODES_DEFINITION_PATH'] = 'C:\Users\User\Miniconda3\envs\mintpy\Library\share\eccodes\definitions'
```

**Full script that generated the error**

```
# NOTE: Terminal command is run using subprocess.Popen()
python smallbaselineApp.py config.txt
```

**Full error message**

```
calculating absolute delay for each date using PyAPS (Jolivet et al., 2011; 2014) ...
number of grib files used: 17
ECCODES ERROR   :  Unable to find boot.def. Context path=D:/bld/eccodes_1616616234353/_h_env/Library/share/eccodes/definitions
Possible causes:
- The software is not correctly installed
- The environment variable ECCODES_DEFINITION_PATH is defined but incorrect

ecCodes assertion failed: `0' in D:\bld\eccodes_1616616234353\work\src\grib_context.c:226

```

**System information**

* Operating system: Windows 8
* Python environment: Anaconda Python 3.8
* Version of MintPy: MintPy release version v1.3.1, release date 2021-08-02s
* Your custom / default template file (if the bug is related to a specific dataset): n/a. applies to multiple datasets.

**Comment by piyushrpt** [comment]
Check the slashes in your path? `/` instead of `\`?

**Comment by pbrotoisworo** [comment]
If you are referring to this path:

`path=D:/bld/eccodes_1616616234353/_h_env/Library/share/eccodes/definitions`

This path does not exist in my computer. I don't even have a `bld` folder so I'm not sure where this is coming from. Actually, this has been an issue for a few months but I've always been manually setting the ECCODES_DEFINITION_PATH parameter to avoid this error.

To be clear, I also did this in a new virtual environment but the error is always there. I'm not sure if it's just my computer because I don't see anyone else having this issue. Maybe it's also because it's Windows 8? I can't update the OS the computer is from my office.

**Comment by piyushrpt** [comment]
I referred to the path that you provided. This seems to be a common issue on Windows with eccodes and not related to mintpy. You will find plenty of similar issues on other github repos that use eccodes.

**Comment by pbrotoisworo** [comment]
Okay good to know that it's probably Windows related. I'll stick to this workaround for now. My current method seems to be working since the error only appears if I run `smallbaselineApp.py` directly without my scripts.

Thank you for your suggestions also. To clarify, I call it using the terminal command, but I use `subprocess.Popen()` to run terminal commands so it is still within Python. I'll just edit the first post and I'll just close this issue.
