### ISSUE TITLE
save_gdal.py does not work with hyp3 data

### ISSUE THREAD

**Issue by pbrotoisworo** [insarlab/MintPy#644]
When working with hyp3 data it is in UTM but `save_gdal.py` seems to be hardcoded to be EPSG:4326 only. This results in invalid output for GIS software such as QGIS or ArcMap.

It can be seen in this line:
https://github.com/insarlab/MintPy/blob/ab1276e917b9a05dd1f8527d3161c3608523a241/mintpy/save_gdal.py#L90

I managed to load the data into QGIS when I modified the line to use the appropriate EPSG code. I took a look at the `attr` variable and I saw that there is an attribute for `UTM_ZONE`. I do not see if there is any option to track EPSG.

* Version of MintPy: MintPy release version v1.3.1, release date 2021-08-02s

**Comment by pbrotoisworo** [comment]
Just an update. I explored the code and I see where this can be inserted. Please correct me if I'm wrong.

in `readfile.py` the spatial reference attributes are being loaded from the raster file after this line
https://github.com/insarlab/MintPy/blob/ab1276e917b9a05dd1f8527d3161c3608523a241/mintpy/utils/readfile.py#L1353

There can be a quick line that is inserted:
```python
# Cast EPSG code to integer then save attribute
atr['EPSG'] = int(srs.GetAttrValue('AUTHORITY',1))
```

The function which is used to create the raster using GDAL is this:
https://github.com/insarlab/MintPy/blob/ab1276e917b9a05dd1f8527d3161c3608523a241/mintpy/save_gdal.py#L65

The attribute can be called in `array2raster`. Maybe an extra argument can be added?
```python
def array2raster(array, inps.outfile, inps.out_format, rasterOrigin, xStep, yStep, atr['EPSG']):
```

Also the docstring about the metadata would have to be updated regarding these changes. If you want I can do a PR.

**Comment by yunjunz** [comment]
Hi @pbrotoisworo, your solutions look great to me. Please feel free to issue a PR for it.

Very minor suggestions:
1. use `atr['EPSG'] = srs.GetAttrValue('AUTHORITY' ,1)` without `int()` to be able to handle files without projection info.
2. in `save_gdal.array2raster()`, use `EPSG=4326` as argument with default value.
