### ISSUE TITLE
set reference point with mintpy.reference.lalo

### ISSUE THREAD

**Issue by cirrusasf** [insarlab/MintPy#668]
**Description of the problem**
Users would like to use mintpy.reference.lalo to the reference point. The current lat and lon in this setting is in projected coordinates. This misleads users. I suggest the team to add the new setting to allow users to use longitude /latitude in WRG 84 to   set the reference point. 

**Full script that generated the error**

```
PASTE CODE HERE
```

**Full error message**

```
PASTE ERROR MESSAGE HERE
```

**System information**

* Operating system: 
* Python environment: 
* Version of MintPy: 
* Your custom / default template file (if the bug is related to a specific dataset):

**Comment by yunjunz** [comment]
Please use the `feature_request` template for new features, with more detailed information, e.g. for HyP3 products in UTM (I guess?).
