### ISSUE TITLE
Error Inversion

### ISSUE THREAD

**Issue by alejobeap** [insarlab/MintPy#679]
Dear @yunjunz 
I have again this error in the inversion (#546) processing, as you mentioned I have made multilook to the files: lon, lat los to the same azimuth and range (4 x 16)
![image](https://user-images.githubusercontent.com/65787135/136856267-2b8c364a-6c8c-45cb-8492-091f2a5e622e.png)

raceback (most recent call last):
  File "/home/isce/tools/MintPy/mintpy/smallbaselineApp.py", line 1255, in <module>
    main(sys.argv[1:])
  File "/home/isce/tools/MintPy/mintpy/smallbaselineApp.py", line 1237, in main
    app.run(steps=inps.runSteps)
  File "/home/isce/tools/MintPy/mintpy/smallbaselineApp.py", line 1044, in run
    self.run_network_inversion(sname)
  File "/home/isce/tools/MintPy/mintpy/smallbaselineApp.py", line 555, in run_network_inversion
    mintpy.ifgram_inversion.main(iargs)
  File "/home/isce/tools/MintPy/mintpy/ifgram_inversion.py", line 1193, in main
    ifgram_inversion(inps)
  File "/home/isce/tools/MintPy/mintpy/ifgram_inversion.py", line 1110, in ifgram_inversion
    ts, inv_quality, num_inv_ifg = ifgram_inversion_patch(**data_kwargs)[:-1]
  File "/home/isce/tools/MintPy/mintpy/ifgram_inversion.py", line 798, in ifgram_inversion_patch
    chunk_size=100000)
  File "/home/isce/tools/MintPy/mintpy/ifgram_inversion.py", line 696, in calc_weight
    L = int(stack_obj.metadata['ALOOKS']) * int(stack_obj.metadata['RLOOKS'])
KeyError: 'ALOOKS'

the information for ifgramStack.h5

 **info.py inputs/ifgramStack.h5** 
******************** Basic File Info ************************
file name: /mnt/nas_insar/TX_Procesamiento/Cotopaxi_TX/inputs/ifgramStack.h5
file type: ifgramStack
coordinates : RADAR

******************** HDF5 File Structure ********************
Attributes in / level:
  ANTENNA_SIDE                                    -1
  AZIMUTH_PIXEL_SIZE                              2.2167761649145166
  CENTER_LINE_UTC                                 39587.0
  DATA_TYPE                                       float32
  DATE12                                          200910-201106
  EARTH_RADIUS                                    6337069.751421896
  FILE_LENGTH                                     1696
  FILE_PATH                                       /mnt/nas_insar/TX_Procesamiento/Cotopaxi_TX/Igrams/20200910_20201106/filt_20200910_20201106_snaphu.unw
  FILE_TYPE                                       ifgramStack
  HEADING                                         -168.84432009494662
  HEIGHT                                          511612.94733224733
  ISCE_VERSION                                    Release: 2.3, svn-2531, 20190112. Current: svn-2531.
  LENGTH                                          1696
  OG_FILE_PATH                                    /mnt/nas_insar/TX_Procesamiento/Cotopaxi_TX/Igrams/20200910_20201106/filt_20200910_20201106_snaphu.unw
  PLATFORM                                        tsx1
  POLARIZATION                                    VV
  PRF                                             3468.62720959596
  PROCESSOR                                       isce
  PROJECT_NAME                                    smallbaseline_Cotopaxi_TX
  P_BASELINE_BOTTOM_HDR                           -460.40779120859287
  P_BASELINE_TOP_HDR                              -461.2883015090358
  RANGE_PIXEL_SIZE                                1.3641053359701238
  REF_X                                           98
  REF_Y                                           1215
  STARTING_RANGE                                  660350.7981230943
  WAVELENGTH                                      0.03106658115133631
  WIDTH                                           680
  access_mode                                     read
  altitude                                        511612.94733224733
  azimuthPixelSize                                2.2167761649145166
  azimuthResolution                               2.392
  beam_mode                                       SM
  byte_order                                      l
  data_type                                       float
  earthRadius                                     6337069.751421896
  family                                          unwimage
  file_name                                       /mnt/nas_insar/TX_Procesamiento/Cotopaxi_TX/Igrams/20200910_20201106/filt_20200910_20201106_snaphu.unw
  image_type                                      unw
  length                                          1696
  mintpy.compute.cluster                          auto
  mintpy.compute.config                           auto
  mintpy.compute.maxMemory                        auto
  mintpy.compute.numWorker                        auto
  mintpy.deramp                                   quadratic
  mintpy.deramp.maskFile                          auto
  mintpy.geocode                                  auto
  mintpy.geocode.SNWE                             auto
  mintpy.geocode.fillValue                        auto
  mintpy.geocode.interpMethod                     auto
  mintpy.geocode.laloStep                         auto
  mintpy.load.autoPath                            auto
  mintpy.load.azAngleFile                         ./merged/geom_reference/los_10.rdr
  mintpy.load.azOffFile                           auto
  mintpy.load.baselineDir                         ./baselines
  mintpy.load.bperpFile                           auto
  mintpy.load.compression                         auto
  mintpy.load.connCompFile                        ./Igrams/*/filt_*.unw.conncomp
  mintpy.load.corFile                             ./Igrams/*/filt_*.cor
  mintpy.load.demFile                             ./merged/geom_reference/hgt_10.rdr
  mintpy.load.incAngleFile                        ./merged/geom_reference/los_10.rdr
  mintpy.load.intFile                             auto
  mintpy.load.ionoFile                            auto
  mintpy.load.lookupXFile                         ./merged/geom_reference/lon_10.rdr
  mintpy.load.lookupYFile                         ./merged/geom_reference/lat_10.rdr
  mintpy.load.magFile                             auto
  mintpy.load.metaFile                            ./merged/SLC/20200910/referenceShelve/data.dat
  mintpy.load.offSnrFile                          auto
  mintpy.load.processor                           isce
  mintpy.load.rgOffFile                           auto
  mintpy.load.shadowMaskFile                      ./merged/geom_reference/shadowMask_10.rdr
  mintpy.load.unwFile                             ./Igrams/*/filt_*.unw
  mintpy.load.updateMode                          auto
  mintpy.load.waterMaskFile                       auto
  mintpy.load.xstep                               auto
  mintpy.load.ystep                               auto
  mintpy.network.aoiLALO                          auto
  mintpy.network.aoiYX                            auto
  mintpy.network.areaRatioBased                   auto
  mintpy.network.coherenceBased                   yes
  mintpy.network.connNumMax                       auto
  mintpy.network.endDate                          auto
  mintpy.network.excludeDate                      auto
  mintpy.network.excludeIfgIndex                  auto
  mintpy.network.keepMinSpanTree                  auto
  mintpy.network.maskFile                         auto
  mintpy.network.minAreaRatio                     auto
  mintpy.network.minCoherence                     0.5
  mintpy.network.perpBaseMax                      auto
  mintpy.network.referenceFile                    auto
  mintpy.network.startDate                        20200910
  mintpy.network.tempBaseMax                      auto
  mintpy.networkInversion.maskDataset             coherence
  mintpy.networkInversion.maskThreshold           auto
  mintpy.networkInversion.minNormVelocity         auto
  mintpy.networkInversion.minNumPixel             auto
  mintpy.networkInversion.minRedundancy           auto
  mintpy.networkInversion.minTempCoh              auto
  mintpy.networkInversion.residualNorm            auto
  mintpy.networkInversion.shadowMask              auto
  mintpy.networkInversion.waterMaskFile           auto
  mintpy.networkInversion.weightFunc              auto
  mintpy.plot                                     auto
  mintpy.reference.coherenceFile                  auto
  mintpy.reference.date                           20200910
  mintpy.reference.lalo                           auto
  mintpy.reference.maskFile                       auto
  mintpy.reference.minCoherence                   auto
  mintpy.reference.yx                             auto
  mintpy.residualRMS.cutoff                       auto
  mintpy.residualRMS.deramp                       auto
  mintpy.residualRMS.maskFile                     auto
  mintpy.save.hdfEos5                             auto
  mintpy.save.hdfEos5.subset                      auto
  mintpy.save.hdfEos5.update                      auto
  mintpy.save.kmz                                 yes
  mintpy.solidEarthTides                          auto
  mintpy.subset.lalo                              auto
  mintpy.subset.yx                                auto
  mintpy.topographicResidual                      auto
  mintpy.topographicResidual.excludeDate          auto
  mintpy.topographicResidual.phaseVelocity        auto
  mintpy.topographicResidual.pixelwiseGeometry    auto
  mintpy.topographicResidual.polyOrder            auto
  mintpy.topographicResidual.stepFuncDate         auto
  mintpy.troposphericDelay.gacosDir               auto
  mintpy.troposphericDelay.looks                  auto
  mintpy.troposphericDelay.method                 height_correlation
  mintpy.troposphericDelay.minCorrelation         auto
  mintpy.troposphericDelay.polyOrder              auto
  mintpy.troposphericDelay.weatherDir             auto
  mintpy.troposphericDelay.weatherModel           auto
  mintpy.unwrapError.bridgePtsRadius              auto
  mintpy.unwrapError.method                       auto
  mintpy.unwrapError.numSample                    auto
  mintpy.unwrapError.ramp                         auto
  mintpy.unwrapError.waterMaskFile                auto
  mintpy.velocity.bootstrap                       auto
  mintpy.velocity.bootstrapCount                  auto
  mintpy.velocity.endDate                         auto
  mintpy.velocity.excludeDate                     auto
  mintpy.velocity.startDate                       20200910
  name                                            unwimage_name
  number_bands                                    2
  orbitNumber                                     78966
  polarization                                    VV
  prf                                             3468.62720959596
  radarWavelength                                 0.03106658115133631
  rangePixelSize                                  1.3641053359701238
  rangeResolution                                 1873702.8625
  relative_orbit                                  None
  scheme                                          BIL
  startUTC                                        2021-09-10 10:59:45.457449
  startingRange                                   660350.7981230943
  stopUTC                                         2021-09-10 10:59:50.413012
  trackNumber                                     None
  width                                           680
  xmax                                            680
  xmin                                            0

HDF5 dataset "/bperp               ": shape (164,)              , dtype <float32>
HDF5 dataset "/coherence           ": shape (164, 1696, 680)    , dtype <float32>
  MODIFICATION_TIME    1633986229.815202

HDF5 dataset "/connectComponent    ": shape (164, 1696, 680)    , dtype <int16>
  MODIFICATION_TIME    1633986230.8177624

HDF5 dataset "/date                ": shape (164, 2)            , dtype <|S8>
HDF5 dataset "/dropIfgram          ": shape (164,)              , dtype <bool>
HDF5 dataset "/unwrapPhase         ": shape (164, 1696, 680)    , dtype <float32>
  MODIFICATION_TIME    1633986228.81245

**and the information for geometry.h5:**

info.py inputs/geometryRadar.h5
******************** Basic File Info ************************
file name: /mnt/nas_insar/TX_Procesamiento/Cotopaxi_TX/inputs/geometryRadar.h5
file type: geometry
coordinates : RADAR

******************** HDF5 File Structure ********************
Attributes in / level:
  ALOOKS                                          4
  ANTENNA_SIDE                                    -1
  AZIMUTH_PIXEL_SIZE                              8.867104659658066
  CENTER_LINE_UTC                                 39587.0
  DATA_TYPE                                       float64
  EARTH_RADIUS                                    6337069.751421896
  FILE_LENGTH                                     1696
  FILE_PATH                                       /mnt/nas_insar/TX_Procesamiento/Cotopaxi_TX/merged/geom_reference/hgt_10.rdr
  FILE_TYPE                                       geometry
  HEADING                                         -168.84432009494662
  HEIGHT                                          511612.94733224733
  ISCE_VERSION                                    Release: 2.3, svn-2531, 20190112. Current: svn-2531.
  LENGTH                                          1696
  OG_FILE_PATH                                    /mnt/nas_insar/TX_Procesamiento/Cotopaxi_TX/merged/geom_reference/hgt.rdr
  PLATFORM                                        tsx1
  POLARIZATION                                    VV
  PRF                                             3468.62720959596
  PROCESSOR                                       isce
  PROJECT_NAME                                    smallbaseline_Cotopaxi_TX
  RANGE_PIXEL_SIZE                                21.82568537552198
  RLOOKS                                          16
  STARTING_RANGE                                  660350.7981230943
  WAVELENGTH                                      0.03106658115133631
  WIDTH                                           680
  XMAX                                            679
  XMIN                                            0
  YMAX                                            1695
  YMIN                                            0
  access_mode                                     read
  altitude                                        511612.94733224733
  azimuthPixelSize                                2.2167761649145166
  azimuthResolution                               2.392
  beam_mode                                       SM
  byte_order                                      l
  data_type                                       DOUBLE
  description                                     ['Pixel-by-pixel height in meters.']
  earthRadius                                     6337069.751421896
  extra_file_name                                 /mnt/nas_insar/TX_Procesamiento/Cotopaxi_TX/merged/geom_reference/hgt.rdr.vrt
  family                                          image
  file_name                                       /mnt/nas_insar/TX_Procesamiento/Cotopaxi_TX/merged/geom_reference/hgt.rdr
  length                                          6785
  mintpy.compute.cluster                          auto
  mintpy.compute.config                           auto
  mintpy.compute.maxMemory                        auto
  mintpy.compute.numWorker                        auto
  mintpy.deramp                                   quadratic
  mintpy.deramp.maskFile                          auto
  mintpy.geocode                                  auto
  mintpy.geocode.SNWE                             auto
  mintpy.geocode.fillValue                        auto
  mintpy.geocode.interpMethod                     auto
  mintpy.geocode.laloStep                         auto
  mintpy.load.autoPath                            auto
  mintpy.load.azAngleFile                         ./merged/geom_reference/los_10.rdr
  mintpy.load.azOffFile                           auto
  mintpy.load.baselineDir                         ./baselines
  mintpy.load.bperpFile                           auto
  mintpy.load.compression                         auto
  mintpy.load.connCompFile                        ./Igrams/*/filt_*.unw.conncomp
  mintpy.load.corFile                             ./Igrams/*/filt_*.cor
  mintpy.load.demFile                             ./merged/geom_reference/hgt_10.rdr
  mintpy.load.incAngleFile                        ./merged/geom_reference/los_10.rdr
  mintpy.load.intFile                             auto
  mintpy.load.ionoFile                            auto
  mintpy.load.lookupXFile                         ./merged/geom_reference/lon_10.rdr
  mintpy.load.lookupYFile                         ./merged/geom_reference/lat_10.rdr
  mintpy.load.magFile                             auto
  mintpy.load.metaFile                            ./merged/SLC/20200910/referenceShelve/data.dat
  mintpy.load.offSnrFile                          auto
  mintpy.load.processor                           isce
  mintpy.load.rgOffFile                           auto
  mintpy.load.shadowMaskFile                      ./merged/geom_reference/shadowMask_10.rdr
  mintpy.load.unwFile                             ./Igrams/*/filt_*.unw
  mintpy.load.updateMode                          auto
  mintpy.load.waterMaskFile                       auto
  mintpy.load.xstep                               auto
  mintpy.load.ystep                               auto
  mintpy.network.aoiLALO                          auto
  mintpy.network.aoiYX                            auto
  mintpy.network.areaRatioBased                   auto
  mintpy.network.coherenceBased                   yes
  mintpy.network.connNumMax                       auto
  mintpy.network.endDate                          auto
  mintpy.network.excludeDate                      auto
  mintpy.network.excludeIfgIndex                  auto
  mintpy.network.keepMinSpanTree                  auto
  mintpy.network.maskFile                         auto
  mintpy.network.minAreaRatio                     auto
  mintpy.network.minCoherence                     0.5
  mintpy.network.perpBaseMax                      auto
  mintpy.network.referenceFile                    auto
  mintpy.network.startDate                        20200910
  mintpy.network.tempBaseMax                      auto
  mintpy.networkInversion.maskDataset             coherence
  mintpy.networkInversion.maskThreshold           auto
  mintpy.networkInversion.minNormVelocity         auto
  mintpy.networkInversion.minNumPixel             auto
  mintpy.networkInversion.minRedundancy           auto
  mintpy.networkInversion.minTempCoh              auto
  mintpy.networkInversion.residualNorm            auto
  mintpy.networkInversion.shadowMask              auto
  mintpy.networkInversion.waterMaskFile           auto
  mintpy.networkInversion.weightFunc              auto
  mintpy.plot                                     auto
  mintpy.reference.coherenceFile                  auto
  mintpy.reference.date                           20200910
  mintpy.reference.lalo                           auto
  mintpy.reference.maskFile                       auto
  mintpy.reference.minCoherence                   auto
  mintpy.reference.yx                             auto
  mintpy.residualRMS.cutoff                       auto
  mintpy.residualRMS.deramp                       auto
  mintpy.residualRMS.maskFile                     auto
  mintpy.save.hdfEos5                             auto
  mintpy.save.hdfEos5.subset                      auto
  mintpy.save.hdfEos5.update                      auto
  mintpy.save.kmz                                 yes
  mintpy.solidEarthTides                          auto
  mintpy.subset.lalo                              auto
  mintpy.subset.yx                                auto
  mintpy.topographicResidual                      auto
  mintpy.topographicResidual.excludeDate          auto
  mintpy.topographicResidual.phaseVelocity        auto
  mintpy.topographicResidual.pixelwiseGeometry    auto
  mintpy.topographicResidual.polyOrder            auto
  mintpy.topographicResidual.stepFuncDate         auto
  mintpy.troposphericDelay.gacosDir               auto
  mintpy.troposphericDelay.looks                  auto
  mintpy.troposphericDelay.method                 height_correlation
  mintpy.troposphericDelay.minCorrelation         auto
  mintpy.troposphericDelay.polyOrder              auto
  mintpy.troposphericDelay.weatherDir             auto
  mintpy.troposphericDelay.weatherModel           auto
  mintpy.unwrapError.bridgePtsRadius              auto
  mintpy.unwrapError.method                       auto
  mintpy.unwrapError.numSample                    auto
  mintpy.unwrapError.ramp                         auto
  mintpy.unwrapError.waterMaskFile                auto
  mintpy.velocity.bootstrap                       auto
  mintpy.velocity.bootstrapCount                  auto
  mintpy.velocity.endDate                         auto
  mintpy.velocity.excludeDate                     auto
  mintpy.velocity.startDate                       20200910
  name                                            image_name
  number_bands                                    1
  orbitNumber                                     78966
  polarization                                    VV
  prf                                             3468.62720959596
  radarWavelength                                 0.03106658115133631
  rangePixelSize                                  1.3641053359701238
  rangeResolution                                 1873702.8625
  relative_orbit                                  None
  scheme                                          BIP
  startUTC                                        2021-09-10 10:59:45.457449
  startingRange                                   660350.7981230943
  stopUTC                                         2021-09-10 10:59:50.413012
  trackNumber                                     None
  width                                           10890
  xmax                                            10890
  xmin                                            0

HDF5 dataset "/azimuthAngle        ": shape (1696, 680)         , dtype <float32>
HDF5 dataset "/height              ": shape (1696, 680)         , dtype <float32>
HDF5 dataset "/incidenceAngle      ": shape (1696, 680)         , dtype <float32>
HDF5 dataset "/latitude            ": shape (1696, 680)         , dtype <float32>
HDF5 dataset "/longitude           ": shape (1696, 680)         , dtype <float32>
HDF5 dataset "/shadowMask          ": shape (1696, 680)         , dtype <bool>
HDF5 dataset "/slantRangeDistance  ": shape (1696, 680)         , dtype <float32>

Could you help me what should I do because on another stack it works correctly.

Thanks

Pedro

_Originally posted by @alejobeap in https://github.com/insarlab/MintPy/issues/546#issuecomment-940455181_

**Comment by yunjunz** [comment]
Similar processing-related posts should be added to the same issue, instead of creating new ones.
