### ISSUE TITLE
plot & save to pic section of smallbaselineApp fails with "numWorker = all"

### ISSUE THREAD

**Issue by EJFielding** [insarlab/MintPy#689]
**Description of the problem**

I used the Dask system to speed my MintPy processing with `smallbaselineApp.py`. It worked great until the end when it started the final `plot & save to pic` section. Something in that section was unable to understand the "numWorker = all" in my configuration file.

This is the configuration that I had specified:
```
mintpy.compute.cluster   = local #[local / slurm / pbs / lsf / none], auto for none, cluster type
mintpy.compute.numWorker = all #[int > 1 / all], auto for 4 (local) or 40 (non-local), num of workers
mintpy.compute.config    = auto #[none / slurm / pbs / lsf ], auto for none (same as cluster), config name
```

**Full script that generated the error**

```
smallbaselineApp.py Haywar_23502_02-s2UAVSAR.txt
```

**Full error message**

```
******************** plot & save to pic ********************
Traceback (most recent call last):
  File "/home/fielding/tools/MintPy/mintpy/smallbaselineApp.py", line 1286, in <module>
    main(sys.argv[1:])
  File "/home/fielding/tools/MintPy/mintpy/smallbaselineApp.py", line 1274, in main
    app.plot_result()
  File "/home/fielding/tools/MintPy/mintpy/smallbaselineApp.py", line 1191, in plot_result
    num_workers = int(self.template['mintpy.compute.numWorker'])
ValueError: invalid literal for int() with base 10: 'all'

```

**System information**

* Operating system:  Linux-CentOS
* Python environment:  conda
* Version of MintPy:  MintPy release version v1.2.3-283, release date 2021-11-04
* Your custom / default template file (if the bug is related to a specific dataset): 
[Haywar_23502_02-s2UAVSAR.txt](https://github.com/insarlab/MintPy/files/7492765/Haywar_23502_02-s2UAVSAR.txt)

**Comment by yunjunz** [comment]
Thank you @EJFielding for reporting this. I was able to re-produce the same issue. It is now fixed by the PR above.

**Comment by EJFielding** [comment]
Thanks @yunjunz for the fix.
