### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'float128' in coord.py

### ISSUE THREAD

**Issue by pbrotoisworo** [insarlab/MintPy#698]
I just updated my MintPy and now I have this error where NumPy has no attribute `float128`.
It comes from this line:
https://github.com/insarlab/MintPy/blob/d2727e06b8fea2d74ff870e5c989bbd9485515eb/mintpy/objects/coord.py#L89

I looked into it and it seems that float128 is not supported on Windows OS. I removed `np.float128` from the line and my analysis works with no error.

See related Github issue from other repo for reference: https://github.com/winpython/winpython/issues/613

If precision is still required up to float128 then here is a possible solution: https://github.com/quantumlib/Cirq/issues/1511#issuecomment-481450449

**Comment by yunjunz** [comment]
Thank you @pbrotoisworo for the bug report and proposed fix. `np.float128` is not really used anywhere in the mintpy code, so there is no issue with removing it. But I prefer the replacement to `np.longdouble` solution, to remind us of this issue and for future reference. Could you issue a PR for your fix?
