### ISSUE TITLE
asc_desc2horz_vert: compute average temporal coherence

### ISSUE THREAD

**Issue by forrestfwilliams** [insarlab/MintPy#716]
In addition to the horizontal/vertical velocity maps produced by `asc_desc2horz_vert.py` I find that I often want an average temporal coherence map that covers the same area as well. I would like to take the temporal coherence maps, co-register them in a similar manner to the asc/desc velocity maps, then average them to get the average temporal coherence. @yunjunz this doesn't necessarily fall within the aim of the `asc_desc2horz_vert.py` script but it does already contain many of needed utilities and I would like to get your thoughts on this before I proceed.

**Comment by yunjunz** [comment]
Hi @forrestfwilliams, `asc_desc2horz_vert.py` applies the LOS2EU decomposition only. Based on your description, if you have two temporal coherence file in the same spatial coverage and resolution, calculating the average of the two can be done as below:

```bash
add.py tempCoh1.h5 tempCoh2.h5 -o tempCohAdd.h5
image_math.py tempCohAdd.h5 '/' 2 -o tempCohAvg.h5
```

**Comment by forrestfwilliams** [comment]
Haha yes that makes a lot more sense. Thanks for pointing me in the right direction!
