### ISSUE TITLE
Hardcoded values sometimes do not work

### ISSUE THREAD

**Issue by mirzaees** [insarlab/MintPy#718]
**Description of the issue**

There are a few things that are hardcoded and sometimes do not adapt with full res data. 
So I sometimes get error or the step is skipped. I am listing two here:

1. The step size in solid earth tide function (It is a large value, when I set it to 3e2, it works):
https://github.com/insarlab/MintPy/blob/4357b8c726dec8a3f936770e3f3dda92882685b7/mintpy/solid_earth_tides.py#L308

2. The min_area in label_conn_comp (It is a large value, when I set it to 2.5e2, it works):
https://github.com/insarlab/MintPy/blob/4357b8c726dec8a3f936770e3f3dda92882685b7/mintpy/unwrap_error_phase_closure.py#L402

**Describe the solution you'd like**

I am not sure what is a good solution, whether to change the hardcoded values or make them as an option in template.
@yunjunz please let me know what you think may solve this issue and I will be happy to help. Although you know better where else this could happen.

**Comment by yunjunz** [comment]
Hi @mirzaees, for `solid_earth_tides.py`, an easy solution could be calculating a value adaptively based on the input file info, e.g. `pixel_step = ut.round_to_1(abs(float(atr['Y_STEP'])) * 30)`. 

For the `unwrap_error_phase_closure.py`, adding a template option sounds good to me.

**Comment by mirzaees** [comment]
Thank you @yunjunz, I will make a PR for this
