### ISSUE TITLE
Problem with timeseries2velocity when excluding dates and outputting residuals

### ISSUE THREAD

**Issue by olliestephenson** [insarlab/MintPy#739]
**Description of the problem**

When running `timeseries2velocity.py` with both `--save-res` and `--exclude` parameters, we have an issue with the resulting residuals output. 

At [L.483](https://github.com/insarlab/MintPy/blob/b33fefc4479c08448289190d586a628d2c60ffa8/mintpy/timeseries2velocity.py#L483) we layout an hdf file for saving the residuals, however we use the original timeseries file as the reference file. This creates an hdf file with the full number of dates, not taking into account the excluded dates. At [L.700](https://github.com/insarlab/MintPy/blob/b33fefc4479c08448289190d586a628d2c60ffa8/mintpy/timeseries2velocity.py#L700) when we write to this file, we only write residuals for the dates we haven't excluded, leaving the final N date entries empty (where N is the number of dates we have excluded). This means that the residuals no longer line up with the correct dates. 

I believe a straightforward solution to this would be to pass the shape of the timeseries with the excluded dates removed to `layout_hdf5` via the `ds_name_dict` argument, rather than just passing the `ref_file`. I think we'd also have to pass the metadata from the original timeseries file, although I'm not sure if I'm missing some aspect of the data structure here.

**Comment by yunjunz** [comment]
Thank you for pointing out this issue @olliestephenson! Note that `ds_name_dict` from `model2hdf5_dataset()` is for the time function parameters, not for time series. But surely we could prepare a set of ds_name_dict for this purpose.

On the one hand, having the residual TS file in a different size than the input TS file is special and can be a useful feature (for more advanced iterative time series cleaning); on the other hand, it could also be confusing to have this inconsistency between inputs and outputs. What do you think @yuankailiu?

**Comment by yuankailiu** [comment]
I just try to create a new `ds_name_dict_R` (a new proposed dictionary just for the time-series residuals output) to feed into `layout_hdf5 ()`. So that it is not just based on the `ref_file`, but also taking into account the `inps.excludeDate`.

This is done here in this [temporary branch](https://github.com/yuankailiu/MintPy/commit/83f75b04062694ee8c5ac1db1b674699e7757934)

I tested it and it works. But do you think this is a proper location to modify?

**Comment by yunjunz** [comment]
Thank you @yuankailiu for the follow-up. It seems to me that we could just change 

from:

https://github.com/insarlab/MintPy/blob/2499eeb7ed1ff03d1a341505485e1f9e7c346cba/mintpy/timeseries2velocity.py#L483

to 

```python
    ds_name_dict = {
        "date"       : [np.string_, (num_date,), np.array(inps.dateList, dtype=np.string_)]
        "timeseries" : [np.float32, (num_date, length, width), None]
    }
    writefile.layout_hdf5(inps.res_file, ds_name_dict=ds_name_dict, metadata=atrR)
```

Could you please confirm, and maybe issue a PR for it?

**Comment by yuankailiu** [comment]
> ```python
>     ds_name_dict = {
>         "bperp"         : [np.float32, (num_date,), np.array(inps.dateList, dtype=np.float32)],
>         "date"           : [np.string_, (num_date,), np.array(inps.dateList, dtype=np.string_)],
>         "timeseries" : [np.float32, (num_date, length, width), None]
>     }
>     writefile.layout_hdf5(inps.res_file, ds_name_dict=ds_name_dict, metadata=atrR)
> ```

This will work. But the data type of the "date" is giving me an error when creating the dataset.

```
--------------------------------------------------
create HDF5 file: zzz_res.h5 with w mode
create dataset  : bperp      of <class 'numpy.float32'>   in size of (198,)               with compression = None
(198,) (198,) bperp <class 'numpy.float32'>
create dataset  : date       of <class 'numpy.bytes_'>    in size of (198,)               with compression = None
(198,) (198,) date <class 'numpy.bytes_'>
Traceback (most recent call last):
  File "/home/ykliu/apps/MintPy/mintpy/timeseries2velocity.py", line 906, in <module>
    main(sys.argv[1:])
  File "/home/ykliu/apps/MintPy/mintpy/timeseries2velocity.py", line 895, in main
    run_timeseries2time_func(inps)
  File "/home/ykliu/apps/MintPy/mintpy/timeseries2velocity.py", line 491, in run_timeseries2time_func
    writefile.layout_hdf5(inps.res_file, ds_name_dict=ds_name_dict, metadata=atrR)
  File "/home/ykliu/apps/MintPy/mintpy/utils/writefile.py", line 359, in layout_hdf5
    ds = f.create_dataset(key,
  File "/home/ykliu/apps/miniconda3/envs/insar/lib/python3.8/site-packages/h5py/_hl/group.py", line 136, in create_dataset
    dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
  File "/home/ykliu/apps/miniconda3/envs/insar/lib/python3.8/site-packages/h5py/_hl/dataset.py", line 118, in make_new_dset
    tid = h5t.py_create(dtype, logical=1)
  File "h5py/h5t.pyx", line 1632, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1654, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1687, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1506, in h5py.h5t._c_string
ValueError: Size must be positive (size must be positive)
```

I cannot figure out the correct data type, could you help me? Thanks!

**Comment by yunjunz** [comment]
Do you have the code change somewhere on Github that I could take a look at?

**Comment by yuankailiu** [comment]
Please look at here: https://github.com/yuankailiu/MintPy/commit/35950bd0feb36685719d61fcd85a8fe87b36f0e2

Thanks!

**Comment by yunjunz** [comment]
I got the same error as you. Using `np.dtype('S8')` instead of `np.string_` seems to fix the issue. Note the `bperp` dataset is not required, and the current value you had is not right. 

We should allow flexible character length for the `date` dataset, as it can be in `YYYYMMDDTHHMM` format, e.g. for UAVSAR data. 

```python
date_len = len(inps.dateList[0])
ds_name_dict = {
        "date"       : [np.dtype(f'S{date_len}'), (num_date,), np.array(inps.dateList, dtype=np.string_)]
        "timeseries" : [np.float32,               (num_date, length, width), None]
    }
```
