### ISSUE TITLE
asc_desc2horz_vert: examples

### ISSUE THREAD

**Issue by falkamelung** [insarlab/MintPy#74]
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
1. asc_desc2horz_vert.py
In the example use geo_* for geocoded
```
example:
  #geocode asc/desc data into the same spatial resolution and coverage
  geocode.py AlosAT424/velocity -x 0.00027778 -y -0.00027778 --bbox 32.0 32.5 130.1 130.5 -o vel_AlosAT424.h5
  geocode.py AlosDT73/velocity  -x 0.00027778 -y -0.00027778 --bbox 32.0 32.5 130.1 130.5 -o vel_AlosDT73.h5

  asc_desc2horz_vert.py  vel_AlosAT424_masked.h5  vel_AlosDT73_masked.h5
  asc_desc2horz_vert.py  vel_EnvAT134_masked.h5   vel_EnvAT256_masked.h5  16
```
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

**Comment by yunjunz** [comment]
Hi @falkamelung,

I have added another line of example for files with `geo_` in the names. The previous filenames are still kept because for the geocoded dataset, there is no `geo_` in the names.

For each minor issue, we could create an independent issue, for the clear discussion flow.
