### ISSUE TITLE
Error : "PyAPS: Mask array size mismatch"

### ISSUE THREAD

**Issue by ThreeIcug** [insarlab/MintPy#773]
**Description of the problem**
I try the GMTSAR with MintPy.  When finish the download of ERA file and do run_tropospheric_delay_correction,  it print the error .   But when I  run  smallbaselineApp.py  with  --start correct_troposphere, the tropospheric correction is ok. And it print another error at the step of plot & save to pic.

### ERROR 1

```bash
------------------------------------------------------------------------------
calculating absolute delay for each date using PyAPS (Jolivet et al., 2011; 2014) ...
number of grib files used: 10
Traceback (most recent call last):
  File "/opt/MintPy/mintpy/smallbaselineApp.py", line 1298, in <module>
    main(sys.argv[1:])
  File "/opt/MintPy/mintpy/smallbaselineApp.py", line 1280, in main
    app.run(steps=inps.runSteps)
  File "/opt/MintPy/mintpy/smallbaselineApp.py", line 1069, in run
    self.run_tropospheric_delay_correction(sname)
  File "/opt/MintPy/mintpy/smallbaselineApp.py", line 821, in run_tropospheric_delay_correction
    tropo_pyaps3.main(iargs)
  File "/opt/MintPy/mintpy/tropo_pyaps3.py", line 846, in main
    calc_delay_timeseries(inps)
  File "/opt/MintPy/mintpy/tropo_pyaps3.py", line 764, in calc_delay_timeseries
    tropo_data = get_delay(grib_file,
  File "/opt/MintPy/mintpy/tropo_pyaps3.py", line 631, in get_delay
    aps_obj = pa.PyAPS(grib_file,
  File "/home/ti/miniconda3/envs/mintpy/lib/python3.10/site-packages/pyaps3/objects.py", line 84, in __init__
    assert self.mask.shape == (self.ny, self.nx), 'PyAPS: Mask array size mismatch'
AssertionError: PyAPS: Mask array size mismatch
------------------------------------------------------------------------------
```

### ERROR 2

```bash
------------------------------------------------------------------------------
Input data seems to be geocoded. Lookup file not needed.
view.py --dpi 150 --noverbose --nodisplay --update --memory 4.0 velocity.h5 --dem inputs/geometryGeo.h5 --mask maskTempCoh.h5 -u cm
WARNING: DEM file has a different size from the data file. This feature is only supported for single subplot, and not for multi-subplots.
    --> Ignore it and continue.
view.py --dpi 150 --noverbose --nodisplay --update --memory 4.0 temporalCoherence.h5 -c gray -v 0 1
view.py --dpi 150 --noverbose --nodisplay --update --memory 4.0 maskTempCoh.h5 -c gray -v 0 1
view.py --dpi 150 --noverbose --nodisplay --update --memory 4.0 inputs/geometryGeo.h5
Traceback (most recent call last):
  File "/opt/MintPy/mintpy/smallbaselineApp.py", line 1298, in <module>
    main(sys.argv[1:])
  File "/opt/MintPy/mintpy/smallbaselineApp.py", line 1286, in main
    app.plot_result()
  File "/opt/MintPy/mintpy/smallbaselineApp.py", line 1222, in plot_result
    mintpy.view.main(iargs)
  File "/opt/MintPy/mintpy/view.py", line 1711, in main
    obj.plot()
  File "/opt/MintPy/mintpy/view.py", line 1690, in plot
    plot_figure(j, self, metadata=self.atr)
  File "/opt/MintPy/mintpy/view.py", line 1304, in plot_figure
    data = read_data4figure(i_start, i_end, inps, metadata)
  File "/opt/MintPy/mintpy/view.py", line 1098, in read_data4figure
    data[i - i_start, :, :] = d
ValueError: could not broadcast input array from shape (1605,2160) into shape (3600,2340)
------------------------------------------------------------------------------
```

I check the ERA data,  such as ERA5_N30_N40_E90_E110_20210526_23.grb.
The information is 
ERA5_N30_N40_E90_E110_20210526_23.grb: x_min: 90 x_max: 110 x_inc: 0.25 name:  n_columns: 81
ERA5_N30_N40_E90_E110_20210526_23.grb: y_min: 30 y_max: 40 y_inc: 0.25 name:  n_rows: 41

In additional, I checked the geometryGeo.h5 and maskTempCoh.h5.
The information is 
  LAT_REF1                                   35.522499999977775
  LAT_REF2                                   35.522499999977775
  LAT_REF3                                   33.739166666677775
  LAT_REF4                                   33.739166666677775
  LENGTH                                     3210
  LON_REF1                                   99.84687499997779
  LON_REF2                                   96.84687499997779
  LON_REF3                                   99.84687499997779
  LON_REF4                                   96.84687499997779

I think the region of ERA5 can cover the data. 

**Full script that generated the error**

```
PASTE CODE HERE
```

**Full error message**

```
PASTE ERROR MESSAGE HERE
```

**System information**

* Operating system: 
* Python environment: 
* Version of MintPy: 
* Your custom / default template file (if the bug is related to a specific dataset):

**Comment by ThreeIcug** [comment]
I have sloved the problem. the reason is  the dem data has error.

**Comment by zNevermind** [comment]
Hello, I'm trying to run Mintpy with GMTSAR processor. I had the same problem,

**AssertionError: PyAPS: Mask array size mismatch**

How did you solve it?

DEM data was generated from GMTSAR.

Thanks.

**Comment by zNevermind** [comment]
> I have sloved the problem. the reason is the dem data has error.

Hello, I'm trying to run Mintpy with GMTSAR processor. I had the same problem,

AssertionError: PyAPS: Mask array size mismatch

How did you solve it?

DEM data was generated from GMTSAR.

Thanks.
