### ISSUE TITLE
smallbaselineApp.py cannot find ifgram.h5 file

### ISSUE THREAD

**Issue by KASHKASHOPTIMUS** [insarlab/MintPy#831]
From Aria-Tools Github repo
1.Run commands as per instructions given in jupyter docs for Insar time series analysis using mintpy and aria products
On Anaconda Prompt run command python ariaDownload.py -b "29.465237 30.051789 -96.253476 -94.613767" -m 30 -l 36 -s
20180101 -e 20211231 -o Download
2. After download another command on the anaconda prompt python ariaTSsetup.py -f L2_interseismic directory --mask Download
3. After geometric and interferrograms stacks are generated, we need to post location of these files on a configuration file that are used with smallbaselineApp.py command. -> smallbaselineApp.py Houston_validation.txt --dostep load_data

Expected behavior
The output of the script is ifgram.h5 hdf5 file and geometric hfd5 file which are used to prepare time series

* Operating system: Windows `0
* Python environment: conda
* Version of MintPy: <MintPy version v1.4.0, date 2022-08-04>
![bnmn](https://user-images.githubusercontent.com/107583734/185241681-cf6ec753-68da-4a4e-86e5-67776ede1f63.JPG)
![cxv](https://user-images.githubusercontent.com/107583734/185241729-cafbcdd9-5a6b-4cba-be09-8c7ba5316c1a.JPG)

**Comment by yunjunz** [comment]
Hi @KASHKASHOPTIMUS, could you re-run the loading process using the `prep_aria.py` command as printed out in the terminal message? This will give a more informative trace-back msg regarding the error.

**Comment by KASHKASHOPTIMUS** [comment]
Hey yunjunz prep_aria.py is giving me a GDAL cannot open file, please check if the syntax is correct
![nmm](https://user-images.githubusercontent.com/107583734/186015364-4b1a7b18-8382-4f23-a174-591e6091f151.JPG)

**Comment by KASHKASHOPTIMUS** [comment]
Also I would like you to know, with the Aria-tools installation I came across a bug which is setmetadatitem to update mode. I think Gdal is not able to read data as it is not in update mode

**Comment by KASHKASHOPTIMUS** [comment]
![new err](https://user-images.githubusercontent.com/107583734/186256554-deaac5f5-8106-45ef-b30c-9d3baee88e1d.JPG)

Hey this is a new error I am getting with smallbaselineApp.py <customtemplate> --dostep load_data

**Comment by yunjunz** [comment]
> Hey yunjunz prep_aria.py is giving me a GDAL cannot open file, please check if the syntax is correct

The syntax does not look right to me, please double check with the help from `prep_aria.py --help`.

> Also I would like you to know, with the Aria-tools installation I came across a bug which is setmetadatitem to update mode. I think Gdal is not able to read data as it is not in update mode

I am not familiar with this issue. `gdal` is required to load ARIA products, so you may want to communicate with the ARIA team and resolve your installation issue.

Close this issue as it does not seems related to mintpy itself.
