### ISSUE TITLE
no effect for mintpy.network.perpBaseMax 

### ISSUE THREAD

**Issue by miladmz** [insarlab/MintPy#834]
I set mintpy.network.perpBaseMax = 300 but I think it has no effect on interferograms : 
I plot the network and the max perpendicular baseline is  1636.72 m
![1](https://user-images.githubusercontent.com/43873834/185908559-eba63390-2e64-44c4-82a8-fdd0f63bafda.png)

also, mintpy.network.tempBaseMax = 73 and again no effect :
max temporal baseline: 48.0 days
I download data from ARIA and they have 3 different locations: "00055E-00029N", "00054E-00031N","00055E-00029N"
I think they should be in the same location, am I right? 
I run modify_network and ifg but finally, I got this export 
![2](https://user-images.githubusercontent.com/43873834/185914863-abbf6300-cdbe-4ef4-a895-5efe1a2127ac.png)
I think it's due to the perpendicular baseline!!!

**Comment by yunjunz** [comment]
Please follow the bug report template (https://github.com/insarlab/MintPy/blob/main/.github/ISSUE_TEMPLATE/bug_report.md) to provide enough information to facilitate the diagnose and error re-production.
