### ISSUE TITLE
How to create a watermask file when using ISCE with stackSentinel?

### ISSUE THREAD

**Issue by Arctic-Ambrun** [insarlab/MintPy#847]
I used createWaterMask.py, turns out to show that there`s not lat.rdr.xml and lon.rdr.xml
Is there and other methods to obtain a watermask file? or what kind of the water mask file is required?

**Comment by yunjunz** [comment]
Here are two methods to create a water mask for mintpy processing:

https://github.com/insarlab/MintPy-tutorial/blob/main/applications/water_mask.ipynb
