### ISSUE TITLE
Error when running remove_ramp.py

### ISSUE THREAD

**Issue by bjmarfito** [insarlab/MintPy#861]
**Description of the problem**

The remove_ramp.py produces an error when I include a mask file generated from generate_mask.py.

**Full script that generated the error**

```
(isce2expe) [bryanjim001@hpc-gekko1 insar]$ remove_ramp.py geo_filt_msk.unw -m geo_unw.msk -s linear -o geo_filt_msk_deramped.unw
```

**Full error message**

```
remove linear ramp from file: geo_filt_msk.unw
read mask file: geo_unw.msk
writing >>> geo_filt_msk_deramped.unw
write file: geo_filt_msk_deramped.unw
write file: geo_filt_msk_deramped.unw.rsc
add/update the following metadata to file:
Traceback (most recent call last):
  File "/home/bryanjim001/tools/MintPy/mintpy/cli/remove_ramp.py", line 150, in <module>
    main(sys.argv[1:])
  File "/home/bryanjim001/tools/MintPy/mintpy/cli/remove_ramp.py", line 137, in main
    ut.run_deramp(
  File "/home/bryanjim001/tools/MintPy/mintpy/utils/utils1.py", line 902, in run_deramp
    add_attribute(out_file, extra_meta, print_msg=True)
  File "/home/bryanjim001/tools/MintPy/mintpy/utils/utils1.py", line 570, in add_attribute
    with h5py.File(File, 'r+') as f:
  File "/home/bryanjim001/.conda/envs/isce2expe/lib/python3.9/site-packages/h5py/_hl/files.py", line 533, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/home/bryanjim001/.conda/envs/isce2expe/lib/python3.9/site-packages/h5py/_hl/files.py", line 228, in make_fid
    fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 106, in h5py.h5f.open
OSError: Unable to open file (file signature not found)
```

**System information**

* Operating system: CentOS 7
* Python environment: conda
* MintPy version: b71a6cf9c4dbdb675a10801a8226605967bda650
* Your custom / default template file (if the bug is related to a specific dataset): N/A

**Comment by yunjunz** [comment]
Thank you @bjmarfito for finding out about this issue, it's fixed by the PR above. Cheers.

**Comment by bjmarfito** [comment]
Thank you @yunjunz. It fixes the error but the area of the output is different when I deramped it. I attached the two images whoch are IFG before and after deramping for your reference.
![Before_deramping](https://user-images.githubusercontent.com/21336508/195987634-cf5bb12e-9145-4fb2-8600-e6fa21d6cdfb.png)
![After_deramping](https://user-images.githubusercontent.com/21336508/195987636-10028afc-3995-4e23-a755-cbf168161fab.png)

**Comment by yunjunz** [comment]
Hi @bjmarfito, I agree that the `geo_filt_msk_noref_deramp.unw` does not make sense, however, I could not re-produce this issue (my testing on the *.unw file using the Fernandina example dataset works as expected). Could you try to debug this and/or provide more description and data?

**Comment by bjmarfito** [comment]
Hi @yunjunz, thank you for your suggestions. Yeah, I will find the cause of this issue and debug it first. 

I used alosStack to generate this output from a pair of ALOS-2 ScanSAR data. Then, I deramped the unwrapped interferogram. I can provide you the data once I can't solve the issue myself.

**Comment by bjmarfito** [comment]
Hi @yunjunz, I already find the issue. The issue is that the writefile.py recognizes the no. of bands as 1 instead of 2 for the .unw file after deramping. I will submit a PR to propose a fix for this one.

**Comment by yunjunz** [comment]
That's great @bjmarfito, and thank you for the fix! `alosStack` write `.unw` file in 1-band, instead of the commonly used 2-band format. MintPy could read this difference adaptively, but the writing part is fixed to 2-band only.

**Comment by bjmarfito** [comment]
Hi @yunjunz, thank you for merging my PR. However, I found out that the deramping makes the magnitude data same with the phase data. alosStack also outputs 2-band which contains the magnitude and phase.

Before deramping
<img width="1601" alt="Screenshot 2022-10-17 at 10 58 24 AM" src="https://user-images.githubusercontent.com/21336508/196079797-ea24bc97-86db-4637-a24e-3e3792cc09b2.png">

After deramping

<img width="1587" alt="Screenshot 2022-10-17 at 10 56 31 AM" src="https://user-images.githubusercontent.com/21336508/196079841-815e13af-0087-4872-baa2-f2c750b1bbac.png">

**Comment by yunjunz** [comment]
@bjmarfito this is expected, and okay for interferometry, as the interferogram amplitude data is not used anymore anyway.

**Comment by bjmarfito** [comment]
You're right. Thank you @yunjunz!
