### ISSUE TITLE
abnormal large residual from `dem_error` for `timeseries_rms`

### ISSUE THREAD

**Issue by yunjunz** [insarlab/MintPy#892]
With the default minization in `dem_error.py` switched from `phase` to `phase velocity` in #875, I noticed the time-series residual after `dem_error` got much bigger for one dataset I have, as shown below. Although this change of behavior is reasonable given their different objective functions, they are not suitable anymore for the following `timeseries_rms` step in `smallbaselineApp`. 

The right way would be: keep phase velocity as default in `correct_topography`, move the `residual_RMS` step after the time function fitting in the `velocity` step, which has more powerful / advanced time func capability; then we won't need the TS residual from `dem_error` anymore. Before this change, I would like to revert #875 to minimize its impact on `timeseries_rms`.

@mirzaees @hfattahi let me know what do you think please.

+ Residual time-series with **phase** minimization

<img width="1612" alt="ts_res_pha" src="https://user-images.githubusercontent.com/13143710/200223995-c63d9c29-d955-4a5f-8eed-02d500138154.png">

+ Residual time-series with **phase velocity** minimization

<img width="1612" alt="ts_res_phaVelo_v1" src="https://user-images.githubusercontent.com/13143710/200224074-75f2e38e-c05a-4469-ab64-946072285d99.png">

**Comment by falkamelung** [comment]
The one example we looked at in detail (Miami full-res) you absolutely need phase velocity. And isn't that what we would expect? I have to look at the paper again, but don't Fattahi&Amelung 2013 make the case that phase velocity needs to be used?   Can you remind us what was the rationale to use phase minimization  in MintPy?

**Comment by yunjunz** [comment]
One could always manually turn ON the phase velocity whenever they need it. My purpose here is to not disturb other steps outside of `correct_topography`.

**Comment by mirzaees** [comment]
Hi @yunjunz!
After spending some time on this to understand why it is happening, I believe there might be another bug in the calculation of design matrix (G_defo):
https://github.com/insarlab/MintPy/blob/64ffdefa14cdff5c1024bb522a7f6f1e79de1103/mintpy/utils/time_func.py#L285-L286
I checked it for polynomial model (you might want to check other deformation models as well), I think it should be like:

```
    for i in range(1, degree+2):
        A[:,i-1] = (yr_diff**i) / np.math.factorial(i)
```

Please check it if that resolves the problem

**Comment by yunjunz** [comment]
Thank you @mirzaees for looking into this. For a polynomial with an order of 3, the math form should be:

```shell
d = c0 + c1 * t + 1/2 * c2 * t^2 + 1/6 * c3 * t^3
```

Thus, I think the current `mintpy.utils.time_func.get_design_matrix4polynomial_func()` is correct. Nevertheless, I don't think the coefficient scale of the time function will affect the least-squares fitting, as the estimated coefficient itself will be scaled proportionally.

Let me try to be clear, both "phase" and "phase velocity" are pretty good on the DEM error estimation, "phase velocity" is better in your testing, which is reasonable, as also shown in the small fitting residual below using the same dataset above (residual phase velocity, please ignore the unit in the colorbar, I did not change it accordingly in my quick hacking):

<img width="1612" alt="Screen Shot 2022-11-07 at 9 41 18 PM" src="https://user-images.githubusercontent.com/13143710/200484229-060138f8-e0d1-42ba-bc0a-7b196b89447a.png">

This is expected because we are minimizing the "residual phase velocity" in this setting, meanwhile the "residual phase" is not guaranteed to be small. Since "residual phase" is a more physically meaningful parameter for the noise evaluation, I would prefer to use `phase` as default.

In the future, after we move the noise evaluation step after `velocity` or time function fitting, we won't need the fitting residual from dem_error anymore, then it's fine to use either `phase velocity` or `phase` as default in `dem_error`. Do you agree?

**Comment by mirzaees** [comment]
Hi @yunjunz, I agree that your solution might fix this problem but still something is wrong with the design matrix, although the effect might be negligible in the displacement timeseries estimation.

according to equation 7 (Fattahi and Amelung, 2013) the constant term (c0) is the last one (psi) which usually goes to the left side of the equation in the unknowns calculation. The unknown vector is [c1, c2, c3, z] in your representation and when you use the phase velocity, the design matrix should look like equation 10 in the paper, one column that is coefficients of c1 are all 1. In the current version of the code, it will be zero and the design matrix will have a rank deficient. It does not look like equation 10.

The phase velocity showed to be better in the estimation of dem error but I found dem_err_std is abnormal. and as you said phase residuals are also abnormal which should not be.

**Comment by yunjunz** [comment]
Hi @mirzaees, I adjusted the order of the design matrix "A" in the code from Fattahi & Amelung (2013), to support generic poly order and other time functions. One example is shown in equation (S3) in Yunjun et al. (2019). Below is the design matrix for "phase" G0 and for "phase velocity" G, and they both look reasonable and consistent with Fattahi & Amelung (2013) to me. I would be happy to be proven wrong with real tests and examples.

```python
(Pdb) G0[:4,:]
array([[ 9.0172085e-05,  1.0000000e+00,  0.0000000e+00,  0.0000000e+00],
       [ 6.0772269e-05,  1.0000000e+00,  1.6427105e-02,  1.3492488e-04],
       [-4.8675432e-05,  1.0000000e+00,  3.2854211e-02,  5.3969951e-04],
       [ 1.3223269e-04,  1.0000000e+00,  4.9281314e-02,  1.2143239e-03]],
      dtype=float32)
(Pdb) G[:4,:]
array([[-0.00178972,  0.        ,  1.0000039 ,  0.00821358],
       [-0.00666261,  0.        ,  0.9999967 ,  0.02464057],
       [ 0.01101275,  0.        ,  0.9999966 ,  0.04106762],
       [-0.01237925,  0.        ,  1.000004  ,  0.05749509]],
      dtype=float32)
```

For now, I will go ahead to change the default setting in smallbaselineApp.py.

**Comment by mirzaees** [comment]
@yunjunz I don't have a problem with changing defaults as you wish but G0 is wrong.
There should not be a column of 1 in G0 and a column of 0 in G. They should be coefficients of C1, C2, C3 and Z
C0 is not an unknown to have coefficient in the design matrix

@hfattahi could you please comment on this? maybe I am wrong

**Comment by yunjunz** [comment]
@mirzaees for "phase" minimization with G0, `c0` is unknown based on my understanding. The zero value in G corresponds to c0, and does not affect the inversion; I kept it there for the convenience of matrix operation. All these can be tested and validated in code, aren't they?

**Comment by mirzaees** [comment]
@yunjunz well the matrix operation does not become convenient this way. Obviously you have a rank deficient matrix and residuals are abnormal. whereas for me after correcting the matrix, everything looks fine. C0 is not unknown, that is a constant and in the inversion it is estimated as residual

**Comment by mirzaees** [comment]
Hi @Yunjun
thank you for helping me understand your point and now I agree with you
we can calculate the correct dem error std with removing the zero column in G
but we simply cannot calculate the timeseries residuals using phase velocity history, and the solution is as you mentioned to calculate them after velocity step
So what you did makes sense to set default on phase history temporarily

**Comment by yunjunz** [comment]
Great discussion with you offline @mirzaees, now we are on the same page with all the details. I issued the PR above for the all-zero column removal. Review it when you got a chance please.

Here is what we agreed on: the polynomial function used in the phase history minimization should have the constant `c0` as an unknown parameter, which could be estimated during the least squares inversion; however, it will be lost if using phase velocity minimization, resulting in an all-zero column in the design matrix.
