### ISSUE TITLE
save_gmt.py  geo_velocity.h5

### ISSUE THREAD

**Issue by wsjbest** [insarlab/MintPy#900]
**Description of the problem**

when I run the save_gmt.py  geo_velocity.h5, I do not find the pre_gmt.py  in the mintpy and maybe same script is defect.

**Full script that generated the error**

```
####################################################################################
def main(iargs=None):
    # parse
    inps = cmd_line_parse(iargs)

    # import
    from mintpy.prep_gmt import save_gmt

    # run
    save_gmt(inps)


####################################################################################
```

**Full error message**

```
ModuleNotFoundError: No module named 'mintpy.prep_gmt'
```

**System information**

* Operating system: Linux-Ubuntu 20.04
* Python environment: 3.8
* MintPy version: Version 1.4.1

**Comment by yunjunz** [comment]
Thank you @wsjbest for reporting the issue. It's a typo and has been fixed in #901. Cheers!
