### ISSUE TITLE
asc_desc2horz_vert.py does not work with timeseries

### ISSUE THREAD

**Issue by javjrg** [insarlab/MintPy#932]
**Description of the problem**

I have two timeseries files from ascending and descending tracks. When I tried to run asc_desc2horz_vert.py on them it fails 

**Full script that generated the error**

```
asc_desc2horz_vert.py ../Caren_AS/geo/geo_timeseries_SET_ERA5_demErr.h5 ../Caren_DES/geo/geo_timeseries_SET_ERA5_demErr.h5
```

**Full error message**

```
overlapping area in SNWE: (-34.300000319999995, -33.9, -71.4, -70.8999996)
Traceback (most recent call last):
  File "/home/javjrg/miniconda3/envs/mintpy/bin/asc_desc2horz_vert.py", line 8, in <module>
    sys.exit(main())
  File "/home/javjrg/tools/MintPy/src/mintpy/cli/asc_desc2horz_vert.py", line 137, in main
    run_asc_desc2horz_vert(inps)
  File "/home/javjrg/tools/MintPy/src/mintpy/asc_desc2horz_vert.py", line 186, in run_asc_desc2horz_vert
    dlos[i, :] = readfile.read(fname, box=box, datasetName=inps.ds_name)[0]
ValueError: could not broadcast input array from shape (60,1440,1800) into shape (1440,1800)
```

**System information**

* Operating system: Linux-Ubuntu (WSL)
* Python environment: conda
* MintPy version: 1.5.0.post9, date 2022-12-12

**Comment by yunjunz** [comment]
This script does not work with time-series, because time-series from asc/desc orbits do not share the same date, thus, we cannot really decompose them into horizontal/vertical time-series without strong assumptions.

**Comment by javjrg** [comment]
Thanks a lot for your answer!

best regards
