### ISSUE TITLE
enforced steps in smallbaselineApp.py

### ISSUE THREAD

**Issue by hfattahi** [insarlab/MintPy#94]
Currently the smallbaselineApp.py expects timeseries_ramp_demErr.h5 to estimate "velocity". This means that the 'deramp', 'correct_topography' are mandatory before velocity estimation. I'm wondering if enforcing these two steps before velocity estimation is intentional or not?

**Comment by yunjunz** [comment]
Hi @hfattahi, none of the four phase corrections (LOD, tropo, ramp, dem error) are mandatory in `smallbaselineApp.py`, `deramp` (turned OFF by default) and `correct_topography` (turned ON by default) can be turn off by setting:

```
mintpy.topographicResidual                    = no
mintpy.deramp          = no
```

`get_timeseries_filename()` in smallbaselineApp.py generates the input and output filenames for steps involving time-series files. The input of `velocity` step is determined as the last file after the four phase correction steps, same as the input of `reference_date` step: https://github.com/insarlab/MintPy/blob/master/mintpy/smallbaselineApp.py#L629

**Comment by hfattahi** [comment]
That's right thanks @yunjunz . This is not an issue and I close it.
