### ISSUE TITLE
timeseries_rms.py does not overwrite `rms_timeseriesResidual_ramp.txt` when it should

### ISSUE THREAD

**Issue by falkamelung** [insarlab/MintPy#969]
I would like to report a minor, minor, minor  bug: `timeseries_rms.py` does not seem to properly check the ages of  files. `ms_timeseriesResidual_ramp.txt` is not updated after  `timeseriesResidual.h5` has been updated.  

I run `timeseries_rms.py timeseriesResidual.h5 -t smallbaselineApp.cfg`.  I would expect that an new `ms_timeseriesResidual_ramp.txt` is created if `timeseriesResidual.h5` is newer, but this does not seem to happen.

As you can see, `timeseriesResidual.h5` is newer than `rms_timeseriesResidual_ramp.txt` :
```
lst
-rw-rw----  1 tg851601      4563 Mar  6 14:52 rms_timeseriesResidual_ramp.txt
-rw-rw----  1 tg851601     21818 Mar  6 14:52 rms_timeseriesResidual_ramp.pdf
-rw-rw----  1 tg851601 509866440 Mar  6 14:54 timeseriesResidual.h5
```
Not I run `timeseries_rms.py`: 
```
timeseries_rms.py timeseriesResidual.h5 -t smallbaselineApp.cfg

read options from template file: smallbaselineApp.cfg
['/scratch/05861/tg851601/MiamiSenAT48/miaplpy_t3aPhaseVelo_201509_202111/network_single_reference/rms_timeseriesResidual_ramp.txt'] exists and is newer than ['timeseriesResidual_ramp.h5', 'maskTempCoh.h5'] --> skip.
read timeseries residual RMS from file: /scratch/05861/tg851601/MiamiSenAT48/miaplpy_t3aPhaseVelo_201509_202111/network_single_reference/rms_timeseriesResidual_ramp.txt
--------------------------------------------------
date with min RMS: 20190702 - 0.0044
save date to file: reference_date.txt
--------------------------------------------------
date(s) with RMS > 3.0 * median RMS (0.0264)
None.
save figure to file: /scratch/05861/tg851601/MiamiSenAT48/miaplpy_t3aPhaseVelo_201509_202111/network_single_reference/rms_timeseriesResidual_ramp.pdf
```
It does check the age of `timeseriesResidual_ramp.h5`. Should it also check the age of `timeseriesResidual_ramp.h5`?

Just want to let you know.  Removing all files that I wasn't to have updated works. It is really minor, minor, minor.

(NB:  I removed `timeseriesResidual_ramp.h5` and I believe it didi not work either although I might be doing a mistake here)

**Description of the problem**

**Full script that generated the error**

```
PASTE CODE HERE
```

**Full error message**

```
PASTE ERROR MESSAGE HERE
```

**System information**

* Operating system: 
* Python environment: 
* MintPy version: 
* Your custom / default template file (if the bug is related to a specific dataset):

**Comment by yunjunz** [comment]
Thank you @falkamelung for reporting this issue. I agree with you that we should always use the `timeseriesResidual.h5` file for the `run_or_skip` checking, instead of the `timeseriesResidual_ramp.h5` file. The above PR fixes this from my local testing. Cheers.
