### ISSUE TITLE
load data ERROR with Gamma dataset

### ISSUE THREAD

**Issue by Yaoshangheng** [insarlab/MintPy#984]
Dear professor
I am using MintPy1.5.0 on Ubuntu21.04.
I have successful I tested mintpy with the example dataset and it passed.
However，When I processing my GAMMA data，It goes wrong.
1、Here is my command record.
![1](https://user-images.githubusercontent.com/20898434/226294480-02b56b2f-4290-43e7-8767-8e66724d29af.jpg)
![2](https://user-images.githubusercontent.com/20898434/226294495-5c0cacf6-e9e6-41ca-b8f7-796833a41a4c.jpg)
![3](https://user-images.githubusercontent.com/20898434/226294508-fc45cee5-0397-49bf-ac3e-b9dd9a1fcac6.jpg)
![1](https://user-images.githubusercontent.com/20898434/226299194-d1933e80-f0ee-4c9e-b89f-848ccdfc71b0.jpg)

2、my directory structure
![2](https://user-images.githubusercontent.com/20898434/226299472-13941e9e-fddd-43d5-955e-f094dd88352d.jpg)

![6](https://user-images.githubusercontent.com/20898434/226297100-7f669474-4e4a-4ff2-a6fa-ff47d00182ca.jpg)
ercontent.com/20898434/226297003-9d33baec-5338-40c7-bdd3-21b74b69907e.jpg)
![7](https://user-images.githubusercontent.com/20898434/226297122-63695afc-2b58-4579-8c44-a2760d61a27c.jpg)
![8](https://user-images.githubusercontent.com/20898434/226297132-1d9cfb96-0cc8-4d58-b914-43e37ff48e93.jpg)

3、GalapagosEnvA2t061.txt
![9](https://user-images.githubusercontent.com/20898434/226297665-c9c0f77f-a2f0-4f01-802d-f0cf7ea49548.jpg)

Bestwish！

**Comment by yunjunz** [comment]
Since the issue occurred during the `load_data` step, and more specifically the `prep_gamma.py` command as in the printed-out message, I would recommend rerunning the `prep_gamma.py` command to see the more detailed error information. A rough guess could be that the Gamma and MintPy are not installed in the same environment, thus, `prep_gamma.py` could not call the gamma command line.

**Comment by keepfighting666** [comment]
> Dear professor I am using MintPy1.5.0 on Ubuntu21.04. I have successful I tested mintpy with the example dataset and it passed. However，When I processing my GAMMA data，It goes wrong. 1、Here is my command record. ![1](https://user-images.githubusercontent.com/20898434/226294480-02b56b2f-4290-43e7-8767-8e66724d29af.jpg) ![2](https://user-images.githubusercontent.com/20898434/226294495-5c0cacf6-e9e6-41ca-b8f7-796833a41a4c.jpg) ![3](https://user-images.githubusercontent.com/20898434/226294508-fc45cee5-0397-49bf-ac3e-b9dd9a1fcac6.jpg) ![1](https://user-images.githubusercontent.com/20898434/226299194-d1933e80-f0ee-4c9e-b89f-848ccdfc71b0.jpg)
> 
> 2、my directory structure ![2](https://user-images.githubusercontent.com/20898434/226299472-13941e9e-fddd-43d5-955e-f094dd88352d.jpg)
> 
> ![6](https://user-images.githubusercontent.com/20898434/226297100-7f669474-4e4a-4ff2-a6fa-ff47d00182ca.jpg) ercontent.com/20898434/226297003-9d33baec-5338-40c7-bdd3-21b74b69907e.jpg) ![7](https://user-images.githubusercontent.com/20898434/226297122-63695afc-2b58-4579-8c44-a2760d61a27c.jpg) ![8](https://user-images.githubusercontent.com/20898434/226297132-1d9cfb96-0cc8-4d58-b914-43e37ff48e93.jpg)
> 
> 3、GalapagosEnvA2t061.txt ![9](https://user-images.githubusercontent.com/20898434/226297665-c9c0f77f-a2f0-4f01-802d-f0cf7ea49548.jpg)
> 
> Bestwish！

Hello, have you solved this problem? I'm encountering the same error too. can you give me some advice? Thanks.
![image](https://github.com/user-attachments/assets/acfb8aae-a535-4094-83df-cdd7690c4b98)
