### ISSUE TITLE
Is there a command or other method to convert a TIF file from geographic coordinate system to radar coordinate system?

### ISSUE THREAD

**Issue by songzwgithub** [insarlab/MintPy#988]
Hello everyone,

I used the geocode.py command to convert filt_fine.unw from radar coordinate system to geographic coordinate system (filt_fine.unw.geo.tif), but I realized that there is no command to convert it back. Is there a command or other method to convert a TIF file from geographic coordinate system to radar coordinate system?

Best regards!

**Comment by yunjunz** [comment]
You could use the geocode.py --geo2radar option to convert it back, check geocode.py --help for example usage. This is how i generated the water mask in radar coordinates from products downloaded in geo coordinates. Note that this option is only supported for ISCE products, which has the lookup table files (lat.rdr, lon.rdr) in radar coordinates.

**Comment by songzwgithub** [comment]
> You could use the geocode.py --geo2radar option to convert it back, check geocode.py --help for example usage. This is how i generated the water mask in radar coordinates from products downloaded in geo coordinates. Note that this option is only supported for ISCE products, which has the lookup table files (lat.rdr, lon.rdr) in radar coordinates.

Thank you very much! I have done it with --geo2radar option.
